package com.catering.v2s.app.edge.operations.access;

import com.catering.v2s.app.edge.operations.session.OperationsSessionResolver;
import com.catering.v2s.app.edge.generated.wire.SortDirection;
import com.catering.v2s.app.edge.generated.wire.WorkspaceInvitation;
import com.catering.v2s.app.edge.generated.wire.WorkspaceInvitationPage;
import com.catering.v2s.app.edge.generated.wire.WorkspaceInvitationSortKey;
import com.catering.v2s.app.edge.generated.wire.WorkspaceInvitationStatus;
import com.catering.v2s.app.edge.generated.wire.WorkspaceOperationsInvitationActionRequest;
import com.catering.v2s.app.edge.generated.wire.WorkspaceOperationsInvitationCreateRequest;
import com.catering.v2s.app.edge.workspaceiam.WorkspaceInvitationPageWireMapper;
import com.catering.v2s.app.edge.workspaceiam.WorkspaceInvitationWireMapper;
import com.catering.v2s.workspace.iam.application.WorkspaceAuthenticationService;
import com.catering.v2s.workspace.iam.application.WorkspaceInvitationService;
import com.catering.v2s.workspace.iam.application.WorkspaceUserService;
import com.catering.v2s.app.edge.session.EdgeRequestContext;
import java.util.List;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/operations/group-workspaces/{groupWorkspaceKey}/user-management")
public final class OperationsWorkspaceInvitationController {
    private final OperationsSessionResolver sessions; private final WorkspaceInvitationService invitations; private final WorkspaceUserService user;
    public OperationsWorkspaceInvitationController(OperationsSessionResolver sessions, WorkspaceInvitationService invitations, WorkspaceUserService user) { this.sessions = sessions; this.invitations = invitations; this.user = user; }
    @GetMapping("/group/invitations") WorkspaceInvitationPage groupList(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @RequestParam(required = false) String scopeRef, @RequestParam(required = false) String mobile, @RequestParam(required = false) String organizationQuery, @RequestParam(required = false) String roleQuery, @RequestParam(required = false) WorkspaceInvitationStatus status, @RequestParam(required = false) Long expiresFrom, @RequestParam(required = false) Long expiresTo, @RequestParam(required = false) WorkspaceInvitationSortKey sort, @RequestParam(required = false) SortDirection direction, @RequestParam(defaultValue = "1") int page, @RequestParam(defaultValue = "20") int pageSize, @RequestParam long expectedContextVersion) { return list(request, groupWorkspaceKey, "GROUP", scopeRef, mobile, organizationQuery, roleQuery, status, expiresFrom, expiresTo, sort, direction, page, pageSize, expectedContextVersion); }
    @GetMapping("/region/invitations") WorkspaceInvitationPage regionList(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @RequestParam(required = false) String scopeRef, @RequestParam(required = false) String mobile, @RequestParam(required = false) String organizationQuery, @RequestParam(required = false) String roleQuery, @RequestParam(required = false) WorkspaceInvitationStatus status, @RequestParam(required = false) Long expiresFrom, @RequestParam(required = false) Long expiresTo, @RequestParam(required = false) WorkspaceInvitationSortKey sort, @RequestParam(required = false) SortDirection direction, @RequestParam(defaultValue = "1") int page, @RequestParam(defaultValue = "20") int pageSize, @RequestParam long expectedContextVersion) { return list(request, groupWorkspaceKey, "REGION", scopeRef, mobile, organizationQuery, roleQuery, status, expiresFrom, expiresTo, sort, direction, page, pageSize, expectedContextVersion); }
    @GetMapping("/project/invitations") WorkspaceInvitationPage projectList(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @RequestParam(required = false) String scopeRef, @RequestParam(required = false) String mobile, @RequestParam(required = false) String organizationQuery, @RequestParam(required = false) String roleQuery, @RequestParam(required = false) WorkspaceInvitationStatus status, @RequestParam(required = false) Long expiresFrom, @RequestParam(required = false) Long expiresTo, @RequestParam(required = false) WorkspaceInvitationSortKey sort, @RequestParam(required = false) SortDirection direction, @RequestParam(defaultValue = "1") int page, @RequestParam(defaultValue = "20") int pageSize, @RequestParam long expectedContextVersion) { return list(request, groupWorkspaceKey, "PROJECT", scopeRef, mobile, organizationQuery, roleQuery, status, expiresFrom, expiresTo, sort, direction, page, pageSize, expectedContextVersion); }
    @GetMapping("/head-company/invitations") WorkspaceInvitationPage headCompanyList(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @RequestParam(required = false) String scopeRef, @RequestParam(required = false) String mobile, @RequestParam(required = false) String organizationQuery, @RequestParam(required = false) String roleQuery, @RequestParam(required = false) WorkspaceInvitationStatus status, @RequestParam(required = false) Long expiresFrom, @RequestParam(required = false) Long expiresTo, @RequestParam(required = false) WorkspaceInvitationSortKey sort, @RequestParam(required = false) SortDirection direction, @RequestParam(defaultValue = "1") int page, @RequestParam(defaultValue = "20") int pageSize, @RequestParam long expectedContextVersion) { return list(request, groupWorkspaceKey, "HEAD_COMPANY", scopeRef, mobile, organizationQuery, roleQuery, status, expiresFrom, expiresTo, sort, direction, page, pageSize, expectedContextVersion); }
    @GetMapping("/store/invitations") WorkspaceInvitationPage storeList(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @RequestParam(required = false) String scopeRef, @RequestParam(required = false) String mobile, @RequestParam(required = false) String organizationQuery, @RequestParam(required = false) String roleQuery, @RequestParam(required = false) WorkspaceInvitationStatus status, @RequestParam(required = false) Long expiresFrom, @RequestParam(required = false) Long expiresTo, @RequestParam(required = false) WorkspaceInvitationSortKey sort, @RequestParam(required = false) SortDirection direction, @RequestParam(defaultValue = "1") int page, @RequestParam(defaultValue = "20") int pageSize, @RequestParam long expectedContextVersion) { return list(request, groupWorkspaceKey, "STORE", scopeRef, mobile, organizationQuery, roleQuery, status, expiresFrom, expiresTo, sort, direction, page, pageSize, expectedContextVersion); }

    @PostMapping("/group/invitations") ResponseEntity<WorkspaceInvitation> groupCreate(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationCreateRequest body) { return create(request, groupWorkspaceKey, "GROUP", headerKey, body); }
    @PostMapping("/region/invitations") ResponseEntity<WorkspaceInvitation> regionCreate(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationCreateRequest body) { return create(request, groupWorkspaceKey, "REGION", headerKey, body); }
    @PostMapping("/project/invitations") ResponseEntity<WorkspaceInvitation> projectCreate(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationCreateRequest body) { return create(request, groupWorkspaceKey, "PROJECT", headerKey, body); }
    @PostMapping("/head-company/invitations") ResponseEntity<WorkspaceInvitation> headCompanyCreate(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationCreateRequest body) { return create(request, groupWorkspaceKey, "HEAD_COMPANY", headerKey, body); }
    @PostMapping("/store/invitations") ResponseEntity<WorkspaceInvitation> storeCreate(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationCreateRequest body) { return create(request, groupWorkspaceKey, "STORE", headerKey, body); }

    @PostMapping("/group/invitations/{invitationId}/cancel") WorkspaceInvitation groupCancel(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID invitationId, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationActionRequest body) { return cancel(request, groupWorkspaceKey, "GROUP", invitationId, headerKey, body); }
    @PostMapping("/region/invitations/{invitationId}/cancel") WorkspaceInvitation regionCancel(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID invitationId, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationActionRequest body) { return cancel(request, groupWorkspaceKey, "REGION", invitationId, headerKey, body); }
    @PostMapping("/project/invitations/{invitationId}/cancel") WorkspaceInvitation projectCancel(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID invitationId, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationActionRequest body) { return cancel(request, groupWorkspaceKey, "PROJECT", invitationId, headerKey, body); }
    @PostMapping("/head-company/invitations/{invitationId}/cancel") WorkspaceInvitation headCompanyCancel(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID invitationId, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationActionRequest body) { return cancel(request, groupWorkspaceKey, "HEAD_COMPANY", invitationId, headerKey, body); }
    @PostMapping("/store/invitations/{invitationId}/cancel") WorkspaceInvitation storeCancel(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID invitationId, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationActionRequest body) { return cancel(request, groupWorkspaceKey, "STORE", invitationId, headerKey, body); }

    @PostMapping("/group/invitations/{invitationId}/reissue") WorkspaceInvitation groupReissue(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID invitationId, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationActionRequest body) { return reissue(request, groupWorkspaceKey, "GROUP", invitationId, headerKey, body); }
    @PostMapping("/region/invitations/{invitationId}/reissue") WorkspaceInvitation regionReissue(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID invitationId, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationActionRequest body) { return reissue(request, groupWorkspaceKey, "REGION", invitationId, headerKey, body); }
    @PostMapping("/project/invitations/{invitationId}/reissue") WorkspaceInvitation projectReissue(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID invitationId, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationActionRequest body) { return reissue(request, groupWorkspaceKey, "PROJECT", invitationId, headerKey, body); }
    @PostMapping("/head-company/invitations/{invitationId}/reissue") WorkspaceInvitation headCompanyReissue(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID invitationId, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationActionRequest body) { return reissue(request, groupWorkspaceKey, "HEAD_COMPANY", invitationId, headerKey, body); }
    @PostMapping("/store/invitations/{invitationId}/reissue") WorkspaceInvitation storeReissue(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID invitationId, @RequestHeader("Idempotency-Key") String headerKey, @RequestBody WorkspaceOperationsInvitationActionRequest body) { return reissue(request, groupWorkspaceKey, "STORE", invitationId, headerKey, body); }

    private WorkspaceInvitationPage list(EdgeRequestContext request, String groupWorkspaceKey, String expectedTargetType, String scopeRef, String mobile, String organizationQuery, String roleQuery, WorkspaceInvitationStatus status, Long expiresFrom, Long expiresTo, WorkspaceInvitationSortKey sort, SortDirection direction, int page, int pageSize, long expectedContextVersion) { var session = session(request, groupWorkspaceKey, expectedContextVersion); return WorkspaceInvitationPageWireMapper.page(invitations.managementPageForOperations(session, expectedTargetType, optionalUuid(scopeRef), pageRequest(mobile, organizationQuery, roleQuery, status, expiresFrom, expiresTo, sort, direction, page, pageSize))); }
    private ResponseEntity<WorkspaceInvitation> create(EdgeRequestContext request, String groupWorkspaceKey, String expectedTargetType, String headerKey, WorkspaceOperationsInvitationCreateRequest body) { var session = session(request, groupWorkspaceKey, body.expectedContextVersion()); matchingKey(headerKey, body.idempotencyKey()); var target = user.resolveCommandTarget(session, expectedTargetType, optionalUuid(body.scopeRef())); List<WorkspaceInvitationService.AssignmentIntent> intents = intents(body.roleIds(), target.targetType(), target.targetId()); var created = invitations.createForOperations(session.workspaceUuid(), groupWorkspaceKey, session.currentAssignmentId(), body.mobile(), intents, body.idempotencyKey(), sessions.actor(session)); return ResponseEntity.status(HttpStatus.CREATED).body(WorkspaceInvitationWireMapper.wire(invitations.managementView(created))); }
    private WorkspaceInvitation cancel(EdgeRequestContext request, String groupWorkspaceKey, String expectedTargetType, UUID invitationId, String headerKey, WorkspaceOperationsInvitationActionRequest body) { var session = session(request, groupWorkspaceKey, body.expectedContextVersion()); matchingKey(headerKey, body.idempotencyKey()); var cancelled = invitations.cancelForOperations(session.workspaceUuid(), groupWorkspaceKey, session.currentAssignmentId(), expectedTargetType, invitationId, required(body.expectedVersion()), body.idempotencyKey(), sessions.actor(session)); return WorkspaceInvitationWireMapper.wire(invitations.managementView(cancelled)); }
    private WorkspaceInvitation reissue(EdgeRequestContext request, String groupWorkspaceKey, String expectedTargetType, UUID invitationId, String headerKey, WorkspaceOperationsInvitationActionRequest body) { var session = session(request, groupWorkspaceKey, body.expectedContextVersion()); matchingKey(headerKey, body.idempotencyKey()); var reissued = invitations.reissueForOperations(session.workspaceUuid(), groupWorkspaceKey, session.currentAssignmentId(), expectedTargetType, invitationId, required(body.expectedVersion()), body.idempotencyKey(), sessions.actor(session)); return WorkspaceInvitationWireMapper.wire(invitations.managementView(reissued)); }
    private com.catering.v2s.workspace.iam.api.WorkspaceSessionReadback session(EdgeRequestContext request, String key, Long expectedContextVersion) { var session = sessions.requireWorkspace(request, key); if (expectedContextVersion != null && session.contextVersion() != expectedContextVersion) throw new WorkspaceAuthenticationService.SessionInvalidException(); return session; }
    private static List<WorkspaceInvitationService.AssignmentIntent> intents(List<String> roleIds, String type, UUID target) { if (roleIds == null || roleIds.isEmpty()) throw new com.catering.v2s.app.edge.problem.InvalidEdgeRequestException("role ids are required"); return roleIds.stream().map(OperationsWorkspaceInvitationController::uuid).map(role -> new WorkspaceInvitationService.AssignmentIntent(role, type, target)).toList(); }
    private static UUID uuid(String value) { try { return UUID.fromString(value); } catch (RuntimeException exception) { throw new com.catering.v2s.app.edge.problem.InvalidEdgeRequestException("identifier is invalid"); } }
    private static UUID optionalUuid(String value) { return value == null || value.isBlank() ? null : uuid(value); }
    private static WorkspaceInvitationService.ManagementInvitationPageRequest pageRequest(String mobile, String organizationQuery, String roleQuery, WorkspaceInvitationStatus status, Long expiresFrom, Long expiresTo, WorkspaceInvitationSortKey sort, SortDirection direction, int page, int pageSize) { return new WorkspaceInvitationService.ManagementInvitationPageRequest(mobile, organizationQuery, roleQuery, status == null ? null : status.name(), expiresFrom, expiresTo, sort == null ? WorkspaceInvitationSortKey.CREATED_AT.name() : sort.name(), direction == null ? SortDirection.DESC.name() : direction.name(), page, pageSize); }
    private static long required(Long value) { if (value == null) throw new com.catering.v2s.app.edge.problem.InvalidEdgeRequestException("expected version is required"); return value; }
    private static void matchingKey(String header, String body) { if (header == null || body == null || !header.equals(body) || header.length() < 16 || header.length() > 128) throw new com.catering.v2s.app.edge.problem.InvalidEdgeRequestException("invalid idempotency key"); }
}
