import {describe, expect, it} from 'vitest';
import {readFile} from 'node:fs/promises';

const source = await readFile(new URL('./PlatformReadPage.tsx', import.meta.url), 'utf8');
const candidateSource = await readFile(new URL('../../../app/queries/usePlatformOrganizationCandidates.ts', import.meta.url), 'utf8');
const styles = await readFile(new URL('../../../styles.css', import.meta.url), 'utf8');

describe('platform overview content tabs', () => it('uses the catalog shell refresh and server-owned ProTable filtering and sorting', () => {
  expect(source).not.toContain('platform-${kind}-refresh');
  expect(source).not.toContain('>刷新</Button>');
  expect(source).not.toContain('layout="inline"');
  expect(source).toContain("search={{labelWidth: 'auto'");
  expect(source).toContain("testId('platform-organization-filter-submit')");
  expect(source).toContain("testId('platform-contract-filter-submit')");
  expect(source).toContain('organizationOverviewQuery(tab, organizationTabState.filters, organizationTabState.page, organizationTabState.pageSize, organizationTabState.sort, organizationTabState.direction)');
  expect(source).toContain('const [organizationTabStates, setOrganizationTabStates]');
  expect(source).toContain('form={{initialValues: organizationTabState.filters}}');
  expect(source).toContain('searchConfig.form?.setFieldsValue({name: undefined, code: undefined, legalName: undefined, unifiedSocialCreditCode: undefined, status: undefined, source: undefined, projectId: undefined, brandId: undefined, tenantId: undefined, headCompanyId: undefined})');
  expect(source).toContain('searchConfig.form?.setFieldsValue({contractNo: undefined, storeId: undefined, phaseName: undefined, tenantId: undefined, itemCode: undefined, status: undefined})');
  expect(source).toContain("const legalEntityTab = tab.category === 'BUSINESS_ENTITY' && (tab.type === 'TENANT' || tab.type === 'HEAD_COMPANY')");
  expect(source).toContain("title: '法人公司'");
  expect(source).toContain("title: '统一代码'");
  expect(source).toContain('onChange={setOrganizationTab}');
  expect(source).toContain('selectedKeys={hierarchyNodeId ? [hierarchyNodeId] : []}');
  expect(source).toContain('onSelect={(keys) =>');
  expect(source).toContain('hierarchyRootProjection');
  expect(source).toContain("entityType: 'COMMERCIAL_GROUP'");
  expect(source).toContain('organizationOverviewExtensionItems(commercialGroupDefinitionQuery.data, hierarchyRoot.extensionValues)');
  expect(source).toContain('const workspaceIsInitialized = workspaceDetailQuery.data?.commercialGroup?.initialized === true');
  expect(source).toContain("tab.category !== 'HIERARCHY' || !workspaceIsInitialized");
  expect(source).toContain('const hierarchyError = workspaceDetailQuery.error ?? (workspaceIsInitialized ? hierarchyQuery.error ?? commercialGroupDefinitionQuery.error : undefined)');
  expect(source).toContain('commercialGroupDefinitionQuery.isLoading');
  expect(source).toContain("testId('platform-organization-hierarchy-uninitialized')");
  expect(source).toContain('当前集团空间尚未初始化商业集团');
  expect(source).toContain('displayedHierarchyDetail');
  expect(source).toContain("hierarchyNodeTitle('GROUP', hierarchyRootProjection.name, hierarchyRootProjection.code, hierarchyRootProjection.status)");
  expect(source).toContain('hierarchyNodeTitle(node.type, node.name, node.code, node.status)');
  expect(source).toContain("<Tag color=\"default\">已停用</Tag>");
  expect(source).not.toContain("{key: 'organization', label: '所属机构', children: hierarchyDetail.path");
  expect(source).toContain('formatNameCode(name, code)');
  expect(source).toContain('<Tag color="cyan">');
  expect(source).toContain('children: treeNodes(hierarchyRootMatchesSearch ? hierarchyQuery?.data?.regions ?? [] : filteredHierarchyRegions)');
  expect(source).toContain('findHierarchyNode');
  expect(source).toContain("placeholder=\"按名称或编码搜索\"");
  expect(source).toContain("testId('platform-organization-hierarchy-search')");
  expect(source).toContain('title="组织架构"'); expect(source).toContain('title="组织详情"');
  expect(source).toContain("'platform-organization-hierarchy-page'");
  expect(source).toContain('className="platform-organization-hierarchy-layout"');
  expect(source).toContain('platform-organization-hierarchy-tree-panel');
  expect(source).toContain('platform-organization-hierarchy-detail-panel');
  expect(source).not.toContain('maxHeight: 440');
  expect(source).not.toContain('minHeight: 360');
  expect(styles).toContain('.platform-organization-hierarchy-page');
  expect(styles).toContain('.platform-organization-hierarchy-layout');
  expect(styles).toContain('flex: 1 1 auto;');
  expect(styles).toContain('.platform-organization-hierarchy-detail-panel > .ant-card-body');
  expect(source).toContain('styles={{label: {width: 164}}}');
  expect(source).toContain('filterHierarchyNodes'); expect(source).toContain('adminHierarchyCollator');
  expect(source).toContain('hierarchyNameCollator.compare(left.name, right.name)');
  expect(source).toContain('hierarchySearchMatches(node, query) || children.length');
  expect(source).toContain("label: '项目分期名称'");
  expect(source).toContain('selectedHierarchyNode?.phases');
  expect(source).not.toContain("key: 'commercial-group'");
  expect(source).toContain('sort: contractSort, direction: contractDirection');
  expect(source).toContain("dataIndex: 'storeId'");
  expect(source).toContain("dataIndex: 'phaseName'");
  expect(source).toContain("dataIndex: 'tenantId'");
  expect(source).toContain("dataIndex: 'itemCode'");
  expect(source).toContain("dataIndex: 'itemSummary'");
  expect(source).toContain("row.items.map((item) => item.code).join('、')");
  expect(source).toContain("placeholder: '搜索门店名称或编码'");
  expect(source).toContain('usePlatformOrganizationCandidates');
  expect(candidateSource).toContain("candidateUsage: 'CONTRACT_LIST'");
  expect(source).not.toContain('contractFilterOptions');
  expect(source).toContain("dataIndex: 'items'");
  expect(source).toContain("row.projectRef.name");
  expect(source).toContain('setContractSort(nextSort)');
  expect(source).toContain("if (!current?.order) { setContractSort('UPDATED_AT'); setContractDirection('DESC'); return; }");
  expect(source).toContain("current.columnKey === 'effectiveFrom' ? 'EFFECTIVE_FROM'");
  expect(source).toContain("title: '起止日期'");
  expect(source).toContain("dataIndex: 'project'");
  expect(source).toContain("dataIndex: 'brand'");
  expect(source).toContain("dataIndex: 'tenant'");
  expect(source).toContain("dataIndex: 'headCompanyId'");
  expect(source).toContain("dataIndex: 'headCompany'");
  expect(source).toContain("title: '别名'");
  expect(source).toContain("title: '备注'");
  expect(source).toContain("row.project ? formatNameCode(row.project.name, row.project.code) : '—'");
  expect(source).toContain("row.brand ? formatNameCode(row.brand.name, row.brand.code) : '—'");
  expect(source).toContain("row.tenant ? formatNameCode(row.tenant.name, row.tenant.code) : '—'");
  expect(source).toContain("row.headCompany ? formatNameCode(row.headCompany.name, row.headCompany.code) : '未设置'");
  expect(source).not.toMatch(/title:\s*['"]操作['"]/);
}));
