events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    map $http_x_edge_auth $client_edge_auth {
        default "";
    }

    server {
        listen 8080;
        server_name _;

        include /etc/nginx/r3/platform-admin-route.conf;
        include /etc/nginx/r3/operations-admin-route.conf;

        location = /_external_auth {
            internal;
            proxy_pass ${R3_EXTERNAL_ACCESS_PROVIDER};
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
        }
    }
}
