/**
 * The single test-id vocabulary for the catalog workbench.
 *
 * Surface ids are stable product surfaces.  Row and field ids are derived from
 * business identities, never from array positions or random values, so a
 * locator continues to point at the same business fact after sorting or
 * pagination.
 */
export const catalogTestIds = {
  surface: {
    storeWorkbench: 'catalog-store-workbench',
    brandWorkbench: 'catalog-brand-workbench',
    workbenchToolbar: 'catalog-workbench-toolbar',
    navigationTree: 'catalog-navigation-tree',
    itemTable: 'catalog-item-table',
    skuRows: 'catalog-sku-rows',
    categoryTaskModal: 'catalog-category-task-modal',
    batchTaskModal: 'catalog-batch-task-modal',
    itemViewDrawer: 'catalog-item-view-drawer',
    itemViewSummary: 'catalog-item-view-summary',
    itemViewIdentifiers: 'catalog-item-view-identifiers',
    itemViewSkus: 'catalog-item-view-skus',
    itemViewAttributes: 'catalog-item-view-attributes',
    itemViewOrderOptions: 'catalog-item-view-order-options',
    itemViewPreparation: 'catalog-item-view-preparation',
    itemViewInventory: 'catalog-item-view-inventory',
    itemViewComposite: 'catalog-item-view-composite',
    itemViewReferences: 'catalog-item-view-references',
    itemViewMedia: 'catalog-item-view-media',
    itemViewSyncSource: 'catalog-item-view-sync-source',
    itemViewTemporary: 'catalog-item-view-temporary',
    itemCreateModal: 'catalog-item-create-modal',
    itemEditDrawer: 'catalog-item-edit-drawer',
    itemEditBasic: 'catalog-item-edit-basic',
    itemEditIdentifiers: 'catalog-item-edit-identifiers',
    itemEditSkus: 'catalog-item-edit-skus',
    skuEditIdentifiers: 'catalog-sku-edit-identifiers',
    skuEditPreparation: 'catalog-sku-edit-preparation',
    itemEditAttributes: 'catalog-item-edit-attributes',
    itemEditOrderOptions: 'catalog-item-edit-order-options',
    itemEditPreparation: 'catalog-item-edit-preparation',
    itemEditInventory: 'catalog-item-edit-inventory',
    itemEditComposite: 'catalog-item-edit-composite',
    promotionTaskModal: 'catalog-promotion-task-modal',
    lifecycleConfirm: 'catalog-lifecycle-confirm',
    configDrawer: 'catalog-config-drawer',
    configTags: 'catalog-config-tags',
    configUnits: 'catalog-config-units',
    configSkuAttributes: 'catalog-config-sku-attributes',
    configProductionTags: 'catalog-config-production-tags',
    configAttributes: 'catalog-config-attributes',
    configOrderOptions: 'catalog-config-order-options',
    configQuickCreate: 'catalog-config-quick-create',
    configAtomModal: 'catalog-config-atom-modal',
    configDefinitionEditor: 'catalog-config-definition-editor',
    brandCopyDrawer: 'catalog-brand-copy-drawer',
    localCopyDrawer: 'catalog-local-copy-drawer',
  },
  control: {
    tableSelectAll: 'catalog-item-table-select-all',
    tableRefresh: 'catalog-item-table-refresh',
    viewSwitch: 'catalog-workbench-view-switch',
    brandSwitch: 'catalog-workbench-brand-switch',
    treeSearch: 'catalog-navigation-tree-search',
    resultKeyword: 'catalog-result-keyword',
    resultStatus: 'catalog-result-status',
    resultSource: 'catalog-result-source',
    resultReset: 'catalog-result-reset',
    workbenchRetry: 'catalog-workbench-retry',
    createOpen: 'catalog-item-create-open',
    createName: 'catalog-item-create-name',
    createCode: 'catalog-item-create-code',
    createShape: 'catalog-item-create-shape',
    createCategory: 'catalog-item-create-category',
    createSubmit: 'catalog-item-create-submit',
    createCancel: 'catalog-item-create-cancel',
    editSave: 'catalog-item-edit-save',
    editCancel: 'catalog-item-edit-cancel',
    editClose: 'catalog-item-edit-close',
    viewEdit: 'catalog-item-view-edit',
    statusEnable: 'catalog-item-status-enable',
    statusDisable: 'catalog-item-status-disable',
    statusVoid: 'catalog-item-status-void',
    lifecycleConfirmYes: 'catalog-lifecycle-confirm-yes',
    lifecycleConfirmNo: 'catalog-lifecycle-confirm-no',
    dirtyDiscard: 'catalog-item-dirty-discard',
    dirtyContinue: 'catalog-item-dirty-continue',
    configSearch: 'catalog-config-search',
    configStatus: 'catalog-config-status',
    configCreate: 'catalog-config-create',
    configSave: 'catalog-config-save',
    configClose: 'catalog-config-close',
  },
  static: {
    attributeDefinitionDrawer: 'catalog-attribute-definition-drawer',
    attributeDefinitionList: 'catalog-attribute-definition-list',
    attributeDefinitionLibrary: 'catalog-attribute-definition-library',
    batchOutcomeClose: 'catalog-batch-outcome-close',
    batchOutcomeFailures: 'catalog-batch-outcome-failures',
    brandCopyCandidatesNext: 'catalog-brand-copy-candidates-next',
    brandCopyDrawer: 'catalog-brand-copy-drawer',
    brandCopyPreflightNext: 'catalog-brand-copy-preflight-next',
    brandCopySelectionNext: 'catalog-brand-copy-selection-next',
    brandCopySourceKeyword: 'catalog-brand-copy-source-keyword',
    categoryActionModal: 'catalog-category-action-modal',
    categoryCode: 'catalog-category-code',
    categoryCreateRoot: 'catalog-category-create-root',
    categoryName: 'catalog-category-name',
    copyBlockedDefinitions: 'catalog-copy-blocked-definitions',
    copyConfirm: 'catalog-copy-confirm',
    copyDirtyContinue: 'catalog-copy-dirty-continue',
    copyDirtyDiscard: 'catalog-copy-dirty-discard',
    copyExecute: 'catalog-copy-execute',
    copyPreflight: 'catalog-copy-preflight',
    copyPreflightRetry: 'catalog-copy-preflight-retry',
    copyPreflightStale: 'catalog-copy-preflight-stale',
    copyProblem: 'catalog-copy-problem',
    copyResult: 'catalog-copy-result',
    copyResultClose: 'catalog-copy-result-close',
    createShapeDescription: 'catalog-create-shape-description',
    dictionaryCode: 'catalog-dictionary-code',
    dictionaryCreate: 'catalog-dictionary-create',
    dictionaryCancel: 'catalog-dictionary-cancel',
    dictionaryOpenCreate: 'catalog-dictionary-open-create',
    dictionaryDrawer: 'catalog-dictionary-drawer',
    dictionaryCreateModal: 'catalog-dictionary-create-modal',
    dictionaryDirtyContinue: 'catalog-dictionary-dirty-continue',
    dictionaryDirtyDiscard: 'catalog-dictionary-dirty-discard',
    dictionaryName: 'catalog-dictionary-name',
    dictionaryNameEditModal: 'catalog-dictionary-name-edit-modal',
    dictionaryPagination: 'catalog-dictionary-pagination',
    dictionaryProblem: 'catalog-dictionary-problem',
    dictionaryStatusChangeModal: 'catalog-dictionary-status-change-modal',
    dictionaryTable: 'catalog-dictionary-table',
    dictionaryTabs: 'catalog-dictionary-tabs',
    inventoryBatchStatus: 'catalog-inventory-batch-status',
    inventoryCopyPreflight: 'catalog-inventory-copy-preflight',
    inventoryItemPagination: 'catalog-inventory-item-pagination',
    inventoryNoAuthorizedBrand: 'catalog-inventory-no-authorized-brand',
    inventoryScopeRequired: 'catalog-inventory-scope-required',
    inventorySelectionSummary: 'catalog-inventory-selection-summary',
    inventorySmartViewExplanation: 'catalog-inventory-smart-view-explanation',
    inventoryTreeLoading: 'catalog-inventory-tree-loading',
    inventoryWorkbenchProblem: 'catalog-inventory-workbench-problem',
    inventoryWorkbenchScopeForbidden: 'catalog-inventory-workbench-scope-forbidden',
    inventoryBomAdd: 'catalog-inventory-bom-add',
    inventoryBomFacts: 'catalog-inventory-bom-facts',
    inventoryBomLines: 'catalog-inventory-bom-lines',
    inventoryBomWorkbench: 'catalog-inventory-bom-workbench',
    inventoryConsumptionCountingUnit: 'catalog-inventory-counting-unit',
    inventoryConsumptionConversionFactor: 'catalog-inventory-conversion-factor',
    inventoryDirectConfig: 'catalog-inventory-direct-config',
    inventoryDirectFacts: 'catalog-inventory-direct-facts',
    inventoryDirectThreshold: 'catalog-inventory-direct-threshold',
    inventoryMode: 'catalog-inventory-mode',
    inventoryOwnerCurrent: 'catalog-inventory-owner-current',
    inventoryOwnerCurrentReadonly: 'catalog-inventory-owner-current-readonly',
    inventoryOwnerEmpty: 'catalog-inventory-owner-empty',
    inventoryOwnerTree: 'catalog-inventory-owner-tree',
    itemAttributeLibraryAdd: 'catalog-item-attribute-library-add',
    itemAttributeLibraryAddModal: 'catalog-item-attribute-library-add-modal',
    itemAttributeLibraryManage: 'catalog-item-attribute-library-manage',
    itemBaseMeasureUnit: 'catalog-item-base-measure-unit',
    itemCategoryField: 'catalog-item-category-field',
    itemCategoryFieldError: 'catalog-item-category-field-error',
    itemCompositeGroupAdd: 'catalog-item-composite-group-add',
    itemCompositeGroupsEditor: 'catalog-item-composite-groups-editor',
    itemCompositeGroupsReadonly: 'catalog-item-composite-groups-readonly',
    itemCopyLocalOpen: 'catalog-item-copy-local-open',
    itemDetailLoading: 'catalog-item-detail-loading',
    itemDirtyContinue: 'catalog-item-dirty-continue',
    itemDirtyDiscard: 'catalog-item-dirty-discard',
    itemEdit: 'catalog-item-edit',
    itemEditName: 'catalog-item-edit-name',
    itemEditShortName: 'catalog-item-edit-short-name',
    itemEditStandardPrice: 'catalog-item-edit-standard-price',
    itemIdentifierAdd: 'catalog-item-identifier-add',
    itemIdentifiersEditor: 'catalog-item-identifiers-editor',
    itemMediaEditor: 'catalog-item-media-editor',
    itemMediaGallery: 'catalog-item-media-gallery',
    itemMediaList: 'catalog-item-media-list',
    itemMediaUpload: 'catalog-item-media-upload',
    itemOptionPreparationLink: 'catalog-item-option-preparation-link',
    itemOrderOptionLibraryAdd: 'catalog-item-order-option-library-add',
    itemOrderOptionLibraryAddModal: 'catalog-item-order-option-library-add-modal',
    itemOrderOptionLibraryManage: 'catalog-item-order-option-library-manage',
    itemPreparationEditor: 'catalog-item-preparation-editor',
    itemPreparationReadonly: 'catalog-item-preparation-readonly',
    itemProblem: 'catalog-item-problem',
    itemProblemRetry: 'catalog-item-problem-retry',
    itemProductionName: 'catalog-item-production-name',
    itemProductionNotes: 'catalog-item-production-notes',
    itemProductionSeconds: 'catalog-item-production-seconds',
    itemProductionTags: 'catalog-item-production-tags',
    itemProductionTagManage: 'catalog-item-production-tag-manage',
    itemReleaseCloseRetry: 'catalog-item-release-close-retry',
    itemSalesUnit: 'catalog-item-sales-unit',
    itemSave: 'catalog-item-save',
    itemSkuAttributeSelector: 'catalog-item-sku-attribute-selector',
    itemSkuAttributeManage: 'catalog-item-sku-attribute-manage',
    itemSkuDimensionTable: 'catalog-item-sku-dimension-table',
    itemSkuMatrixEditor: 'catalog-item-sku-matrix-editor',
    itemSkuMatrixReadonly: 'catalog-item-sku-matrix-readonly',
    itemSourceAutoSync: 'catalog-item-source-auto_sync',
    itemSourceAutoSyncFacts: 'catalog-item-source-auto_sync-facts',
    itemTabs: 'catalog-item-tabs',
    itemTagManage: 'catalog-item-tag-manage',
    itemTagRefs: 'catalog-item-tag-refs',
    itemTemporaryPromotion: 'catalog-item-temporary-promotion',
    itemVoid: 'catalog-item-void',
    itemVoidBlockReasons: 'catalog-item-void-block-reasons',
    localCopyBomBlocked: 'catalog-local-copy-bom-blocked',
    localCopyBomMappingNext: 'catalog-local-copy-bom-mapping-next',
    localCopyCandidates: 'catalog-local-copy-candidates',
    localCopyCandidatesEmpty: 'catalog-local-copy-candidates-empty',
    localCopyCandidatesError: 'catalog-local-copy-candidates-error',
    localCopyCandidatesLoading: 'catalog-local-copy-candidates-loading',
    localCopyCandidatesNext: 'catalog-local-copy-candidates-next',
    localCopyCompatibilityResults: 'catalog-local-copy-compatibility-results',
    localCopyConfirm: 'catalog-local-copy-confirm',
    localCopyDirtyContinue: 'catalog-local-copy-dirty-continue',
    localCopyDirtyDiscard: 'catalog-local-copy-dirty-discard',
    localCopyDrawer: 'catalog-local-copy-drawer',
    localCopyExecute: 'catalog-local-copy-execute',
    localCopyMappingLoading: 'catalog-local-copy-mapping-loading',
    localCopyOpenTarget: 'catalog-local-copy-open-target',
    localCopyPreflight: 'catalog-local-copy-preflight',
    localCopyPreflightLoading: 'catalog-local-copy-preflight-loading',
    localCopyPreflightRetry: 'catalog-local-copy-preflight-retry',
    localCopyProblem: 'catalog-local-copy-problem',
    localCopyReadbackReferenceMappings: 'catalog-local-copy-readback-reference-mappings',
    localCopyResult: 'catalog-local-copy-result',
    localCopyScopeOptionsError: 'catalog-local-copy-scope-options-error',
    localCopySections: 'catalog-local-copy-sections',
    localCopySkippedReadback: 'catalog-local-copy-skipped-readback',
    localCopySourceItemNext: 'catalog-local-copy-source-item-next',
    localCopySourceKeyword: 'catalog-local-copy-source-keyword',
    localCopySourceScope: 'catalog-local-copy-source-scope',
    localCopySourceScopeNext: 'catalog-local-copy-source-scope-next',
    localCopyStale: 'catalog-local-copy-stale',
    localCopySteps: 'catalog-local-copy-steps',
    orderOptionDefinitionDrawer: 'catalog-order-option-definition-drawer',
    orderOptionDefinitionList: 'catalog-order-option-definition-list',
    orderOptionDefinitionLibrary: 'catalog-order-option-definition-library',
    preparationVariationSummary: 'catalog-preparation-variation-summary',
    productionTagsPagination: 'catalog-production-tags-pagination',
    skuAttributeCreateForm: 'catalog-sku-attribute-create-form',
    skuAttributeManager: 'catalog-sku-attribute-manager',
    skuAttributeValueCreateForm: 'catalog-sku-attribute-value-create-form',
    skuAttributeValuesTable: 'catalog-sku-attribute-values-table',
    skuAttributeValuesPagination: 'catalog-sku-attribute-values-pagination',
    skuAttributesPagination: 'catalog-sku-attributes-pagination',
    skuAttributesTable: 'catalog-sku-attributes-table',
    skuIdentifierModal: 'catalog-sku-identifier-modal',
    skuPreparationClear: 'catalog-sku-preparation-clear',
    skuPreparationModal: 'catalog-sku-preparation-modal',
    skuPreparationMode: 'catalog-sku-preparation-mode',
    temporaryPromotionBlocked: 'catalog-temporary-promotion-blocked',
    temporaryPromotionFormalCode: 'catalog-temporary-promotion-formal-code',
    temporaryPromotionMaterialRole: 'catalog-temporary-promotion-material-role',
    temporaryPromotionName: 'catalog-temporary-promotion-name',
    temporaryPromotionProblem: 'catalog-temporary-promotion-problem',
    temporaryPromotionRePreflight: 'catalog-temporary-promotion-re-preflight',
    temporaryPromotionShape: 'catalog-temporary-promotion-shape',
    temporaryPromotionShortName: 'catalog-temporary-promotion-short-name',
    unitDimension: 'catalog-unit-dimension',
    unitEditModal: 'catalog-unit-edit-modal',
    unitPrecision: 'catalog-unit-precision',
    unitReadProblem: 'catalog-unit-read-problem',
  },
} as const;

/** Each section anchor is an interactive control. Keep its stable identity
 * tied to the contract tab key rather than to a translated display label. */
export function catalogItemTabTestId(tabKey: string): string {
  return `catalog-item-tab-${tabKey}`;
}

/**
 * Business-control vocabulary used by focused proof and the managed browser
 * runner.  Components consume these constructors instead of inventing a
 * second selector convention.
 */
export const catalogTestIdControls = {
  workbench: {
    viewTree: 'catalog-workbench-view-tree',
    viewTable: 'catalog-workbench-view-table',
    openConfig: 'catalog-config-open',
    openBrandCopy: 'catalog-brand-copy-open',
    brandSwitch: catalogTestIds.control.brandSwitch,
    openCreate: catalogTestIds.control.createOpen,
    treeSearch: catalogTestIds.control.treeSearch,
    filterKeyword: catalogTestIds.control.resultKeyword,
    filterStatus: catalogTestIds.control.resultStatus,
    filterSource: catalogTestIds.control.resultSource,
    filterReset: catalogTestIds.control.resultReset,
    retry: catalogTestIds.control.workbenchRetry,
    refresh: catalogTestIds.control.tableRefresh,
    categoryNode: (categoryCode: string) => `catalog-category-node-${utf8Hex(categoryCode)}`,
    categoryActions: (categoryCode: string) => `catalog-category-actions-${utf8Hex(categoryCode)}`,
  },
  itemTable: {
    root: catalogTestIds.surface.itemTable,
    selectAll: catalogTestIds.control.tableSelectAll,
    itemSelect: catalogItemSelectionTestId,
    itemOpen: catalogItemRowTestId,
    itemExpand: (itemCode: string) => `catalog-item-expand-${utf8Hex(itemCode)}`,
    skuOpen: catalogSkuRowTestId,
    skuMore: (itemCode: string) => `catalog-sku-more-${utf8Hex(itemCode)}`,
    skuRetry: (itemCode: string) => `catalog-sku-retry-${utf8Hex(itemCode)}`,
  },
  create: {
    root: catalogTestIds.surface.itemCreateModal,
    name: catalogTestIds.control.createName,
    code: catalogTestIds.control.createCode,
    shape: catalogTestIds.control.createShape,
    category: catalogTestIds.control.createCategory,
    submit: catalogTestIds.control.createSubmit,
    cancel: catalogTestIds.control.createCancel,
    problem: 'catalog-create-problem',
  },
  view: {
    root: catalogTestIds.surface.itemViewDrawer,
    close: 'catalog-item-view-close',
    edit: catalogTestIds.control.viewEdit,
    more: 'catalog-item-view-more',
    section: (sectionKey: string) => `catalog-item-view-section-${utf8Hex(sectionKey)}`,
    skuIssue: (skuBusinessIdentity: string) => `catalog-item-sku-readonly-issues-${utf8Hex(skuBusinessIdentity)}`,
    skuIssueText: (skuBusinessIdentity: string) =>
      `catalog-item-sku-readonly-issue-text-${utf8Hex(skuBusinessIdentity)}`,
    skuMedia: (skuBusinessIdentity: string, assetRef: string) =>
      `catalog-item-sku-media-readonly-${utf8Hex(skuBusinessIdentity)}-${utf8Hex(assetRef)}`,
    itemMedia: (assetRef: string) => `catalog-item-media-gallery-${utf8Hex(assetRef)}`,
    retry: 'catalog-item-view-retry',
  },
  edit: {
    root: catalogTestIds.surface.itemEditDrawer,
    close: catalogTestIds.control.editClose,
    cancel: catalogTestIds.control.editCancel,
    save: catalogTestIds.control.editSave,
    errorSummary: 'catalog-item-edit-error-summary',
    discard: catalogTestIds.control.dirtyDiscard,
    anchor: (sectionKey: string) => `catalog-item-edit-anchor-${utf8Hex(sectionKey)}`,
    section: (sectionKey: string) => `catalog-item-edit-section-${utf8Hex(sectionKey)}`,
    field: catalogFieldTestId,
    row: (sectionKey: string, businessCodeOrEditorId: string) =>
      `catalog-item-edit-row-${utf8Hex(sectionKey)}-${utf8Hex(businessCodeOrEditorId)}`,
    rowAction: (sectionKey: string, businessCodeOrEditorId: string, action: string) =>
      `catalog-item-edit-row-action-${utf8Hex(sectionKey)}-${utf8Hex(businessCodeOrEditorId)}-${utf8Hex(action)}`,
    media: (businessIdentity: string, action: string) =>
      `catalog-item-media-${utf8Hex(action)}-${utf8Hex(businessIdentity)}`,
    skuMedia: (skuEditorId: string, businessIdentity: string, action: string) =>
      `catalog-item-sku-media-${utf8Hex(action)}-${utf8Hex(skuEditorId)}-${utf8Hex(businessIdentity)}`,
    dynamic: (surface: string, action: string, primaryIdentity: string, secondaryIdentity?: string) =>
      `catalog-item-${surface}-${action}-${primaryIdentity}${secondaryIdentity ? `-${secondaryIdentity}` : ''}`,
    related: (controlId: string, action: string, businessIdentity?: string) =>
      `${controlId}-${action}${businessIdentity ? `-${businessIdentity}` : ''}`,
  },
  childTask: {
    root: 'catalog-child-task',
    search: (sectionKey: string) => `catalog-child-task-search-${utf8Hex(sectionKey)}`,
    result: (businessCode: string) => `catalog-child-task-result-${utf8Hex(businessCode)}`,
    more: (sectionKey: string) => `catalog-child-task-more-${utf8Hex(sectionKey)}`,
    apply: 'catalog-child-task-apply',
    cancel: 'catalog-child-task-cancel',
    error: 'catalog-child-task-error',
  },
  config: {
    root: catalogTestIds.surface.configDrawer,
    close: catalogTestIds.control.configClose,
    library: (libraryKey: string) => `catalog-config-library-${utf8Hex(libraryKey)}`,
    search: catalogTestIds.control.configSearch,
    create: catalogTestIds.control.configCreate,
    row: catalogDictionaryRowTestId,
    action: catalogDictionaryActionTestId,
    detail: catalogTestIds.surface.configDefinitionEditor,
    back: 'catalog-config-back',
    save: catalogTestIds.control.configSave,
    delete: 'catalog-config-delete',
    valueRow: (libraryKey: string, parentCode: string, valueCode: string) =>
      `catalog-config-value-row-${utf8Hex(libraryKey)}-${utf8Hex(parentCode)}-${utf8Hex(valueCode)}`,
  },
  categoryTask: {
    root: catalogTestIds.surface.categoryTaskModal,
    name: 'catalog-category-name',
    code: 'catalog-category-code',
    parent: 'catalog-category-parent',
    impact: 'catalog-category-impact',
    submit: 'catalog-category-submit',
    cancel: 'catalog-category-cancel',
    problem: 'catalog-category-problem',
  },
  batch: {
    root: catalogTestIds.surface.batchTaskModal,
    action: 'catalog-batch-action',
    category: 'catalog-inventory-batch-category',
    tags: 'catalog-inventory-batch-tag',
    summary: 'catalog-batch-outcome-summary',
    progress: 'catalog-batch-submitting',
    problem: 'catalog-batch-problem',
    submit: 'catalog-batch-submit',
    cancel: 'catalog-batch-cancel',
    resultRow: (itemCode: string) => `catalog-batch-result-${utf8Hex(itemCode)}`,
    refreshError: 'catalog-batch-refresh-error',
  },
  copy: {
    root: (copyKind: 'BRAND' | 'LOCAL') =>
      copyKind === 'BRAND' ? catalogTestIds.surface.brandCopyDrawer : catalogTestIds.surface.localCopyDrawer,
    sourceSearch: (copyKind: 'BRAND' | 'LOCAL') =>
      copyKind === 'BRAND' ? 'catalog-brand-copy-source-keyword' : 'catalog-local-copy-source-keyword',
    sourceRow: (businessCode: string) => `catalog-copy-source-${utf8Hex(businessCode)}`,
    scopeDescription: (scopeCode: string) => `catalog-copy-scope-description-${utf8Hex(scopeCode)}`,
    scopeReason: (scopeCode: string) => `catalog-copy-scope-reason-${utf8Hex(scopeCode)}`,
    confirmation: (copyKind: 'BRAND' | 'LOCAL', compatibilityId: string) =>
      `catalog-copy-confirmation-${copyKind.toLowerCase()}-${utf8Hex(compatibilityId)}`,
    target: 'catalog-copy-target',
    section: (sectionKey: string) => `catalog-copy-section-${utf8Hex(sectionKey)}`,
    preflight: 'catalog-copy-preflight',
    back: 'catalog-copy-back',
    execute: 'catalog-copy-execute',
    resultRow: (businessCode: string) => `catalog-copy-result-row-${utf8Hex(businessCode)}`,
    close: 'catalog-copy-result-close',
    problem: 'catalog-copy-problem',
  },
  governance: {
    root: catalogTestIds.surface.lifecycleConfirm,
    action: catalogTestIds.control.editClose,
    impact: 'catalog-item-void-block-reasons',
    gap: (fieldKey: string) => `catalog-governance-gap-${utf8Hex(fieldKey)}`,
    submit: 'catalog-governance-submit',
    cancel: 'catalog-governance-cancel',
    result: 'catalog-governance-result',
    problem: 'catalog-item-problem',
  },
  inventory: {
    owner: (ownerIdentity: string) => `catalog-inventory-owner-${utf8Hex(ownerIdentity)}`,
    bomLine: (ownerIdentity: string, lineIdentity: string, control: string) =>
      `catalog-inventory-bom-${utf8Hex(ownerIdentity)}-${utf8Hex(lineIdentity)}-${utf8Hex(control)}`,
  },
  common: {
    dirtyConfirm: 'catalog-dirty-confirm',
    dirtyStay: catalogTestIds.control.dirtyContinue,
    dirtyDiscard: catalogTestIds.control.dirtyDiscard,
    confirm: 'catalog-confirm',
    confirmYes: 'catalog-confirm-yes',
    confirmNo: 'catalog-confirm-no',
    inlineRetry: (surfaceKey: string) => `catalog-inline-retry-${utf8Hex(surfaceKey)}`,
  },
} as const;

export const catalogSurfaceTestIds = catalogTestIds.surface;

function utf8Hex(value: string): string {
  const bytes = new TextEncoder().encode(value);
  return Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('');
}

export function catalogBusinessTestId(prefix: string, businessCode: string): string {
  return `catalog-${prefix}-${utf8Hex(businessCode)}`;
}

export function catalogItemRowTestId(itemCode: string): string {
  return `catalog-item-row-${utf8Hex(itemCode)}`;
}

/** Parent-row selection is a business action, so its locator uses the item code too. */
export function catalogItemSelectionTestId(itemCode: string): string {
  return `catalog-item-select-${utf8Hex(itemCode)}`;
}

export function catalogSkuRowTestId(itemCode: string, skuCode: string): string {
  return `catalog-sku-row-${utf8Hex(`${itemCode}:${skuCode}`)}`;
}

export function catalogSkuStateTestId(itemCode: string, state: string): string {
  return `catalog-sku-state-${state.toLowerCase()}-${utf8Hex(itemCode)}`;
}

export function catalogFieldTestId(sectionKey: string, fieldKey: string): string {
  return `catalog-field-${utf8Hex(sectionKey)}-${utf8Hex(fieldKey)}`;
}

export function catalogSectionTestId(sectionKey: string): string {
  return `catalog-section-${utf8Hex(sectionKey)}`;
}

export function catalogDictionaryRowTestId(libraryKey: string, businessCode: string): string {
  return `catalog-dictionary-row-${utf8Hex(libraryKey)}-${utf8Hex(businessCode)}`;
}

export function catalogDictionaryActionTestId(libraryKey: string, businessCode: string, action: string): string {
  return `catalog-dictionary-action-${utf8Hex(libraryKey)}-${utf8Hex(businessCode)}-${utf8Hex(action)}`;
}
