import {theme, type ThemeConfig} from 'antd';

export const operationsAdminThemeProfile = {
  id: 'operations-admin-default',
  consumerFace: 'operations-admin',
  colorScheme: 'light',
  proLayoutNavTheme: 'light',
  theme: {
    algorithm: [theme.defaultAlgorithm, theme.compactAlgorithm],
    cssVar: {key: 'operations-admin', prefix: 'operations-admin'},
    components: {
      Layout: {
        headerBg: 'var(--operations-admin-color-bg-container)',
        bodyBg: 'var(--operations-admin-color-bg-layout)',
        footerBg: 'var(--operations-admin-color-bg-layout)',
        siderBg: 'var(--operations-admin-color-bg-container)',
        lightSiderBg: 'var(--operations-admin-color-bg-container)',
        lightTriggerBg: 'var(--operations-admin-color-bg-container)',
        headerColor: 'var(--operations-admin-color-text)',
        lightTriggerColor: 'var(--operations-admin-color-text)',
      },
    },
    token: {
      colorPrimary: '#1E40AF',
      colorSuccess: '#0EA5E9',
      colorWarning: '#F59E0B',
      colorError: '#EF4444',
      colorInfo: '#3B82F6',
      colorTextBase: '#334155',
      colorBgBase: '#F1F5F9',
      colorPrimaryBg: '#EFF6FF',
      colorPrimaryBgHover: '#DBEAFE',
      colorPrimaryBorder: '#93C5FD',
      colorPrimaryBorderHover: '#60A5FA',
      colorPrimaryHover: '#3B82F6',
      colorPrimaryActive: '#1E3A8A',
      colorPrimaryText: '#1E40AF',
      colorPrimaryTextHover: '#3B82F6',
      colorPrimaryTextActive: '#1E3A8A',
      colorSuccessBg: '#F0F9FF',
      colorSuccessBgHover: '#E0F2FE',
      colorSuccessBorder: '#7DD3FC',
      colorSuccessBorderHover: '#38BDF8',
      colorSuccessHover: '#38BDF8',
      colorSuccessActive: '#0284C7',
      colorSuccessText: '#0EA5E9',
      colorSuccessTextHover: '#38BDF8',
      colorSuccessTextActive: '#0284C7',
      colorWarningBg: '#FFFBEB',
      colorWarningBgHover: '#FEF3C7',
      colorWarningBorder: '#FDE68A',
      colorWarningBorderHover: '#FCD34D',
      colorWarningHover: '#FBBF24',
      colorWarningActive: '#D97706',
      colorWarningText: '#F59E0B',
      colorWarningTextHover: '#FBBF24',
      colorWarningTextActive: '#D97706',
      colorErrorBg: '#FEF2F2',
      colorErrorBgHover: '#FEE2E2',
      colorErrorBorder: '#FCA5A5',
      colorErrorBorderHover: '#F87171',
      colorErrorHover: '#F87171',
      colorErrorActive: '#DC2626',
      colorErrorText: '#EF4444',
      colorErrorTextHover: '#F87171',
      colorErrorTextActive: '#DC2626',
      colorInfoBg: '#EFF6FF',
      colorInfoBgHover: '#DBEAFE',
      colorInfoBorder: '#93C5FD',
      colorInfoBorderHover: '#60A5FA',
      colorInfoHover: '#60A5FA',
      colorInfoActive: '#2563EB',
      colorInfoText: '#3B82F6',
      colorInfoTextHover: '#60A5FA',
      colorInfoTextActive: '#2563EB',
      colorText: 'rgba(51, 65, 85, 0.90)',
      colorTextSecondary: 'rgba(51, 65, 85, 0.70)',
      colorTextTertiary: 'rgba(51, 65, 85, 0.50)',
      colorTextQuaternary: 'rgba(51, 65, 85, 0.25)',
      colorTextDisabled: 'rgba(51, 65, 85, 0.25)',
      colorBgContainer: '#FFFFFF',
      colorBgElevated: '#FFFFFF',
      colorBgLayout: '#F1F5F9',
      colorBgSpotlight: 'rgba(51, 65, 85, 0.85)',
      colorBgMask: 'rgba(51, 65, 85, 0.40)',
      colorBorder: '#E2E8F0',
      colorBorderSecondary: '#F1F5F9',
      borderRadius: 6,
      borderRadiusXS: 2,
      borderRadiusSM: 4,
      borderRadiusLG: 8,
      padding: 16,
      paddingSM: 12,
      paddingLG: 24,
      margin: 16,
      marginSM: 12,
      marginLG: 24,
      boxShadow: '0 1px 3px 0 rgba(148, 163, 184, 0.1), 0 1px 2px -1px rgba(148, 163, 184, 0.1)',
      boxShadowSecondary: '0 4px 6px -1px rgba(148, 163, 184, 0.1), 0 2px 4px -2px rgba(148, 163, 184, 0.1)',
    },
  } satisfies ThemeConfig,
} as const;

export const operationsAdminTheme = operationsAdminThemeProfile.theme;
export const operationsAdminChromeProps = {
  'data-chrome-profile': operationsAdminThemeProfile.id,
  'data-consumer-face': operationsAdminThemeProfile.consumerFace,
} as const;
