import {readFileSync} from 'node:fs'
import {describe, expect, it} from 'vitest'
import {adminGeometry, baseTokens} from '@catering-v2s/ui-base-primitives'

const read = (relativePath: string): string => readFileSync(new URL(`../${relativePath}`, import.meta.url), 'utf8')

describe('admin visual contract', () => {
  it('declares the high-fidelity geometry as focused data, not a frame macro', () => {
    expect(adminGeometry.rootLaptop).toMatchObject({paddingHorizontal: 0, paddingVertical: 0})
    expect(adminGeometry.rootMobile).toMatchObject({paddingHorizontal: 0, paddingVertical: 0})
    expect(adminGeometry.shellLaptop).toMatchObject({flex: 1, width: '100%', maxWidth: '100%', minHeight: 0, minWidth: 0, alignSelf: 'stretch'})
    expect(adminGeometry.shellMobile).toMatchObject({flex: 1, width: '100%', maxWidth: '100%', minHeight: 0, minWidth: 0, alignSelf: 'stretch'})
    expect(adminGeometry.headerLaptop).toMatchObject({height: 72, paddingHorizontal: 24, borderBottomWidth: 1})
    expect(adminGeometry.headerMobile).toMatchObject({height: 60, paddingHorizontal: 16, borderBottomWidth: 1})
    expect(adminGeometry.navigation).toMatchObject({width: 248, minWidth: 248, padding: 12, borderRightWidth: 1})
    expect(adminGeometry.navigationList).toMatchObject({gap: 6})
    expect(adminGeometry.contentLaptop).toMatchObject({padding: 24})
    expect(adminGeometry.contentMobile).toMatchObject({padding: 16, gap: 12})
    expect(adminGeometry.card).toMatchObject({borderRadius: 16, borderWidth: 1, padding: 20, minHeight: 96})
    expect(adminGeometry.disclosure).toMatchObject({minHeight: 52, paddingHorizontal: 16})
    expect(adminGeometry.ratioBar).toMatchObject({height: 12, borderRadius: 6})
    expect(adminGeometry.surfaceRectLaptop).toMatchObject({minHeight: 176})
    expect(adminGeometry.surfaceRectMobile).toMatchObject({minHeight: 120})
  })

  it('uses admin semantic classes at the shared-rendering boundaries', () => {
    expect(baseTokens.adminShell).toContain('bg-admin-shell-surface')
    expect(baseTokens.adminShell).toContain('border-admin-shell-border')
    expect(baseTokens.adminShell).not.toContain('rounded-[20px]')
    expect(baseTokens.adminShell).not.toContain('shadow-2xl')
    expect(baseTokens.adminNavItemSelected).toContain('bg-admin-action')
    expect(baseTokens.adminNavFocusBar).toContain('bg-admin-focus')
    expect(baseTokens.adminContent).toContain('bg-admin-content-surface')
    expect(baseTokens.adminCard).toContain('bg-surface-elevated')
    expect(baseTokens.adminRatioBar).toContain('bg-admin-inset')
    expect(baseTokens.adminDisclosureTrigger).toContain('flex-row')
    expect(read('src/components/AdminShellFrame.tsx')).toContain('appearance="admin-shell"')
    expect(read('src/components/AdminSectionNavigationLaptop.tsx')).toContain('variant="admin-nav"')
    expect(read('src/components/AdminSectionNavigationLaptop.tsx')).toContain('icon=')
    expect(read('../primitives/src/components/PrimitiveAdmin.tsx')).toContain('aspectRatio: surface.aspectRatio')
  })

  it('freezes the high-fidelity shape contract for every shared admin control family', () => {
    expect(baseTokens.adminHeaderTitle).toContain('text-2xl leading-8 font-bold')
    expect(baseTokens.adminHeaderClose).toContain('min-h-7 min-w-7')
    expect(baseTokens.adminHeaderClose).toContain('rounded-[9px]')
    expect(baseTokens.adminStatus).toContain('min-h-7 min-w-28')
    expect(baseTokens.adminStatus).toContain('rounded-[14px]')
    expect(baseTokens.adminNavItem).toContain('min-h-11 flex-row')
    expect(baseTokens.adminNavItemSelected).toContain('bg-admin-action')
    expect(baseTokens.adminButton).toContain('min-h-11')
    expect(baseTokens.adminButton).toContain('rounded-xl')
    expect(baseTokens.adminButtonSecondary).toContain('min-h-11')
    expect(baseTokens.adminButtonSecondary).toContain('rounded-xl')
    expect(baseTokens.adminMobileSelector).toContain('min-h-12')
    expect(baseTokens.adminMobileSelector).toContain('rounded-xl border-2')
    expect(baseTokens.adminDisclosureTrigger).toContain('min-h-[52px] flex-row')
    expect(baseTokens.adminRatioBar).toContain('h-3')
    expect(baseTokens.adminSurfaceMapRect).toContain('min-h-44')
    expect(baseTokens.adminSurfaceMapRectCurrent).toContain('border-2 border-admin-focus')
    expect(baseTokens.adminSurfaceMapLogicWidth).toContain('top-4')
    expect(baseTokens.adminSurfaceMapLogicHeight).toContain('rotate-90')
    expect(baseTokens.adminSurfaceMapPhysicalWidth).toContain('top-0')
    expect(baseTokens.adminSurfaceMapPhysicalHeight).toContain('rotate-90')
    expect(baseTokens.adminSurfaceMapPhysicalHeight).toContain('bottom-8')
    expect(baseTokens.adminSurfaceMapWrap).toContain('pb-12')
  })

  it('binds aspect ratio to the inner surface rectangle, never the outer surface card', () => {
    const source = read('../primitives/src/components/PrimitiveAdmin.tsx')
    const cardStart = source.indexOf('testID={`${address}:surface:${surface.key}:card`}')
    const innerStart = source.indexOf('testID={`${address}:surface:${surface.key}`}', cardStart)
    expect(cardStart).toBeGreaterThanOrEqual(0)
    expect(innerStart).toBeGreaterThan(cardStart)
    expect(source.slice(cardStart, innerStart)).not.toContain('aspectRatio')
    const ratioStart = source.indexOf('aspectRatio: surface.aspectRatio', innerStart)
    expect(ratioStart).toBeGreaterThan(innerStart)
    expect(source.slice(innerStart, ratioStart)).not.toContain('aspectRatio')
  })

  it('keeps runtime fact controls and action gradients on semantic shared boundaries', () => {
    const runtime = read('src/components/sections/RuntimeSection.tsx')
    const button = read('../primitives/src/components/PrimitiveButton.tsx')
    expect(runtime).toContain('admin.console.runtime:environment')
    expect(runtime).toContain('admin.console.runtime:debug')
    expect(runtime).toContain('admin.console.runtime:device')
    expect(runtime).toContain('admin.console.runtime:display-status')
    expect(button).toContain("namespace={appearance === 'admin-primary' ? 'admin' : 'login'}")
    expect(button).toContain('--color-${namespace}-action-start')
    expect(button).toContain('--color-${namespace}-action-end')
  })

  it('keeps the four known false-green regressions mechanically visible', () => {
    const adminShell = read('src/components/AdminShellFrame.tsx')
    const navigation = read('src/components/AdminSectionNavigationLaptop.tsx')
    const primitiveAdmin = read('../primitives/src/components/PrimitiveAdmin.tsx')
    const selection = read('src/foundations/adminSectionSelection.ts')
    expect(adminShell).toContain('adminGeometry.shellLaptop')
    expect(navigation).toContain('adminGeometry.navigationList')
    expect(primitiveAdmin).toContain(':card')
    expect(primitiveAdmin).not.toContain('style={{aspectRatio: surface.aspectRatio}}')
    expect(selection).not.toContain('pageKey: undefined')
  })
})
