package com.catering.v2s.workspace.iam.application.persistence;

/** SQL text fragments owned by WorkspaceAuthenticationService; B3 relocates text only and does not change execution. */
public final class WorkspaceAuthenticationServiceSql {
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_STATUS_PASSWORD_HASH = "SELECT a.id, a.workspace_uuid, a.group_workspace_key, a.status, c.password_hash, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_LOCKED_UNTIL_EPOCH_MILLIS = "c.locked_until_epoch_millis, c.password_change_required, a.display_name, gw.name, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_ACCOUNT_OPERATIONS_TITLE_LOGO_ASSET_REF = "gw.operations_title, gw.logo_asset_ref FROM workspace_iam.workspace_account a JOIN ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_CREDENTIAL_ACCOUNT_ID = "workspace_iam.workspace_credential c ON c.account_id=a.id JOIN ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_GROUP_WORKSPACE_WORKSPACE_UUID = "platform_workspace.group_workspace gw ON gw.workspace_uuid=a.workspace_uuid AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_GROUP_WORKSPACE_KEY = "gw.group_workspace_key=a.group_workspace_key WHERE a.group_workspace_key=? AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_LOGIN_NAME_NORMALIZED = "a.login_name_normalized=?";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_UPDATE_WORKSPACE_CREDENTIAL_FAILED_ATTEMPTS = "UPDATE workspace_iam.workspace_credential SET failed_attempts=failed_attempts+1, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_LOCKED_UNTIL_EPOCH_MILLIS_FAILED_ATTEMPTS = "locked_until_epoch_millis=CASE WHEN failed_attempts+1>=10 THEN ? ELSE ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_LOCKED_UNTIL_EPOCH_MILLIS_VERSION_ACCOUNT_ID = "locked_until_epoch_millis END, version=version+1 WHERE account_id=?";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_UPDATE_OTP_GRANT_STATUS_SUPERSEDED_SUBJECT_REF = "UPDATE workspace_iam.otp_grant SET status='SUPERSEDED' WHERE subject_ref=? AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_PURPOSE_WORKSPACE_LOGIN_STATUS_ACTIVE = "purpose='WORKSPACE_LOGIN' AND status='ACTIVE'";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_INSERT_INTO_OTP_GRANT = "INSERT INTO workspace_iam.otp_grant (id, workspace_uuid, group_workspace_key, purpose, token_hash, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_SUBJECT_REF = "subject_ref, status, expires_at_epoch_millis) VALUES (?, ?, ?, 'WORKSPACE_LOGIN', ?, ?, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_ACTIVE = "'ACTIVE', ?)";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_UPDATE_OTP_GRANT_STATUS_USED_USED_AT_EPOCH_MILLIS_SUBJECT_REF = "UPDATE workspace_iam.otp_grant SET status='USED', used_at_epoch_millis=? WHERE subject_ref=? AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_PURPOSE_WORKSPACE_LOGIN_TOKEN_HASH_STATUS = "purpose='WORKSPACE_LOGIN' AND token_hash=? AND status='ACTIVE' AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_EXPIRES_AT_EPOCH_MILLIS = "expires_at_epoch_millis>?";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_UPDATE_OTP_GRANT_ATTEMPT_COUNT_SUBJECT_REF = "UPDATE workspace_iam.otp_grant SET attempt_count=attempt_count+1 WHERE subject_ref=? AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_PURPOSE_WORKSPACE_LOGIN_STATUS_ACTIVE_ALTERNATE_A = "purpose='WORKSPACE_LOGIN' AND status='ACTIVE'";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_UPDATE_WORKSPACE_SESSION_CURRENT_ASSIGNMENT_ID_SELECTED_REGION_ID = "UPDATE workspace_iam.workspace_session SET current_assignment_id=?, selected_region_id=?, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_SELECTED_PROJECT_ID = "selected_project_id=?, selected_store_id=?, selected_head_company_id=?, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_CONTEXT_VERSION_AUTHORIZATION_REVISION = "context_version=context_version+1, authorization_revision=authorization_revision+1 ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_WHERE_CONTEXT_VERSION = "WHERE id=? AND context_version=?";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_UPDATE_WORKSPACE_SESSION_SELECTED_REGION_ID_SELECTED_PROJECT_ID = "UPDATE workspace_iam.workspace_session SET selected_region_id=?, selected_project_id=?, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_SELECTED_STORE_ID_SELECTED_HEAD_COMPANY_ID_CONTEXT_VERSION = "selected_store_id=?, selected_head_company_id=?, context_version=context_version+1, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_AUTHORIZATION_REVISION_CONTEXT_VERSION = "authorization_revision=authorization_revision+1 WHERE id=? AND context_version=?";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_WORKSPACE_UUID = "SELECT s.id, s.workspace_uuid, s.group_workspace_key, s.account_id, s.current_assignment_id, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_SELECTED_REGION_ID = "s.selected_region_id, s.selected_project_id, s.selected_store_id, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_SELECTED_HEAD_COMPANY_ID = "s.selected_head_company_id, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_CONTEXT_VERSION = "s.context_version, s.authorization_revision, a.display_name, ra.role_id, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_SERVICE_NODE_TYPE = "ra.service_node_type, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_SERVICE_NODE_ID_PAGE_ACCESS_KEYS_CAPABILITY_KEYS = "ra.service_node_id, r.page_access_keys, r.capability_keys ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_FROM_CLAUSE_WORKSPACE_SESSION_FROM_WORKSPACE_IAM_WORKSPACE = "FROM workspace_iam.workspace_session s ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_JOIN_WORKSPACE_ACCOUNT_ACCOUNT_ID = "JOIN workspace_iam.workspace_account a ON a.id=s.account_id ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_JOIN_ROLE_ASSIGNMENT_CURRENT_ASSIGNMENT_ID = "JOIN workspace_iam.role_assignment ra ON ra.id=s.current_assignment_id ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONDITION_ACCOUNT_ID_WORKSPACE_UUID = "AND ra.account_id=s.account_id AND ra.workspace_uuid=s.workspace_uuid ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONDITION_GROUP_WORKSPACE_KEY_STATUS_ACTIVE = "AND ra.group_workspace_key=s.group_workspace_key AND ra.status='ACTIVE' ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_JOIN_WORKSPACE_ROLE_ROLE_ID = "JOIN workspace_iam.workspace_role r ON r.id=ra.role_id AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_UUID = "r.workspace_uuid=s.workspace_uuid ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONDITION_GROUP_WORKSPACE_KEY_STATUS_ENABLED = "AND r.group_workspace_key=s.group_workspace_key AND r.status='ENABLED' ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_WHERE_TOKEN_HASH_STATUS_ACTIVE_EXPIRES_AT_EPOCH_MILLIS = "WHERE s.token_hash=? AND s.status='ACTIVE' AND s.expires_at_epoch_millis>?";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_ROLE_ASSIGNMENT_ROLE_ID_STATUS_ACTIVE = "SELECT role_id FROM workspace_iam.role_assignment WHERE id=? AND status='ACTIVE'";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_UPDATE_WORKSPACE_SESSION_STATUS_REVOKED_REVOKED_AT_EPOCH_MILLIS = "UPDATE workspace_iam.workspace_session SET status='REVOKED', revoked_at_epoch_millis=?, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_SELECTED_REGION_ID_SELECTED_PROJECT_ID_SELECTED_STORE_ID = "selected_region_id=NULL, selected_project_id=NULL, selected_store_id=NULL, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_SELECTED_HEAD_COMPANY_ID_TOKEN_HASH_STATUS_ACTIVE = "selected_head_company_id=NULL WHERE token_hash=? AND status='ACTIVE'";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_ACCOUNT_ID_CONTEXT_VERSION_PASSWORD_HASH_VERSION = "SELECT s.id, s.account_id, s.context_version, c.password_hash, c.version FROM ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_CREDENTIAL_WORKSPACE_SESSION = "workspace_iam.workspace_session s JOIN workspace_iam.workspace_credential c ON ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_ACCOUNT_ID_TOKEN_HASH_STATUS_ACTIVE = "c.account_id=s.account_id WHERE s.token_hash=? AND s.status='ACTIVE' AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_EXPIRES_AT_EPOCH_MILLIS_ALTERNATE_A = "s.expires_at_epoch_millis>?";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_UPDATE_WORKSPACE_CREDENTIAL_PASSWORD_HASH_CHANGED_AT_EPOCH_MILLIS = "UPDATE workspace_iam.workspace_credential c SET password_hash=?, changed_at_epoch_millis=?, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_FAILED_ATTEMPTS = "failed_attempts=0, locked_until_epoch_millis=NULL, password_change_required=FALSE, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_VERSION_ACCOUNT_ID = "version=version+1 WHERE c.account_id=? AND c.version=? AND EXISTS (SELECT 1 FROM ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_SESSION_STATUS_ACTIVE = "workspace_iam.workspace_session s WHERE s.id=? AND s.status='ACTIVE' AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_EXPIRES_AT_EPOCH_MILLIS_ALTERNATE_B = "s.expires_at_epoch_millis>?)";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_UPDATE_WORKSPACE_SESSION_STATUS_REVOKED_REVOKED_AT_EPOCH_MILLIS_ALTERNATE_A = "UPDATE workspace_iam.workspace_session SET status='REVOKED', revoked_at_epoch_millis=?, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_SELECTED_REGION_ID_SELECTED_PROJECT_ID_SELECTED_STORE_ID_ALTERNATE_A = "selected_region_id=NULL, selected_project_id=NULL, selected_store_id=NULL, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_SELECTED_HEAD_COMPANY_ID_ACCOUNT_ID_STATUS_ACTIVE = "selected_head_company_id=NULL WHERE account_id=? AND status='ACTIVE'";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_ROLE_ASSIGNMENT_ROLE_ID_SERVICE_NODE_TYPE_SERVICE_NODE_ID = "SELECT a.id, a.role_id, a.service_node_type, a.service_node_id FROM workspace_iam.role_assignment a ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_JOIN_WORKSPACE_ROLE_ROLE_ID_ACCOUNT_ID = "JOIN workspace_iam.workspace_role r ON r.id=a.role_id WHERE a.account_id=? AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_STATUS_ACTIVE = "a.workspace_uuid=? AND a.group_workspace_key=? AND a.status='ACTIVE' AND r.status='ENABLED'";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_INSERT_INTO_WORKSPACE_SESSION = "INSERT INTO workspace_iam.workspace_session (id, workspace_uuid, group_workspace_key, account_id, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_TOKEN_HASH = "token_hash, current_assignment_id, selected_region_id, selected_project_id, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_SELECTED_STORE_ID = "selected_store_id, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_SELECTED_HEAD_COMPANY_ID = "selected_head_company_id, context_version, authorization_revision, status, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_EXPIRES_AT_EPOCH_MILLIS_ACTIVE = "expires_at_epoch_millis) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 1, 'ACTIVE', ?)";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_INSERT_INTO_WORKSPACE_AUTHENTICATION_HISTORY = "INSERT INTO workspace_iam.workspace_authentication_history (id, workspace_uuid, group_workspace_key, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_ACCOUNT_ID_AUTHENTICATED_AT_EPOCH_MILLIS = "account_id, authenticated_at_epoch_millis) VALUES (?, ?, ?, ?, ?)";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_WORKSPACE_UUID_ALTERNATE_A = "SELECT a.id, a.workspace_uuid, a.group_workspace_key, a.status, c.password_change_required, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_DISPLAY_NAME_NAME_OPERATIONS_TITLE_LOGO_ASSET_REF = "a.display_name, gw.name, gw.operations_title, gw.logo_asset_ref FROM ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_CREDENTIAL_WORKSPACE_ACCOUNT = "workspace_iam.workspace_account a JOIN workspace_iam.workspace_credential c ON ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_GROUP_WORKSPACE_ACCOUNT_ID = "c.account_id=a.id JOIN platform_workspace.group_workspace gw ON ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_UUID_GROUP_WORKSPACE_KEY = "gw.workspace_uuid=a.workspace_uuid AND gw.group_workspace_key=a.group_workspace_key WHERE ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_GROUP_WORKSPACE_KEY_MOBILE_NORMALIZED = "a.group_workspace_key=? AND a.mobile_normalized=?";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_WORKSPACE_UUID_ALTERNATE_B = "SELECT s.id, s.workspace_uuid, s.group_workspace_key, s.account_id, s.current_assignment_id, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_SELECTED_REGION_ID_ALTERNATE_A = "s.selected_region_id, s.selected_project_id, s.selected_store_id, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_SELECTED_HEAD_COMPANY_ID_ALTERNATE_A = "s.selected_head_company_id, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_CONTEXT_VERSION_ALTERNATE_A = "s.context_version, s.authorization_revision, a.display_name, gw.name, gw.operations_title, ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_SESSION = "gw.logo_asset_ref, c.password_change_required FROM workspace_iam.workspace_session s JOIN ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_ACCOUNT_ACCOUNT_ID = "workspace_iam.workspace_account a ON a.id=s.account_id JOIN ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_CREDENTIAL = "workspace_iam.workspace_credential ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_GROUP_WORKSPACE_ACCOUNT_ID_ALTERNATE_A = "c ON c.account_id=a.id JOIN platform_workspace.group_workspace gw ON ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_ALTERNATE_A = "gw.workspace_uuid=s.workspace_uuid AND gw.group_workspace_key=s.group_workspace_key WHERE ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_TOKEN_HASH_STATUS_ACTIVE_EXPIRES_AT_EPOCH_MILLIS = "s.token_hash=? AND s.status='ACTIVE' AND s.expires_at_epoch_millis>?";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_ROLE_ASSIGNMENT_ROLE_ID_SERVICE_NODE_TYPE_SERVICE_NODE_ID_ALTERNATE_A = "SELECT a.id, a.role_id, a.service_node_type, a.service_node_id FROM workspace_iam.role_assignment a ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_JOIN_WORKSPACE_ROLE_ROLE_ID_ACCOUNT_ID_ALTERNATE_A = "JOIN workspace_iam.workspace_role r ON r.id=a.role_id WHERE a.id=? AND a.account_id=? AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_STATUS_ACTIVE_ALTERNATE_A = "a.workspace_uuid=? AND a.group_workspace_key=? AND a.status='ACTIVE' AND r.status='ENABLED'";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_SELECT_ROLE_ASSIGNMENT_ROLE_ID_SERVICE_NODE_TYPE_SERVICE_NODE_ID_ALTERNATE_B = "SELECT a.id, a.role_id, a.service_node_type, a.service_node_id FROM workspace_iam.role_assignment a ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_JOIN_WORKSPACE_ROLE_ROLE_ID_ACCOUNT_ID_ALTERNATE_B = "JOIN workspace_iam.workspace_role r ON r.id=a.role_id WHERE a.account_id=? AND ";
    public static final String WORKSPACE_AUTHENTICATION_SERVICE_CONTINUATION_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_STATUS_ACTIVE_ALTERNATE_B = "a.workspace_uuid=? AND a.group_workspace_key=? AND a.status='ACTIVE' AND r.status='ENABLED'";
}
