// Generated by scripts/generate/messaging-protocol from contracts/protocol/http-headers.yaml. Do not edit.
export const platformHttpProtocol = {
  CORRELATION_ID: 'X-Correlation-Id',
  REQUEST_ID: 'X-Request-Id',
  TRACE_ID: 'X-Trace-Id',
  TRACEPARENT: 'traceparent',
  DIAGNOSTIC_PARENT_EVENT_ID: 'X-Platform-Diagnostic-Parent-Event-Id',
  OWNER_COMMAND_AUTHORIZATION_PROOF: 'X-Owner-Command-Authorization-Proof',
  OPERATIONS_DATA_NODE_TYPE: 'X-Operations-Data-Node-Type',
  OPERATIONS_DATA_NODE_REF: 'X-Operations-Data-Node-Ref',
} as const;
export type PlatformHttpProtocolKey = keyof typeof platformHttpProtocol;
