package com.catering.v2s.salesmenu.application.persistence;

/** SQL text fragments owned by SalesMenuManualSaleService; B3 relocates text only and does not change execution. */
public final class SalesMenuManualSaleServiceSql {
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_INSERT_INTO_SALES_MANUAL_STATUS_CURRENT = "INSERT INTO sales_menu.sales_manual_status_current(sales_item_ref,channel_ref,target_kind,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_TARGET_REF_STATE_REASON_CHANGED_AT_EPOCH_MILLIS = "target_ref,state,reason,changed_at_epoch_millis,actor_type,actor_id,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_ACTOR_DISPLAY_SNAPSHOT_VERSION = "actor_display_snapshot,version) VALUES(?,?,?,?,?,?,?,?,?,?,1) ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_JOIN_CONDITION_SALES_ITEM_REF_CHANNEL_REF_TARGET_KIND_TARGET_REF = "ON CONFLICT (sales_item_ref,channel_ref,target_kind,target_ref) ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_SET_DO_UPDATE_SET = "DO UPDATE SET ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_STATE_REASON = "state=EXCLUDED.state,reason=EXCLUDED.reason,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_CHANGED_AT_EPOCH_MILLIS = "changed_at_epoch_millis=EXCLUDED.changed_at_epoch_millis,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_ACTOR_TYPE_ACTOR_ID = "actor_type=EXCLUDED.actor_type,actor_id=EXCLUDED.actor_id,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_ACTOR_DISPLAY_SNAPSHOT = "actor_display_snapshot=EXCLUDED.actor_display_snapshot,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_VERSION_SALES_MANUAL_STATUS_CURRENT = "version=sales_menu.sales_manual_status_current.version+1";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_INSERT_INTO_SALES_MANUAL_STATUS_EVENT = "INSERT INTO sales_menu.sales_manual_status_event(event_ref,sales_item_ref,channel_ref,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_TARGET_KIND_TARGET_REF_EVENT_KIND_REASON = "target_kind,target_ref,event_kind,reason,actor_type,actor_id,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_ACTOR_DISPLAY_SNAPSHOT_OCCURRED_AT_EPOCH_MILLIS = "actor_display_snapshot,occurred_at_epoch_millis) VALUES(?,?,?,?,?,?,?,?,?,?,?)";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_SELECT_SALES_VERSION_ITEM_SKU_RESOLVED_SKU_NAME = "SELECT resolved_sku_name FROM sales_menu.sales_version_item_sku ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_WHERE_VERSION_REF_SALES_ITEM_REF_SKU_REF = "WHERE version_ref=? AND sales_item_ref=? AND sku_ref=?";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_SELECT_SALES_VERSION_ITEM_ORDER_OPTION_VA_RESOLVED_VALUE_NAME = "SELECT resolved_value_name FROM sales_menu.sales_version_item_order_option_value ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_WHERE_VERSION_REF_SALES_ITEM_REF_DEFINITION_VALUE_REF = "WHERE version_ref=? AND sales_item_ref=? AND definition_value_ref=?";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_SELECT_REQUEST_HASH_STATUS_READBACK_JSON_TEXT = "SELECT request_hash,status,response_json::text readback_json ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_FROM_CLAUSE_SALES_COMMAND_RECEIPT_FROM_SALES_MENU_SALES_COMMAN = "FROM sales_menu.sales_command_receipt ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_WHERE_WORKSPACE_UUID_OPERATION_ID_IDEMPOTENCY_KEY = "WHERE workspace_uuid=? AND operation_id=? AND idempotency_key=?";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_INSERT_INTO_SALES_COMMAND_RECEIPT = "INSERT INTO sales_menu.sales_command_receipt(receipt_ref,workspace_uuid,group_workspace_key,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_OPERATION_ID_IDEMPOTENCY_KEY_REQUEST_HASH_STATUS = "operation_id,idempotency_key,request_hash,status,response_json,created_at_epoch_millis) ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_VALUES_VALUES_JSONB = "VALUES(?,?,?,?,?,?,? ,?::jsonb,?) ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_JOIN_CONDITION_WORKSPACE_UUID_OPERATION_ID_IDEMPOTENCY_KEY = "ON CONFLICT (workspace_uuid,operation_id,idempotency_key) DO NOTHING";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_SELECT_REQUEST_HASH_STATUS_READBACK_JSON_TEXT_ALTERNATE_A = "SELECT request_hash,status,response_json::text readback_json ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_FROM_CLAUSE_SALES_COMMAND_RECEIPT_FROM_SALES_MENU_SALES_COMMAN_ALTERNATE_A = "FROM sales_menu.sales_command_receipt ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_WHERE_WORKSPACE_UUID_OPERATION_ID_IDEMPOTENCY_KEY_ALTERNATE_A = "WHERE workspace_uuid=? AND operation_id=? AND idempotency_key=?";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_SELECT_VERSION_REF_SALES_ITEM_REF_CATALOG_ITEM_REF_SECTION_REF = "SELECT v.version_ref,i.sales_item_ref,i.catalog_item_ref,v.section_ref,v.display_order,v.version,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_DISPLAY_NAME_OVERRIDE = "v.display_name_override,v.resolved_item_name,v.resolved_item_code,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_RESOLVED_PRODUCT_SHAPE = "v.resolved_product_shape,v.resolved_sales_unit_ref,v.resolved_sales_unit_code,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_RESOLVED_SALES_UNIT_NAME = "v.resolved_sales_unit_name,v.resolved_sales_unit_dimension,v.resolved_sales_unit_precision,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_LISTED_PRICE_CENTS = "v.listed_price_cents,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_ORDERING_CONSTRAINTS_JSON_TEXT_DISPLAY_MEDIA_MODE = "v.ordering_constraints_json::text ordering_constraints_json,v.display_media_mode,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_PUBLISHED_PRIMARY_IMAGE_ASSET_REF = "v.published_primary_image_asset_ref,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_PUBLISHED_CATALOG_IMAGE_ASSET_REFS_TEXT = "v.published_catalog_image_asset_refs::text published_catalog_image_asset_refs,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_SALES_VERSION_ITEM_PREVIOUS = "EXISTS (SELECT 1 FROM sales_menu.sales_version_item previous ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_WHERE_PREVIOUS_VERSION_REF_SECTION_REF = "WHERE previous.version_ref=v.version_ref AND previous.section_ref=v.section_ref AND ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_OPEN_PAREN_PREVIOUS_DISPLAY_ORDER = "(previous.display_order < v.display_order OR ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_OPEN_PAREN_PREVIOUS_DISPLAY_ORDER_ALTERNATE_A = "(previous.display_order=v.display_order AND ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_PREVIOUS_SALES_ITEM_REF_CAN_MOVE_UP = "previous.sales_item_ref < v.sales_item_ref))) can_move_up,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_SALES_VERSION_ITEM_NEXT_ITEM = "EXISTS (SELECT 1 FROM sales_menu.sales_version_item next_item ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_WHERE_NEXT_ITEM_VERSION_REF_SECTION_REF = "WHERE next_item.version_ref=v.version_ref AND next_item.section_ref=v.section_ref AND ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_OPEN_PAREN_NEXT_ITEM_DISPLAY_ORDER = "(next_item.display_order > v.display_order OR ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_OPEN_PAREN_NEXT_ITEM_DISPLAY_ORDER_ALTERNATE_A = "(next_item.display_order=v.display_order AND ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_NEXT_ITEM_SALES_ITEM_REF_CAN_MOVE_DOWN = "next_item.sales_item_ref > v.sales_item_ref))) can_move_down ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_FROM_CLAUSE_SALES_ITEM_FROM_SALES_MENU_SALES_VERSIO = "FROM sales_menu.sales_version_item v JOIN sales_menu.sales_item i ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_JOIN_CONDITION_SALES_ITEM_REF_VERSION_REF = "ON i.sales_item_ref=v.sales_item_ref WHERE v.version_ref=?";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_CONDITION_SECTION_REF = " AND v.section_ref=?";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_CONDITION_SALES_ITEM_REF = " AND v.sales_item_ref=?";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_ORDER_BY_SECTION_REF_DISPLAY_ORDER_SALES_ITEM_REF = " ORDER BY v.section_ref,v.display_order,v.sales_item_ref";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_SELECT_SALES_COLLECTION_CURRENT_DRAFT_VERSION_REF = "SELECT current_draft_version_ref FROM sales_menu.sales_collection ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_WHERE_COLLECTION_REF = "WHERE collection_ref=?";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_SELECT_SALES_COLLECTION_LATEST_PUBLISHED_VERSION_REF = "SELECT latest_published_version_ref FROM sales_menu.sales_collection ";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_WHERE_COLLECTION_REF_ALTERNATE_A = "WHERE collection_ref=?";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_INSERT_INTO_SALES_OPERATION_RECORD = "INSERT INTO sales_menu.sales_operation_record(record_ref,workspace_uuid,group_workspace_key,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_STORE_REF_CHANNEL_REF_COLLECTION_REF_OPERATION_KIND = "store_ref,channel_ref,collection_ref,operation_kind,target_ref,target_kind,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_TARGET_DISPLAY_SNAPSHOT_RESULT_ACTOR_TYPE_ACTOR_ID = "target_display_snapshot,result,actor_type,actor_id,actor_display_snapshot,";
    public static final String SALES_MENU_MANUAL_SALE_SERVICE_OCCURRED_AT_EPOCH_MILLIS_IDEMPOTENCY_KEY = "occurred_at_epoch_millis,idempotency_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
}
