package com.catering.v2s.salesmenu.application.persistence;

/** SQL text fragments owned by SalesMenuPublicationService; B3 relocates text only and does not change execution. */
public final class SalesMenuPublicationServiceSql {
    public static final String VALUE_SEPARATOR = ",";
    public static final String PARAMETER_PLACEHOLDER = "?";
    public static final String PUBLICATION_ITEM_VALUE_ROW = "(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?::jsonb,?,?,?::jsonb,1)";
    public static final String PUBLICATION_SKU_VALUE_ROW = "(?,?,?,?,?,?,?,?)";
    public static final String PUBLICATION_MEDIA_VALUE_ROW = "(?,?,?,?)";
    public static final String SALES_MENU_PUBLICATION_SERVICE_INSERT_INTO_SALES_PUBLICATION_PUBLICATION_REF_COLLECTION_REF = "INSERT INTO sales_menu.sales_publication(publication_ref,collection_ref,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_PUBLISHED_VERSION_REF = "published_version_ref,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_SOURCE_DRAFT_REVISION = "source_draft_revision,actor_type,actor_id,actor_display_snapshot,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_OCCURRED_AT_EPOCH_MILLIS = "occurred_at_epoch_millis) VALUES(?,?,?,?,?,?,?,?)";
    public static final String SALES_MENU_PUBLICATION_SERVICE_UPDATE_SALES_COLLECTION_LATEST_PUBLISHED_VERSION_REF = "UPDATE sales_menu.sales_collection SET latest_published_version_ref=? ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_COLLECTION_REF = "WHERE collection_ref=?";
    public static final String SALES_MENU_PUBLICATION_SERVICE_DELETE_SALES_MANUAL_STATUS_CURRENT_CURRENT_STATUS = "DELETE FROM sales_menu.sales_manual_status_current current_status ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_USING_SALES_ITEM_ITEM = "USING sales_menu.sales_item item ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_CURRENT_STATUS_SALES_ITEM_REF_ITEM = "WHERE current_status.sales_item_ref=item.sales_item_ref ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_ITEM_COLLECTION_REF = "AND item.collection_ref=? ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_CURRENT_STATUS_TARGET_KIND_ITEM = "AND current_status.target_kind <> 'ITEM' ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_AND_NOT_EXISTS = "AND NOT EXISTS (";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_SALES_VERSION_ITEM_SKU_SKU = "SELECT 1 FROM sales_menu.sales_version_item_sku sku ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_SKU_VERSION_REF_SALES_ITEM_REF_CURRENT_STATUS = "WHERE sku.version_ref=? AND sku.sales_item_ref=current_status.sales_item_ref ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_CURRENT_STATUS_TARGET_KIND_SKU_SKU_REF = "AND current_status.target_kind='SKU' AND sku.sku_ref=current_status.target_ref) ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_AND_NOT_EXISTS_ALTERNATE_A = "AND NOT EXISTS (";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_SALES_VERSION_ITEM_ORDER_OPTION_VA_OPTION_VALUE = "SELECT 1 FROM sales_menu.sales_version_item_order_option_value option_value ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_OPTION_VALUE_VERSION_REF_SALES_ITEM_REF = "WHERE option_value.version_ref=? AND option_value.sales_item_ref=";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_CURRENT_STATUS_SALES_ITEM_REF = "current_status.sales_item_ref ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_CURRENT_STATUS_TARGET_KIND_ORDER_OPTION_VALUE = "AND current_status.target_kind='ORDER_OPTION_VALUE' ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_OPTION_VALUE_DEFINITION_VALUE_REF_CURRENT_STATUS_TARGET_REF = "AND option_value.definition_value_ref=current_status.target_ref)";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_REQUEST_HASH_STATUS_READBACK_JSON_TEXT = "SELECT request_hash,status,readback_json::text readback_json ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_FROM_CLAUSE_SALES_COMMAND_RECEIPT_FROM_SALES_MENU_SALES_COMMAN = "FROM sales_menu.sales_command_receipt ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_WORKSPACE_UUID_OPERATION_ID_IDEMPOTENCY_KEY = "WHERE workspace_uuid=? AND operation_id=? AND idempotency_key=?";
    public static final String SALES_MENU_PUBLICATION_SERVICE_INSERT_INTO_SALES_COMMAND_RECEIPT = "INSERT INTO sales_menu.sales_command_receipt(receipt_ref,workspace_uuid,group_workspace_key,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_OPERATION_ID_IDEMPOTENCY_KEY_REQUEST_HASH_STATUS = "operation_id,idempotency_key,request_hash,status,readback_json,created_at_epoch_millis) ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_VALUES_VALUES_JSONB = "VALUES(?,?,?,?,?,?,? ,?::jsonb,?) ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_JOIN_CONDITION_WORKSPACE_UUID_OPERATION_ID_IDEMPOTENCY_KEY = "ON CONFLICT (workspace_uuid,operation_id,idempotency_key) DO NOTHING";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_REQUEST_HASH_STATUS_READBACK_JSON_TEXT_ALTERNATE_A = "SELECT request_hash,status,readback_json::text readback_json ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_FROM_CLAUSE_SALES_COMMAND_RECEIPT_FROM_SALES_MENU_SALES_COMMAN_ALTERNATE_A = "FROM sales_menu.sales_command_receipt ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_WORKSPACE_UUID_OPERATION_ID_IDEMPOTENCY_KEY_ALTERNATE_A = "WHERE workspace_uuid=? AND operation_id=? AND idempotency_key=?";
    public static final String SALES_MENU_PUBLICATION_SERVICE_INSERT_INTO_SALES_VERSION_SECTION = "INSERT INTO sales_menu.sales_version_section(version_ref,section_ref,collection_ref,name,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_DISPLAY_ORDER = "display_order) ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_SECTION_REF_COLLECTION_REF_NAME_DISPLAY_ORDER = "SELECT ?,section_ref,collection_ref,name,display_order ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_FROM_CLAUSE_SALES_VERSION_SECTION_FROM_SALES_MENU_SALES_VERSIO = "FROM sales_menu.sales_version_section ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_VERSION_REF = "WHERE version_ref=?";
    public static final String SALES_MENU_PUBLICATION_SERVICE_INSERT_INTO_SALES_VERSION_ITEM_ORDER_OPTION = "INSERT INTO sales_menu.sales_version_item_order_option(version_ref,sales_item_ref,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_DEFINITION_REF = "definition_ref,resolved_definition_name,selection_mode,required,min_selection_count,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_MAX_SELECTION_COUNT_DISPLAY_ORDER = "max_selection_count,display_order) VALUES(?,?,?,?,?,?,?,?,?)";
    public static final String SALES_MENU_PUBLICATION_SERVICE_INSERT_INTO_SALES_VERSION_ITEM_ORDER_OPTION_VA = "INSERT INTO sales_menu.sales_version_item_order_option_value(version_ref,sales_item_ref,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_DEFINITION_REF_ALTERNATE_A = "definition_ref,definition_value_ref,resolved_value_name,display_order,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_DEFAULT_VALUE_EXTRA_PRICE = "default_value,extra_price) VALUES(?,?,?,?,?,?,?,?)";
    public static final String SALES_MENU_PUBLICATION_SERVICE_INSERT_INTO_SALES_VERSION_ITEM_VERSION_REF_SALES_ITEM_REF_SECTION_REF = "INSERT INTO sales_menu.sales_version_item(version_ref,sales_item_ref,section_ref,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_COLLECTION_REF = "collection_ref,display_order,display_name_override,resolved_item_name,resolved_item_code,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_RESOLVED_PRODUCT_SHAPE = "resolved_product_shape,resolved_sales_unit_ref,resolved_sales_unit_code,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_RESOLVED_SALES_UNIT_NAME = "resolved_sales_unit_name,resolved_sales_unit_dimension,resolved_sales_unit_precision,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_LISTED_PRICE_CENTS = "listed_price_cents,ordering_constraints_json,display_media_mode,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_PUBLISHED_PRIMARY_IMAGE_ASSET_REF = "published_primary_image_asset_ref,published_catalog_image_asset_refs,version) VALUES ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_INSERT_INTO_SALES_VERSION_ITEM_SKU_VERSION_REF_SALES_ITEM_REF_SKU_REF = "INSERT INTO sales_menu.sales_version_item_sku(version_ref,sales_item_ref,sku_ref,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_LISTED_PRICE_CENTS_ALTERNATE_A = "listed_price_cents,resolved_sku_code,resolved_sku_name,default_price_cents,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_DISPLAY_ORDER_ALTERNATE_A = "display_order) VALUES ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_INSERT_INTO_SALES_VERSION_ITEM_MEDIA = "INSERT INTO sales_menu.sales_version_item_media(version_ref,sales_item_ref,asset_ref,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_DISPLAY_ORDER_ALTERNATE_B = "display_order) VALUES ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_INSERT_INTO_SALES_COLLECTION_VERSION = "INSERT INTO sales_menu.sales_collection_version(version_ref,collection_ref,kind,revision,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_SCHEDULE_KIND = "schedule_kind,schedule_start_local_time,schedule_end_local_time,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_SOURCE_DRAFT_VERSION_REF_SOURCE_DRAFT_REVISION_VERSION = "source_draft_version_ref,source_draft_revision,version) VALUES(?,?,?,?,?,?,?,?,?,1)";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_VERSION_REF_SALES_ITEM_REF_CATALOG_ITEM_REF_SECTION_REF = "SELECT v.version_ref,i.sales_item_ref,i.catalog_item_ref,v.section_ref,v.display_order,v.version,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_DISPLAY_NAME_OVERRIDE = "v.display_name_override,v.resolved_item_name,v.resolved_item_code,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_RESOLVED_PRODUCT_SHAPE_ALTERNATE_A = "v.resolved_product_shape,v.resolved_sales_unit_ref,v.resolved_sales_unit_code,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_RESOLVED_SALES_UNIT_NAME_ALTERNATE_A = "v.resolved_sales_unit_name,v.resolved_sales_unit_dimension,v.resolved_sales_unit_precision,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_LISTED_PRICE_CENTS_ALTERNATE_B = "v.listed_price_cents,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_ORDERING_CONSTRAINTS_JSON_TEXT_DISPLAY_MEDIA_MODE = "v.ordering_constraints_json::text ordering_constraints_json,v.display_media_mode,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_PUBLISHED_PRIMARY_IMAGE_ASSET_REF_ALTERNATE_A = "v.published_primary_image_asset_ref,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_PUBLISHED_CATALOG_IMAGE_ASSET_REFS_TEXT = "v.published_catalog_image_asset_refs::text published_catalog_image_asset_refs,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_SALES_VERSION_ITEM_PREVIOUS = "EXISTS (SELECT 1 FROM sales_menu.sales_version_item previous ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_PREVIOUS_VERSION_REF_SECTION_REF = "WHERE previous.version_ref=v.version_ref AND previous.section_ref=v.section_ref AND ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_OPEN_PAREN_PREVIOUS_DISPLAY_ORDER = "(previous.display_order < v.display_order OR ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_OPEN_PAREN_PREVIOUS_DISPLAY_ORDER_ALTERNATE_A = "(previous.display_order=v.display_order AND ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_PREVIOUS_SALES_ITEM_REF_CAN_MOVE_UP = "previous.sales_item_ref < v.sales_item_ref))) can_move_up,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_SALES_VERSION_ITEM_NEXT_ITEM = "EXISTS (SELECT 1 FROM sales_menu.sales_version_item next_item ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_NEXT_ITEM_VERSION_REF_SECTION_REF = "WHERE next_item.version_ref=v.version_ref AND next_item.section_ref=v.section_ref AND ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_OPEN_PAREN_NEXT_ITEM_DISPLAY_ORDER = "(next_item.display_order > v.display_order OR ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_OPEN_PAREN_NEXT_ITEM_DISPLAY_ORDER_ALTERNATE_A = "(next_item.display_order=v.display_order AND ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_NEXT_ITEM_SALES_ITEM_REF_CAN_MOVE_DOWN = "next_item.sales_item_ref > v.sales_item_ref))) can_move_down ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_FROM_CLAUSE_SALES_ITEM_FROM_SALES_MENU_SALES_VERSIO = "FROM sales_menu.sales_version_item v JOIN sales_menu.sales_item i ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_JOIN_CONDITION_SALES_ITEM_REF_VERSION_REF = "ON i.sales_item_ref=v.sales_item_ref WHERE v.version_ref=?";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_SECTION_REF = " AND v.section_ref=?";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_SALES_ITEM_REF = " AND v.sales_item_ref=?";
    public static final String SALES_MENU_PUBLICATION_SERVICE_ORDER_BY_SECTION_REF_DISPLAY_ORDER_SALES_ITEM_REF = " ORDER BY v.section_ref,v.display_order,v.sales_item_ref";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_SALES_ITEM_REF = "SELECT sales_item_ref,definition_ref,resolved_definition_name,selection_mode,required,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_MIN_SELECTION_COUNT_MAX_SELECTION_COUNT_DISPLAY_ORDER = "min_selection_count,max_selection_count,display_order ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_FROM_CLAUSE_SALES_VERSION_ITEM_ORDER_OPTION_VERSION_REF = "FROM sales_menu.sales_version_item_order_option WHERE version_ref=? ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_SALES_ITEM_REF_ALTERNATE_A = "AND sales_item_ref IN (";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CLOSE_PAREN = ") ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_ORDER_BY_SALES_ITEM_REF_DISPLAY_ORDER_DEFINITION_REF = "ORDER BY sales_item_ref,display_order,definition_ref";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_SALES_ITEM_REF_ALTERNATE_A = "SELECT sales_item_ref,definition_ref,definition_value_ref,resolved_value_name,display_order,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_DEFAULT_VALUE_EXTRA_PRICE_ALTERNATE_A = "default_value,extra_price ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_FROM_CLAUSE_SALES_VERSION_ITEM_ORDER_OPTION_VA_VERSION_REF = "FROM sales_menu.sales_version_item_order_option_value WHERE version_ref=? ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_SALES_ITEM_REF_ALTERNATE_B = "AND sales_item_ref IN (";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CLOSE_PAREN_ALTERNATE_A = ") ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_ORDER_BY_SALES_ITEM_REF = "ORDER BY sales_item_ref,definition_ref,display_order,definition_value_ref";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_SALES_ITEM_REF_SKU_REF_LISTED_PRICE_CENTS_RESOLVED_SKU_CODE = "SELECT sales_item_ref,sku_ref,listed_price_cents,resolved_sku_code,resolved_sku_name,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_SALES_VERSION_ITEM_SKU_DEFAULT_PRICE_CENTS_DISPLAY_ORDER = "default_price_cents,display_order FROM sales_menu.sales_version_item_sku ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_VERSION_REF_SALES_ITEM_REF = "WHERE version_ref=? AND sales_item_ref IN (";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CLOSE_PAREN_ALTERNATE_B = ") ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_ORDER_BY_SALES_ITEM_REF_DISPLAY_ORDER_SKU_REF = "ORDER BY sales_item_ref,display_order,sku_ref";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_SALES_ITEM_REF_ASSET_REF_DISPLAY_ORDER = "SELECT sales_item_ref,asset_ref,display_order ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_FROM_CLAUSE_SALES_VERSION_ITEM_MEDIA_VERSION_REF = "FROM sales_menu.sales_version_item_media WHERE version_ref=? ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_SALES_ITEM_REF_ALTERNATE_C = "AND sales_item_ref IN (";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CLOSE_PAREN_ALTERNATE_C = ") ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_ORDER_BY_SALES_ITEM_REF_DISPLAY_ORDER_ASSET_REF = "ORDER BY sales_item_ref,display_order,asset_ref";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_SALES_COLLECTION_CURRENT_DRAFT_VERSION_REF = "SELECT current_draft_version_ref FROM sales_menu.sales_collection ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_COLLECTION_REF_ALTERNATE_A = "WHERE collection_ref=?";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_SALES_COLLECTION_LATEST_PUBLISHED_VERSION_REF = "SELECT latest_published_version_ref FROM sales_menu.sales_collection ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_WHERE_COLLECTION_REF_ALTERNATE_B = "WHERE collection_ref=?";
    public static final String SALES_MENU_PUBLICATION_SERVICE_SELECT_SALES_COLLECTION_ACTIVATION_CHANNEL_REF_COLLECTION_REF = "SELECT channel_ref FROM sales_menu.sales_collection_activation WHERE collection_ref=? ";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONDITION_STATUS_ENABLED_CHANNEL_REF = "AND status='ENABLED' ORDER BY channel_ref";
    public static final String SALES_MENU_PUBLICATION_SERVICE_INSERT_INTO_SALES_OPERATION_RECORD = "INSERT INTO sales_menu.sales_operation_record(record_ref,workspace_uuid,group_workspace_key,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_STORE_REF_CHANNEL_REF_COLLECTION_REF_OPERATION_KIND = "store_ref,channel_ref,collection_ref,operation_kind,target_ref,target_kind,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_TARGET_DISPLAY_SNAPSHOT_RESULT_ACTOR_TYPE_ACTOR_ID = "target_display_snapshot,result,actor_type,actor_id,actor_display_snapshot,";
    public static final String SALES_MENU_PUBLICATION_SERVICE_CONTINUATION_OCCURRED_AT_EPOCH_MILLIS_IDEMPOTENCY_KEY = "occurred_at_epoch_millis,idempotency_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
}
