export const activeSkeletonBatch = 2 as const;

export const skeletonGraph = {
  'kernel.base.contracts': {
    batch: 1,
    plannedKind: 'toolkit',
    dependencies: [],
    devDependencies: [],
  },
  'kernel.base.platform-ports': {
    batch: 1,
    plannedKind: 'toolkit',
    dependencies: ['kernel.base.contracts'],
    devDependencies: [],
  },
  'kernel.base.state': {
    batch: 1,
    plannedKind: 'toolkit',
    dependencies: ['kernel.base.contracts', 'kernel.base.platform-ports'],
    devDependencies: [],
  },
  'kernel.base.runtime': {
    batch: 1,
    dependencies: ['kernel.base.contracts', 'kernel.base.platform-ports', 'kernel.base.state'],
    devDependencies: [],
  },
  'kernel.base.transport': {
    batch: 2,
    plannedKind: 'owner',
    dependencies: ['kernel.base.contracts', 'kernel.base.platform-ports', 'kernel.base.state', 'kernel.base.runtime'],
    devDependencies: [],
  },
  'kernel.base.display-context': {
    batch: 1,
    dependencies: ['kernel.base.contracts', 'kernel.base.platform-ports', 'kernel.base.state', 'kernel.base.runtime'],
    devDependencies: [],
  },
  'kernel.base.workflow': {
    batch: 2,
    plannedKind: 'owner',
    dependencies: ['kernel.base.contracts', 'kernel.base.platform-ports', 'kernel.base.state', 'kernel.base.runtime'],
    devDependencies: [],
  },
  'kernel.base.ui-state': {
    batch: 1,
    kind: 'owner',
    dependencies: [
      'kernel.base.contracts',
      'kernel.base.platform-ports',
      'kernel.base.state',
      'kernel.base.runtime',
      'kernel.base.display-context',
    ],
    devDependencies: [],
  },
  'kernel.base.test-support': {
    batch: 1,
    plannedKind: 'toolkit',
    dependencies: [],
    devDependencies: [
      'kernel.base.contracts',
      'kernel.base.platform-ports',
      'kernel.base.state',
      'kernel.base.runtime',
    ],
  },
  'ui.base.render': {
    batch: 1,
    plannedKind: 'toolkit',
    dependencies: ['kernel.base.contracts', 'kernel.base.platform-ports', 'kernel.base.runtime', 'kernel.base.state', 'kernel.base.ui-state'],
    devDependencies: [],
  },
  'ui.base.automation': {
    batch: 1,
    plannedKind: 'owner',
    dependencies: ['kernel.base.platform-ports', 'kernel.base.runtime', 'kernel.base.ui-state'],
    devDependencies: [],
  },
  'ui.base.primitives': {
    batch: 1,
    plannedKind: 'toolkit',
    dependencies: ['ui.base.automation'],
    devDependencies: [],
  },
  'ui.base.input': {
    batch: 2,
    plannedKind: 'owner',
    dependencies: [
      'kernel.base.platform-ports',
      'kernel.base.runtime',
      'kernel.base.state',
      'ui.base.render',
      'ui.base.primitives',
    ],
    devDependencies: [],
  },
  'ui.base.admin-shell': {
    batch: 2,
    plannedKind: 'owner',
    dependencies: [
      'kernel.base.platform-ports',
      'kernel.base.runtime',
      'kernel.base.state',
      'ui.base.render',
      'ui.base.primitives',
      'kernel.base.ui-state',
    ],
    devDependencies: [],
  },
  'ui.base.test-support': {
    batch: 1,
    plannedKind: 'toolkit',
    dependencies: [],
    devDependencies: [
      'kernel.base.contracts',
      'kernel.base.display-context',
      'kernel.base.platform-ports',
    ],
  },
  'kernel.feature.sample-staff-session': {
    batch: 2,
    dependencies: ['kernel.base.contracts', 'kernel.base.state', 'kernel.base.runtime'],
    devDependencies: ['kernel.base.platform-ports'],
  },
  'kernel.feature.sample-member-registry': {
    batch: 2,
    dependencies: ['kernel.base.contracts', 'kernel.base.state', 'kernel.base.runtime'],
    devDependencies: ['kernel.base.platform-ports'],
  },
  'ui.feature.sample-staff-auth': {
    batch: 2,
    dependencies: [
      'kernel.base.state',
      'kernel.base.ui-state',
      'kernel.base.runtime',
      'kernel.feature.sample-staff-session',
      'ui.base.render',
      'ui.base.primitives',
    ],
    devDependencies: [],
  },
  'ui.feature.sample-member-desk': {
    batch: 2,
    dependencies: [
      'kernel.base.state',
      'kernel.base.ui-state',
      'kernel.base.runtime',
      'kernel.base.display-context',
      'kernel.feature.sample-staff-session',
      'kernel.feature.sample-member-registry',
      'ui.base.render',
      'ui.base.primitives',
    ],
    devDependencies: [],
  },
  'ui.integration.sample-console': {
    batch: 1,
    plannedKind: 'toolkit',
    dependencies: [
      'kernel.base.contracts',
      'kernel.base.platform-ports',
      'kernel.base.runtime',
      'kernel.base.display-context',
      'kernel.base.ui-state',
      'kernel.feature.sample-staff-session',
      'kernel.feature.sample-member-registry',
      'ui.base.render',
      'ui.feature.sample-staff-auth',
      'ui.feature.sample-member-desk',
    ],
    devDependencies: ['ui.base.test-support'],
  },
  'adapter.android.persist-kv': {
    batch: 1,
    plannedKind: 'toolkit',
    dependencies: ['kernel.base.platform-ports'],
    devDependencies: [],
  },
  'adapter.android.device': {
    batch: 2,
    plannedKind: 'toolkit',
    dependencies: ['kernel.base.platform-ports'],
    devDependencies: [],
  },
  'adapter.android.app-control': {
    batch: 2,
    plannedKind: 'toolkit',
    dependencies: ['kernel.base.platform-ports'],
    devDependencies: [],
  },
  'adapter.android.logger': {
    batch: 2,
    plannedKind: 'toolkit',
    dependencies: ['kernel.base.platform-ports'],
    devDependencies: [],
  },
  'adapter.android.dual-screen': {
    batch: 2,
    plannedKind: 'toolkit',
    dependencies: ['kernel.base.platform-ports'],
    devDependencies: [],
  },
  'assembly.android.sample-terminal': {
    batch: 1,
    plannedKind: 'toolkit',
    dependencies: [
      'kernel.base.platform-ports',
      'adapter.android.persist-kv',
      'adapter.android.device',
      'adapter.android.app-control',
      'adapter.android.logger',
      'adapter.android.dual-screen',
      'ui.integration.sample-console',
    ],
    devDependencies: [],
  },
} as const;
