/** Stable locators for terminal update package management. */
export const terminalUpdateTestIds = {
  page: 'platform-terminal-update-page',
  upload: 'platform-terminal-update-upload',
  uploadInput: 'platform-terminal-update-upload-input',
  artifactKind: 'platform-terminal-update-artifact-kind',
  artifactKindOption: (kind: 'FULL' | 'HOT') => `platform-terminal-update-artifact-kind-option-${kind.toLowerCase()}`,
  artifactFilterKind: 'platform-terminal-update-artifact-filter-kind',
  artifactFilterApplication: 'platform-terminal-update-artifact-filter-application',
  artifactFilterRuntime: 'platform-terminal-update-artifact-filter-runtime',
  artifactFilterQuery: 'platform-terminal-update-artifact-filter-query',
  artifactFilterSubmit: 'platform-terminal-update-artifact-filter-submit',
  artifactFilterReset: 'platform-terminal-update-artifact-filter-reset',
  artifactOpen: (artifactRef: string) => `platform-terminal-update-artifact-open-${artifactRef}`,
  minimumFull: 'platform-terminal-update-minimum-full',
  minimumFullCandidate: (artifactRef: string) => `platform-terminal-update-minimum-full-candidate-${artifactRef}`,
  save: 'platform-terminal-update-save',
  list: 'platform-terminal-update-list',
  detail: 'platform-terminal-update-detail',
  parseSuccess: 'platform-terminal-update-parse-success',
  refresh: 'platform-terminal-update-refresh',
  releaseStagedUpload: 'platform-terminal-update-release-staged-upload',
} as const;
