package com.catering.v2s.businesschannel.application.persistence;

/** SQL text owned by BusinessChannelTemplateService; B3 relocates text without changing execution. */
public final class BusinessChannelTemplateServiceSql {
    public static final String PARAMETER_PLACEHOLDER = "?";
    public static final String VISIBLE_STORE_REF_VALUE = "(?::uuid)";
    public static final String VALUE_SEPARATOR = ", ";
    public static final String VISIBLE_STORE_REF_ROWS_SUFFIX = ") refs(store_ref)";
    public static final String SORT_DIRECTION_DESC = "DESC";
    public static final String SORT_DIRECTION_ASC = "ASC";
    public static final String SORT_SEPARATOR = " ";
    public static final String TEMPLATE_REF_SORT_EXPRESSION = "template_ref";
    public static final String TEMPLATE_NAME_SORT_EXPRESSION = "COALESCE(template_name, '')";
    public static final String TEMPLATE_CODE_SORT_EXPRESSION = "COALESCE(template_code, '')";
    public static final String ACCESS_KIND_SORT_EXPRESSION = "access_kind";
    public static final String OPERATOR_KIND_SORT_EXPRESSION = "operator_kind";
    public static final String ORDER_KIND_SORT_EXPRESSION = "order_kind";
    public static final String STATUS_SORT_EXPRESSION = "status";
    public static final String TEMPLATE_REF_ORDER_SUFFIX = ", template_ref";
    public static final String CURSOR_LESS_OPERATOR = "<";
    public static final String CURSOR_GREATER_OPERATOR = ">";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY = " WHERE workspace_uuid=? AND group_workspace_key=?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_PROJECT_REF = " AND project_ref=?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_STATUS = " AND status=?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_OPERATOR_KIND = " AND operator_kind=?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_ORDER_BY = " ORDER BY ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_LIMIT = " LIMIT ?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_PROJECT_REF = " WHERE t.workspace_uuid=? AND t.group_workspace_key=? AND t.project_ref=? ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_OPERATOR_KIND_STORE_STATUS_ENABLED = "AND t.operator_kind='STORE' AND t.status='ENABLED' AND (";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_STORE_VISIBILITY_SCOPE_ALL_PROJECT_STORES = "t.store_visibility_scope='ALL_PROJECT_STORES' OR (";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_STORE_VISIBILITY_SCOPE_SELECTED_PROJECT_STORES = "t.store_visibility_scope='SELECTED_PROJECT_STORES' AND EXISTS (";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_BUSINESS_CHANNEL_TEMPLATE_STORE_VI = "SELECT 1 FROM business_channel.business_channel_template_store_visibility v ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_TEMPLATE_REF_STORE_REF = "WHERE v.template_ref=t.template_ref AND v.store_ref=?)))";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_TEMPLATE_REF = " AND template_ref > ?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_BUSINESS_CHANNEL_TEMPLATE_SELECT_COUNT_FROM_BUSINESS_C = "SELECT count(*) FROM business_channel.business_channel_template t";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_ORDER_BY_ALTERNATE_A = " ORDER BY ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_LIMIT_ALTERNATE_A = " LIMIT ?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_TEMPLATE_REF_WORKSPACE_UUID_GROUP_WORKSPACE_KEY = " WHERE v.template_ref=? AND t.workspace_uuid=? AND t.group_workspace_key=? ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_PROJECT_REF_OPERATOR_KIND_STORE = "AND t.project_ref=? AND t.operator_kind='STORE' ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_STORE_REF_WORKSPACE_UUID = "AND s.id=v.store_ref AND s.workspace_uuid=t.workspace_uuid ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_GROUP_WORKSPACE_KEY_PROJECT_ID_PROJECT_REF = "AND s.group_workspace_key=t.group_workspace_key AND s.project_id=t.project_ref";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_STATUS_VOIDED = " AND s.status <> 'VOIDED'";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_CODE = " AND (COALESCE(s.code,'') > ? OR (COALESCE(s.code,'') = ? ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_STORE_REF = "AND v.store_ref > CAST(? AS uuid)))";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_FROM_CLAUSE_BUSINESS_CHANNEL_TEMPLATE_STORE_VI = " FROM business_channel.business_channel_template_store_visibility v ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_JOIN_BUSINESS_CHANNEL_TEMPLATE_TEMPLATE_REF = "JOIN business_channel.business_channel_template t ON t.template_ref=v.template_ref ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_JOIN_STORE_STORE_REF = "JOIN organization.store s ON s.id=v.store_ref";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_SELECT_COUNT = "SELECT count(*)";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_STORE_REF_CODE_STORE_CODE_NAME = "SELECT v.store_ref, s.code AS store_code, s.name AS store_name, s.status AS store_status";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_ORDER_BY_CODE_STORE_REF = " ORDER BY COALESCE(s.code,''), v.store_ref LIMIT ?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_BUSINESS_CHANNEL_TEMPLATE_TEMPLATE_REF_PROJECT_REF = "SELECT template_ref, project_ref FROM business_channel.business_channel_template ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_TEMPLATE_REF = "WHERE workspace_uuid=? AND group_workspace_key=? AND template_ref=?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_INSERT_INTO_BUSINESS_CHANNEL_TEMPLATE_INSERT_INTO_BUSINESS_CHANNEL = "INSERT INTO business_channel.business_channel_template ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_OPEN_PAREN_TEMPLATE_REF = "(template_ref, workspace_uuid, group_workspace_key, project_ref, templat";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_E_NAME_TEMPLATE_CODE = "e_name, template_code, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_ACCESS_KIND_OPERATOR_KIND_ORDER_KIND_DINE_IN_FORM = "access_kind, operator_kind, order_kind, dine_in_form, provider_code, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_STORE_VISIBILITY_SCOPE_STATUS = "store_visibility_scope, status, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_VERSION = "version, created_at_epoch_millis, updated_at_epoch_millis) ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_VALUES_ENABLED = "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'ENABLED', 1, ?, ?)";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_UPDATE_BUSINESS_CHANNEL_TEMPLATE_STATUS = "UPDATE business_channel.business_channel_template SET status=?, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_VERSION_UPDATED_AT_EPOCH_MILLIS_TEMPLATE_REF = "version=version+1, updated_at_epoch_millis=? WHERE template_ref=? ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_VERSION = "AND workspace_uuid=? AND group_workspace_key=? AND version=?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_TEMPLATE_REF_ALTERNATE_A = "WHERE workspace_uuid=? AND group_workspace_key=? AND template_ref=?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_TEMPLATE_REF_ALTERNATE_B = "WHERE workspace_uuid=? AND group_workspace_key=? AND template_ref=? FOR UPDATE";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_TEMPLATE_REF_ALTERNATE_C = "WHERE workspace_uuid=? AND group_workspace_key=? AND template_ref=? FOR UPDATE";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_TEMPLATE_REF_PROJECT_REF = "SELECT t.workspace_uuid, t.group_workspace_key, t.template_ref, t.project_ref, t.template_name, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_TEMPLATE_CODE_ACCESS_KIND_OPERATOR_KIND_ORDER_KIND = "t.template_code, t.access_kind, t.operator_kind, t.order_kind, t.dine_in_form, t.provider_code, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_STORE_VISIBILITY_SCOPE_STATUS_VERSION = "t.store_visibility_scope, t.status, t.version, (SELECT count(*) FROM ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_BUSINESS_CHANNEL_TEMPLATE_STORE_VI = "business_channel.business_channel_template_store_visibility v ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_JOIN_STORE_VISIBLE_STORE_STORE_REF = "JOIN organization.store visible_store ON visible_store.id=v.store_ref ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_VISIBLE_STORE_WORKSPACE_UUID = "AND visible_store.workspace_uuid=t.workspace_uuid ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_VISIBLE_STORE_GROUP_WORKSPACE_KEY = "AND visible_store.group_workspace_key=t.group_workspace_key ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_VISIBLE_STORE_PROJECT_ID_PROJECT_REF = "AND visible_store.project_id=t.project_ref ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_TEMPLATE_REF_VISIBLE_STORE_STATUS_VOIDED = "WHERE v.template_ref=t.template_ref AND visible_store.status <> 'VOIDED') AS visible_store_count, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_ARRAY_AGG_STORE_REF = "COALESCE((SELECT array_agg(v.store_ref ORDER BY v.store_ref) FROM ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_BUSINESS_CHANNEL_TEMPLATE_STORE_VI_ALTERNATE_A = "business_channel.business_channel_template_store_visibility v ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_TEMPLATE_REF_VISIBLE_STORE_REFS = "WHERE v.template_ref=t.template_ref), ARRAY[]::uuid[]) AS visible_store_refs, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_OPEN_PAREN_ORGANIZATION_NODE_PROJECT_STATUS = "(SELECT project.status FROM organization.organization_node project ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_PROJECT_PROJECT_REF_WORKSPACE_UUID = "WHERE project.id=t.project_ref AND project.workspace_uuid=t.workspace_uuid ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_PROJECT_GROUP_WORKSPACE_KEY_PROJECT_STATUS = "AND project.group_workspace_key=t.group_workspace_key) AS project_status ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_FROM_CLAUSE_BUSINESS_CHANNEL_TEMPLATE_FROM_BUSINESS_CHANNEL_BUSINE = "FROM business_channel.business_channel_template t ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CTE_ANCESTRY = "WITH RECURSIVE ancestry AS (";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_SOURCE_REF_PARENT_ID_NODE_TYPE_STATUS = "SELECT id AS source_ref, id, parent_id, node_type, status, 0 AS depth ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_FROM_CLAUSE_ORGANIZATION_NODE_FROM_ORGANIZATION_ORGANIZATI = "FROM organization.organization_node ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_WHERE_ID_IN = "WHERE id IN (";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CLOSE_PAREN_WORKSPACE_UUID_GROUP_WORKSPACE_KEY = ") AND workspace_uuid=? AND group_workspace_key=? ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_UNION_CHILD_SOURCE_REF_PARENT_PARENT_ID = "UNION ALL SELECT child.source_ref, parent.id, parent.parent_id, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_PARENT_NODE_TYPE_STATUS_CHILD = "parent.node_type, parent.status, child.depth+1 ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_FROM_CLAUSE_ANCESTRY_PARENT_CHILD_PARENT_ID = "FROM organization.organization_node parent JOIN ancestry child ON parent.id=child.parent_id ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_PARENT_WORKSPACE_UUID_GROUP_WORKSPACE_KEY = "WHERE parent.workspace_uuid=? AND parent.group_workspace_key=? ) ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_ANCESTRY_SOURCE_REF_NODE_TYPE_STATUS_DEPTH = "SELECT source_ref, node_type, id, status FROM ancestry ORDER BY source_ref, depth DESC";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_BUSINESS_CHANNEL_TEMPLATE_PROJECT_REF_OPERATOR_KIND = "SELECT project_ref, operator_kind FROM business_channel.business_channel_template ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_TEMPLATE_REF_ALTERNATE_D = "WHERE workspace_uuid=? AND group_workspace_key=? AND template_ref=?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_BUSINESS_CHANNEL_TEMPLATE_STORE_VI_ALTERNATE_A = "SELECT count(*) FROM business_channel.business_channel_template_store_visibility ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_TEMPLATE_REF_STORE_REF_ALTERNATE_A = "WHERE template_ref=? AND store_ref=?";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_STORE_REF = "SELECT NULL::uuid AS store_ref WHERE FALSE";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_REFS_STORE_REF = "SELECT refs.store_ref FROM (VALUES ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CTE_DELETED = "WITH deleted AS (";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_DELETE_BUSINESS_CHANNEL_TEMPLATE_STORE_VI = "DELETE FROM business_channel.business_channel_template_store_visibility ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_TEMPLATE_REF = "WHERE template_ref=? RETURNING template_ref), ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_DELETED_TARGET_TEMPLATE_TEMPLATE_REF = "target_template AS (SELECT ?::uuid AS template_ref UNION SELECT template_ref FROM deleted), ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_INSERT_BUSINESS_CHANNEL_TEMPLATE_STORE_VI_INSERTED = "inserted AS (INSERT INTO business_channel.business_channel_template_store_visibility ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_OPEN_PAREN_TEMPLATE_REF_STORE_REF_TARGET_TEMPLATE_RELATION_ROWS = "(template_ref, store_ref) SELECT target_template.template_ref, relation_rows.store_ref ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_FROM_CLAUSE_TARGET_TEMPLATE_FROM_TARGET_TEMPLATE_CROSS_J = "FROM target_template CROSS JOIN (";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CLOSE_PAREN_RELATION_ROWS = ") relation_rows ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_RETURNING_TEMPLATE_REF_STORE_REF = "RETURNING template_ref, store_ref), ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_UPDATE_BUSINESS_CHANNEL_TEMPLATE_UPDATED_TEMPLATE_NAME = "updated AS (UPDATE business_channel.business_channel_template t SET template_name=?, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_STORE_VISIBILITY_SCOPE = "store_visibility_scope=?, version=version+1, updated_at_epoch_millis=? ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_FROM_CLAUSE_INSERTED_INSERTED_COUNT_RELATION_WRITE = "FROM target_template CROSS JOIN (SELECT count(*) AS inserted_count FROM inserted) relation_write ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_TEMPLATE_REF_TARGET_TEMPLATE_WORKSPACE_UUID = "WHERE t.template_ref=target_template.template_ref AND t.workspace_uuid=? ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_GROUP_WORKSPACE_KEY = "AND t.group_workspace_key=? AND t.version=? AND relation_write.inserted_count >= 0 ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_RETURNING_RETURNING_T = "RETURNING t.*) ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_SELECT_UPDATED_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_TEMPLATE_REF = "SELECT updated.workspace_uuid, updated.group_workspace_key, updated.template_ref, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_UPDATE_UPDATED_PROJECT_REF_TEMPLATE_NAME_TEMPLATE_CODE = "updated.project_ref, updated.template_name, updated.template_code, updated.access_kind, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_UPDATE_UPDATED_OPERATOR_KIND_ORDER_KIND_DINE_IN_FORM = "updated.operator_kind, updated.order_kind, updated.dine_in_form, updated.provider_code, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_UPDATE_INSERTED_UPDATED_STORE_VISIBILITY_SCOPE_STATUS_VERSION = "updated.store_visibility_scope, updated.status, updated.version, (SELECT count(*) FROM inserted ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_JOIN_STORE_VISIBLE_STORE_INSERTED_STORE_REF = "JOIN organization.store visible_store ON visible_store.id=inserted.store_ref ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_VISIBLE_STORE_WORKSPACE_UUID_UPDATED = "AND visible_store.workspace_uuid=updated.workspace_uuid ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_VISIBLE_STORE_GROUP_WORKSPACE_KEY_UPDATED = "AND visible_store.group_workspace_key=updated.group_workspace_key ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_VISIBLE_STORE_PROJECT_ID_UPDATED_PROJECT_REF = "AND visible_store.project_id=updated.project_ref ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_INSERTED_TEMPLATE_REF_UPDATED_VISIBLE_STORE = "WHERE inserted.template_ref=updated.template_ref AND visible_store.status <> 'VOIDED') ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_ORGANIZATION_NODE_VISIBLE_STORE_COUNT_PROJECT_STATUS = "AS visible_store_count, (SELECT project.status FROM organization.organization_node project ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_WHERE_PROJECT_UPDATED_PROJECT_REF_WORKSPACE_UUID = "WHERE project.id=updated.project_ref AND project.workspace_uuid=updated.workspace_uuid ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION_PROJECT_GROUP_WORKSPACE_KEY_UPDATED_PROJECT_STATUS = "AND project.group_workspace_key=updated.group_workspace_key) AS project_status ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_FROM_CLAUSE_UPDATED_FROM_UPDATED = "FROM updated";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_INSERT_INTO_BUSINESS_CHANNEL_TEMPLATE_STORE_VI = "INSERT INTO business_channel.business_channel_template_store_visibility ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_OPEN_PAREN_TEMPLATE_REF_STORE_REF = "(template_ref, store_ref) VALUES (?, ?)";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_INSERT_INTO_AUDIT_EVENT = "INSERT INTO business_channel.audit_event (event_ref, workspace_uuid, group_workspace_key, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_ACTOR_TYPE = "actor_type, actor_id, actor_display_snapshot, entity_type, entity_ref, action, ";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_CHANGES_JSON_OCCURRED_AT_EPOCH_MILLIS = "changes_json, occurred_at_epoch_millis) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?::jsonb, ?)";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONDITION = " AND (";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_PARAMETER_PLACEHOLDER = " ? OR (";
    public static final String BUSINESS_CHANNEL_TEMPLATE_SERVICE_CONTINUATION_TEMPLATE_REF = " = ? AND template_ref > ?))";
}
