import {Alert, Button, Form, Input, Space} from 'antd';
import {testId, useOverlayLock} from '@catering-v2s/admin-ui-foundation';
import {useState} from 'react';

export function PublicInvitationOtpStep({pending, onBack, onSend, onVerify}: {pending: boolean; onBack: () => void; onSend: (mobile: string) => Promise<{sent: boolean; debugCode?: string}>; onVerify: (mobile: string, code: string) => Promise<boolean>}) {
  const [form] = Form.useForm<{mobile: string; code: string}>(); const [sent, setSent] = useState(false); const [debugCode, setDebugCode] = useState<string>(); const locked = useOverlayLock();
  const invalidate = () => { setSent(false); setDebugCode(undefined); form.setFieldValue('code', undefined); };
  const send = async () => form.validateFields(['mobile']).then(async ({mobile}) => { const result = await onSend(mobile); if (!result.sent) { invalidate(); return; } setSent(true); setDebugCode(result.debugCode); form.setFieldValue('code', undefined); }).catch(() => undefined);
  return <Form form={form} layout="vertical" style={{marginTop: 16}} onFinish={async ({mobile, code}) => { const done = await onVerify(mobile, code); if (!done) form.setFieldValue('code', undefined); }}><Form.Item name="mobile" label="手机号" rules={[{required: true, pattern: /^1\d{10}$/}]}><Input disabled={locked || pending} onChange={invalidate} {...testId('public-invitation-mobile')}/></Form.Item><Form.Item name="code" label="验证码" rules={[{required: true, pattern: /^\d{6}$/}]}><Input disabled={!sent || locked || pending} {...testId('public-invitation-otp')}/></Form.Item>{sent && <Alert type="success" showIcon message="验证码已发送，请在有效期内填写"/>}{debugCode && <Alert type="info" showIcon message={`当前为测试环境，验证码：${debugCode}`}/>}<Space><Button onClick={() => void send()} loading={pending} disabled={locked || pending} {...testId('public-invitation-send-otp')}>获取验证码</Button><Button onClick={onBack} disabled={locked || pending} {...testId('public-invitation-otp-back')}>返回</Button><Button type="primary" htmlType="submit" loading={pending} disabled={!sent || locked || pending} {...testId('public-invitation-verify')}>验证并继续</Button></Space></Form>;
}
