import {describe, expect, it} from 'vitest';
import {readFile} from 'node:fs/promises';

const source = await readFile(new URL('./ContractManagementPage.tsx', import.meta.url), 'utf8');
const styles = await readFile(new URL('../../../styles.css', import.meta.url), 'utf8');
const createSource = await readFile(new URL('./ContractCreateDrawer.tsx', import.meta.url), 'utf8');
const editSource = await readFile(new URL('./ContractEditDrawer.tsx', import.meta.url), 'utf8');
const detailSource = await readFile(new URL('./ContractDetailDrawer.tsx', import.meta.url), 'utf8');
const invalidateSource = await readFile(new URL('./ContractInvalidateModal.tsx', import.meta.url), 'utf8');

describe('contract management focused contract', () => {
  it('keeps the catalog page read-only except for approved overlay entry points', () => {
    expect(source).toContain('contractPageTitle');
    expect(source).not.toContain('headerTitle={contractPageTitle}');
    expect(source).toContain('contextScopedQueryArgs');
    expect(source).toContain('operationsAdminRtkRequest.getOperationsContracts');
    expect(source).toContain('operationsRtk.useGetOperationsContractsQuery');
    expect(source).toContain("useState<StoreContractSortKey>('UPDATED_AT')");
    expect(source).toContain("useState<StoreContractSortDirection>('DESC')");
    expect(source).toContain('sort, direction, page, pageSize');
    expect(source).toContain("key: 'contractNo'");
    expect(source).toContain("key: 'effectiveFrom'");
    expect(source).toContain("title: '更新时间'");
    expect(source).toContain("dataIndex: 'updatedAt'");
    expect(source).toContain("current?.columnKey === 'contractNo' ? 'CONTRACT_NO'");
    expect(source).toContain("current?.columnKey === 'effectiveFrom' ? 'EFFECTIVE_FROM' : 'UPDATED_AT'");
    expect(source).toContain('showOwnerReadback');
    expect(source).toContain('operations-contract-page-retry');
    expect(source).toContain("testId('operations-contract-filter-submit')");
    expect(source).toContain("searchConfig.form?.submit()");
    expect(source).toContain("testId('operations-contract-filter-reset')");
    expect(source).toContain("search: false");
    expect(source).not.toContain('hideInSearch');
    expect(source).toContain('const projectId = queryContext.scopeRef');
    expect(source).toContain('useContractStoreCandidates({open: Boolean(projectId), queryContext})');
    expect(source).not.toContain('请先选择数据范围。');
    expect(source).not.toContain('请先选择项目。');
    expect(source).not.toContain('operations-contract-filter-project');
    expect(source).not.toContain('projectCandidates');
    expect(source).not.toContain("title: '项目', dataIndex: 'projectDisplay'");
    expect(source).not.toContain('row.project');
    expect(source).toContain('operations-contract-page-retry');
    expect(source).not.toMatch(/title:\s*['"]操作['"]/);
  });

  it('keeps contract mutations in independent foundation-managed overlays', () => {
    expect(createSource).toContain('useDrawerFormLifecycle');
    expect(createSource).toContain('selectedStoreTenant');
    expect(createSource).toContain("testId('operations-contract-create-tenant')");
    expect(createSource).toContain("'随门店确定'");
    expect(createSource).toContain('operations-contract-create-project');
    expect(createSource).toContain('showSearch filterOption={false} onSearch={candidates.setStoreSearch}');
    expect(createSource).toContain('onPopupScroll={candidates.onPopupScroll}');
    expect(source).toContain('showSearch: true, filterOption: false, onSearch: candidates.setStoreSearch');
    expect(source).toContain('showSearch: true, filterOption: false, onSearch: setTenantSearch');
    expect(source).toContain('operations-contract-number-link');
    expect(styles).toContain('.operations-content .ant-btn-link > .ant-typography');
    expect(styles).toContain('color: inherit !important;');
    expect(source).toContain('operations-contract-effective-range');
    expect(createSource).toContain('Form.List name="items"');
    expect(createSource).toContain('货号编码不能重复');
    expect(createSource).toContain('operationsClient.createOperationsContract');
    expect(createSource).not.toContain('body: {projectId');
    expect(editSource).toContain('useDrawerFormLifecycle');
    expect(editSource).toContain('operationsClient.updateOperationsContract');
    expect(editSource).toContain('items: contract.items');
    expect(editSource).toContain('Form.List name="items"');
    expect(editSource).toContain('货号编码不能重复');
    expect(editSource).toContain('onConflict(contract)');
    expect(detailSource).toContain('closeThen(onEdit)');
    expect(detailSource).toContain('closeThen(onInvalidate)');
    expect(detailSource).toContain('useOverlayLock(Boolean(contract))');
    expect(detailSource).toContain("operations-contract-detail-loading");
    expect(detailSource).toContain("operations-contract-detail-error");
    expect(detailSource).toContain("operations-contract-detail-extension-error");
    expect(detailSource).toContain('operationsAdminRtkRequest.getOperationsContract');
    expect(detailSource).toContain('const selected = detailQuery.error ? undefined : detailQuery.data;');
    expect(detailSource).toContain('const detailReady = Boolean(selected) && !detailQuery.isLoading;');
    expect(detailSource).toContain('extra={detailReady && selected && <Space>');
    expect(detailSource).toContain('adminDetailDescriptionsProps');
    expect(detailSource).not.toContain('detailQuery.data ?? contract');
    expect(invalidateSource).toContain('useSubmissionLifecycle');
    expect(invalidateSource).toContain('operationsClient.invalidateOperationsContract');
    expect(invalidateSource).toContain('作废后保留历史记录。');
  });
});
