export const baseTokens = Object.freeze({
  container: 'flex-1 bg-canvas p-6 gap-4',
  containerContent: 'w-full bg-canvas gap-3',
  containerCard: 'w-11/12 max-w-xl self-center rounded-xl border border-border bg-surface p-6 gap-4',
  containerElevated: 'bg-surface-elevated shadow-lg',
  containerLogin: 'w-11/12 max-w-2xl self-center rounded-2xl border border-login-border bg-login-surface p-4 gap-3 shadow-2xl md:p-10 md:gap-5',
  containerBoundedCard: 'min-h-0 overflow-hidden',
  containerBoundedContent: 'flex-1 min-h-0',
  containerCentered: 'flex-1 items-center justify-center bg-canvas p-6 gap-4',
  containerTransparent: 'flex-1 p-6 gap-4',
  imageBackground: 'absolute inset-0 w-full h-full',
  // Keep explicit line boxes for all cross-platform text tokens. Android's
  // CJK glyph descent can exceed a size-only Text line box after a surface
  // transform, while the browser derives a different default line height.
  // These token-owned line heights keep the layout box and glyph metrics
  // stable without asking product components about a host scale.
  text: 'text-foreground leading-6',
  heading: 'text-xl leading-7 font-semibold text-foreground',
  headingLogin: 'text-3xl leading-10 font-semibold text-login-foreground text-center',
  label: 'text-sm leading-5 font-medium text-muted-foreground',
  input: 'min-h-12 rounded-md border border-border bg-surface px-3 text-base text-foreground',
  button: 'self-start min-h-12 rounded-md bg-action px-4 py-3',
  buttonText: 'text-center text-base leading-6 font-semibold text-action-foreground',
  buttonLoginPrimary: 'w-full min-h-16 rounded-lg bg-login-action px-4 py-4 overflow-hidden',
  buttonLoginPrimaryText: 'text-center text-lg leading-7 font-semibold text-login-action-foreground',
  buttonLoginSecondary: 'self-center min-h-12 rounded-md bg-transparent px-4 py-2',
  buttonLoginSecondaryText: 'text-center text-lg leading-7 font-medium text-login-foreground',
  keyboardDock: 'w-full self-center rounded-[20px] border border-keyboard-border bg-keyboard-surface',
  keyboardKey: 'flex-1 self-stretch min-h-[48px] rounded-[9px] border border-keyboard-border bg-keyboard-key px-2 py-2 items-center justify-center',
  keyboardKeyCompact: 'flex-1 self-stretch min-h-[38px] rounded-[7px] border border-keyboard-border bg-keyboard-key px-1 py-1 items-center justify-center',
  keyboardKeySelected: 'flex-1 self-stretch min-h-[48px] rounded-[9px] border-2 border-keyboard-focus bg-keyboard-key px-2 py-2 items-center justify-center',
  keyboardKeySelectedCompact: 'flex-1 self-stretch min-h-[38px] rounded-[7px] border-2 border-keyboard-focus bg-keyboard-key px-1 py-1 items-center justify-center',
  keyboardAction: 'flex-1 self-stretch min-h-[48px] rounded-[9px] border border-keyboard-border bg-keyboard-action px-0 py-2 items-center justify-center',
  keyboardActionCompact: 'flex-1 self-stretch min-h-[38px] rounded-[7px] border border-keyboard-border bg-keyboard-action px-0 py-1 items-center justify-center',
  keyboardActionSelected: 'flex-1 self-stretch min-h-[48px] rounded-[9px] border-2 border-keyboard-focus bg-keyboard-action px-0 py-2 items-center justify-center',
  keyboardActionSelectedCompact: 'flex-1 self-stretch min-h-[38px] rounded-[7px] border-2 border-keyboard-focus bg-keyboard-action px-0 py-1 items-center justify-center',
  keyboardButtonText: 'text-center text-[21px] leading-[25px] font-semibold text-keyboard-key-foreground',
  keyboardButtonTextCompact: 'text-center text-[17px] leading-[20px] font-semibold text-keyboard-key-foreground',
  keyboardActionText: 'text-center text-[16px] leading-[20px] font-semibold whitespace-nowrap text-keyboard-action-foreground',
  keyboardActionTextCompact: 'text-center text-[12px] leading-[14px] font-semibold whitespace-nowrap text-keyboard-action-foreground',
  status: 'text-sm leading-6 pb-1 text-muted-foreground',
  statusLogin: 'w-full text-sm leading-6 pb-1 text-login-muted text-center',
  actions: 'flex-row flex-wrap items-start gap-3',
  actionsColumn: 'w-full items-center gap-3',
  // ScrollView's className styles the viewport on native. Keep the content
  // spacing in PrimitiveScrollView's contentContainerStyle so native and web
  // lay out the same direct-child stack.
  scroll: 'w-full flex-1 bg-canvas',
  // Explicit opt-in for composites whose parent owns the background, such as
  // a wallpaper-backed picker. Existing consumers keep the opaque token above.
  scrollTransparent: 'w-full flex-1',
  card: 'w-full rounded-xl border border-border bg-surface p-4 gap-3',
  divider: 'w-full h-px bg-border',
  stack: 'w-full gap-3',
  grid: 'w-full flex-row flex-wrap gap-3',
  pinInput: 'w-full flex-row gap-2',
  pinCell: 'flex-1 aspect-square min-w-0 items-center justify-center rounded-lg border-2 border-border bg-surface-inset',
  pinCellFocused: 'flex-1 aspect-square min-w-0 items-center justify-center rounded-lg border-2 border-focus bg-surface-inset',
  pinCellInvalid: 'flex-1 aspect-square min-w-0 items-center justify-center rounded-lg border-2 border-error-border bg-error-background',
  pinCellDisabled: 'opacity-50',
  pinCellText: 'text-2xl leading-8 font-semibold text-foreground',
  pinInputLogin: 'w-full max-w-2xl self-center flex-row justify-center gap-3',
  pinCellLogin: 'flex-1 aspect-square min-w-0 max-w-20 items-center justify-center rounded-lg border-2 border-login-border bg-login-inset',
  pinCellLoginFocused: 'flex-1 aspect-square min-w-0 max-w-20 items-center justify-center rounded-lg border-2 border-login-focus bg-login-inset',
  pinCellLoginInvalid: 'flex-1 aspect-square min-w-0 max-w-20 items-center justify-center rounded-lg border-2 border-error-border bg-error-background',
  pinCellLoginText: 'text-3xl leading-10 font-semibold text-login-foreground',
  textLogin: 'text-base leading-6 text-login-foreground text-center',
  textLoginMuted: 'text-base leading-6 text-login-muted text-center',
  iconLogin: 'text-login-icon',
  iconKeyboardAction: 'text-keyboard-action-foreground',
  // The keyboard dock owns its own opaque surface. The surrounding keyboard
  // area must stay transparent so the host surface remains visible around the
  // inset dock on both laptop and mobile layouts.
  keyboardBackdrop: 'w-full bg-transparent',
  center: 'w-full items-center justify-center',
  codeBlock: 'w-full rounded-md border border-border bg-surface p-3 font-mono text-sm leading-5 text-foreground',
  textarea: 'min-h-24 rounded-md border border-border bg-surface px-3 py-3 text-base leading-6 text-foreground',
  checkbox: 'h-6 w-6 items-center justify-center rounded-sm border border-border bg-surface',
  checkboxChecked: 'h-6 w-6 items-center justify-center rounded-sm border border-action bg-action',
  radio: 'h-6 w-6 items-center justify-center rounded-full border border-border bg-surface',
  radioSelected: 'h-6 w-6 items-center justify-center rounded-full border border-action bg-action',
  switch: 'min-w-12 rounded-full border border-border bg-surface px-1 py-1',
  switchChecked: 'min-w-12 rounded-full border border-action bg-action px-1 py-1',
  controlMarker: 'text-center text-base font-semibold text-action-foreground',
  option: 'w-full min-h-12 rounded-md border border-border bg-surface px-3 py-3 text-left text-base text-foreground',
  optionSelected: 'w-full min-h-12 rounded-md border border-action bg-action px-3 py-3 text-left text-base text-action-foreground',
  dataRow: 'w-full flex-row items-center justify-between gap-3 border-b border-border py-3',
  dataLabel: 'flex-1 text-sm leading-5 font-medium text-muted-foreground',
  dataValue: 'flex-1 text-right text-sm leading-5 text-foreground',
  list: 'w-full flex-1 bg-canvas',
  table: 'w-full border border-border bg-surface',
  tableRow: 'w-full flex-row border-b border-border',
  tableCell: 'flex-1 px-3 py-2 text-sm leading-5 text-foreground',
  tabRow: 'w-full flex-row flex-wrap gap-2',
  tab: 'min-h-12 rounded-md border border-border bg-surface px-3 py-3 text-sm leading-5 text-foreground',
  tabSelected: 'min-h-12 rounded-md border border-action bg-action px-3 py-3 text-sm leading-5 text-action-foreground',
  dropdown: 'w-full gap-2',
  dropdownValue: 'flex-1 text-base leading-6 text-foreground',
  dropdownChevron: 'text-lg leading-6 text-muted-foreground',
  dropdownMenu: 'w-full rounded-md border border-border bg-surface p-1 gap-1',
  dropdownOption: 'w-full rounded-md px-3 py-3 text-base leading-6 text-foreground',
  dropdownOptionSelected: 'w-full rounded-md bg-action px-3 py-3 text-base leading-6 text-action-foreground',
  ratioBar: 'w-full h-3 flex-row overflow-hidden rounded-full bg-surface-inset',
  disclosure: 'w-full rounded-xl border border-border bg-surface',
  disclosureContent: 'w-full gap-3 border-t border-border p-4',
  disclosureLabel: 'flex-1 text-base leading-6 font-semibold text-foreground',
  disclosureSummary: 'text-sm leading-5 text-muted-foreground',
  surfaceMapRow: 'w-full flex-row items-start gap-4',
  surfaceMapColumn: 'w-full flex-col gap-4',
  surfaceMapCurrent: 'flex-1 min-w-0 rounded-xl border-2 border-action bg-surface p-4 gap-2',
  surfaceMapNonCurrent: 'flex-1 min-w-0 rounded-xl border border-border bg-surface-inset p-4 gap-2',
  surfaceMapLabel: 'text-base leading-6 font-semibold text-foreground',
  surfaceMapRole: 'text-sm leading-5 font-medium text-muted-foreground',
  surfaceMapInside: 'text-sm leading-5 text-foreground',
  surfaceMapStatus: 'text-sm leading-5 font-semibold',
  surfaceMapOutside: 'text-xs leading-4 text-muted-foreground',
} as const)

export const semanticToneTokens = Object.freeze({
  neutral: Object.freeze({foreground: 'text-muted-foreground', background: 'bg-surface', border: 'border-border'}),
  ok: Object.freeze({foreground: 'text-ok-foreground', background: 'bg-ok-background', border: 'border-ok-border'}),
  warn: Object.freeze({foreground: 'text-warn-foreground', background: 'bg-warn-background', border: 'border-warn-border'}),
  error: Object.freeze({foreground: 'text-error-foreground', background: 'bg-error-background', border: 'border-error-border'}),
  info: Object.freeze({foreground: 'text-info-foreground', background: 'bg-info-background', border: 'border-info-border'}),
} as const)

export const buttonToneTokens = Object.freeze({
  neutral: Object.freeze({background: 'bg-action', foreground: 'text-action-foreground', border: 'border-action'}),
  ok: Object.freeze({background: 'bg-ok-background', foreground: 'text-ok-foreground', border: 'border-ok-border'}),
  warn: Object.freeze({background: 'bg-warn-background', foreground: 'text-warn-foreground', border: 'border-warn-border'}),
  error: Object.freeze({background: 'bg-error-background', foreground: 'text-error-foreground', border: 'border-error-border'}),
  info: Object.freeze({background: 'bg-info-background', foreground: 'text-info-foreground', border: 'border-info-border'}),
} as const)

export const baseLayout = Object.freeze({
  scrollContentGap: 12,
} as const)
