export const baseTokens = Object.freeze({
  container: 'flex-1 bg-canvas p-6 gap-4',
  containerContent: 'w-full bg-canvas gap-3',
  containerCard: 'w-11/12 max-w-xl self-center rounded-xl border border-border bg-surface p-6 gap-4',
  containerCentered: 'flex-1 items-center justify-center bg-canvas p-6 gap-4',
  text: 'text-foreground',
  heading: 'text-xl font-semibold text-foreground',
  label: 'text-sm font-medium text-muted-foreground',
  input: 'min-h-12 rounded-md border border-border bg-surface px-3 text-base text-foreground',
  button: 'self-start min-h-12 rounded-md bg-action px-4 py-3',
  buttonText: 'text-center text-base font-semibold text-action-foreground',
  keyboardKey: 'flex-1 self-stretch min-h-12 rounded-md bg-action px-2 py-2',
  keyboardAction: 'flex-1 self-stretch min-h-12 rounded-md border border-border bg-surface px-2 py-2',
  keyboardButtonText: 'text-center text-base font-semibold text-action-foreground',
  keyboardActionText: 'text-center text-base font-semibold text-foreground',
  status: 'text-sm text-muted-foreground',
  actions: 'flex-row flex-wrap items-start gap-3',
  scroll: 'w-full flex-1 bg-canvas gap-3',
} as const)
