module.exports = {
  content: [
    './src/**/*.{ts,tsx}',
    './test-expo/**/*.{ts,tsx}',
    '../../base/primitives/src/**/*.{ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        canvas: 'rgb(var(--color-canvas) / <alpha-value>)',
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-elevated': 'rgb(var(--color-surface-elevated) / <alpha-value>)',
        'surface-inset': 'rgb(var(--color-surface-inset) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
        'muted-foreground': 'rgb(var(--color-muted-foreground) / <alpha-value>)',
        border: 'rgb(var(--color-border) / <alpha-value>)',
        action: 'rgb(var(--color-action) / <alpha-value>)',
        'action-foreground': 'rgb(var(--color-action-foreground) / <alpha-value>)',
        'keyboard-surface': 'rgb(var(--color-keyboard-surface) / <alpha-value>)',
        'keyboard-key': 'rgb(var(--color-keyboard-key) / <alpha-value>)',
        'keyboard-action': 'rgb(var(--color-keyboard-action) / <alpha-value>)',
        'keyboard-key-foreground': 'rgb(var(--color-keyboard-key-foreground) / <alpha-value>)',
        'keyboard-action-foreground': 'rgb(var(--color-keyboard-action-foreground) / <alpha-value>)',
        'keyboard-border': 'rgb(var(--color-keyboard-border) / <alpha-value>)',
        'keyboard-focus': 'rgb(var(--color-keyboard-focus) / <alpha-value>)',
        focus: 'rgb(var(--color-focus) / <alpha-value>)',
        'admin-shell-surface': 'rgb(var(--color-admin-shell-surface) / <alpha-value>)',
        'admin-shell-foreground': 'rgb(var(--color-admin-shell-foreground) / <alpha-value>)',
        'admin-shell-muted': 'rgb(var(--color-admin-shell-muted) / <alpha-value>)',
        'admin-shell-border': 'rgb(var(--color-admin-shell-border) / <alpha-value>)',
        'admin-content-surface': 'rgb(var(--color-admin-content-surface) / <alpha-value>)',
        'admin-content-foreground': 'rgb(var(--color-admin-content-foreground) / <alpha-value>)',
        'admin-content-muted': 'rgb(var(--color-admin-content-muted) / <alpha-value>)',
        'admin-content-border': 'rgb(var(--color-admin-content-border) / <alpha-value>)',
        'admin-ratio-undeclared': 'rgb(var(--color-admin-ratio-undeclared) / <alpha-value>)',
        'admin-inset': 'rgb(var(--color-admin-inset) / <alpha-value>)',
        'admin-action': 'rgb(var(--color-admin-action) / <alpha-value>)',
        'admin-action-start': 'rgb(var(--color-admin-action-start) / <alpha-value>)',
        'admin-action-end': 'rgb(var(--color-admin-action-end) / <alpha-value>)',
        'admin-action-foreground': 'rgb(var(--color-admin-action-foreground) / <alpha-value>)',
        'admin-focus': 'rgb(var(--color-admin-focus) / <alpha-value>)',
        'admin-surface-current': 'rgb(var(--color-admin-surface-current) / <alpha-value>)',
        'admin-surface-noncurrent': 'rgb(var(--color-admin-surface-noncurrent) / <alpha-value>)',
        'ok-foreground': 'rgb(var(--color-ok-foreground) / <alpha-value>)',
        'ok-background': 'rgb(var(--color-ok-background) / <alpha-value>)',
        'ok-border': 'rgb(var(--color-ok-border) / <alpha-value>)',
        'warn-foreground': 'rgb(var(--color-warn-foreground) / <alpha-value>)',
        'warn-background': 'rgb(var(--color-warn-background) / <alpha-value>)',
        'warn-border': 'rgb(var(--color-warn-border) / <alpha-value>)',
        'error-foreground': 'rgb(var(--color-error-foreground) / <alpha-value>)',
        'error-background': 'rgb(var(--color-error-background) / <alpha-value>)',
        'error-border': 'rgb(var(--color-error-border) / <alpha-value>)',
        'info-foreground': 'rgb(var(--color-info-foreground) / <alpha-value>)',
        'info-background': 'rgb(var(--color-info-background) / <alpha-value>)',
        'info-border': 'rgb(var(--color-info-border) / <alpha-value>)',
        'login-surface': 'rgb(var(--color-login-surface) / <alpha-value>)',
        'login-foreground': 'rgb(var(--color-login-foreground) / <alpha-value>)',
        'login-muted': 'rgb(var(--color-login-muted) / <alpha-value>)',
        'login-border': 'rgb(var(--color-login-border) / <alpha-value>)',
        'login-inset': 'rgb(var(--color-login-inset) / <alpha-value>)',
        'login-focus': 'rgb(var(--color-login-focus) / <alpha-value>)',
        'login-action': 'rgb(var(--color-login-action) / <alpha-value>)',
        'login-action-start': 'rgb(var(--color-login-action-start) / <alpha-value>)',
        'login-action-end': 'rgb(var(--color-login-action-end) / <alpha-value>)',
        'login-action-foreground': 'rgb(var(--color-login-action-foreground) / <alpha-value>)',
        'login-icon': 'rgb(var(--color-login-icon) / <alpha-value>)',
      },
    },
  },
  plugins: [],
}
