package com.catering.v2s.organization.application.persistence;

/** SQL text fragments owned by OrganizationAssignmentCandidateService; B3 relocates text only and does not change execution. */
public final class OrganizationAssignmentCandidateServiceSql {
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_SELECT_ORGANIZATION_NODE_WORKSPACE_UUID = "SELECT id FROM organization.organization_node WHERE workspace_uuid=? AND ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_GROUP_WORKSPACE_KEY_NODE_TYPE_STATUS_ENABLED = "group_workspace_key=? AND node_type=? AND status='ENABLED' ORDER BY code";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_SELECT_ORGANIZATION_SELECT_ID_FROM_ORGANIZATION = "SELECT id FROM organization.";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_WHERE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_STATUS_ENABLED = " WHERE workspace_uuid=? AND group_workspace_key=? AND status='ENABLED' ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_ORDER_BY_CODE = "ORDER BY code";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_SELECT_COMMERCIAL_GROUP_UUID = "SELECT commercial_group_uuid, commercial_group_code || ' ' || commercial_group_name, count(*) ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_COMMERCIAL_GROUP_OVER_FROM_ORGANIZATION_COMME = "OVER() FROM organization.commercial_group ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_WHERE_GROUP_WORKSPACE_KEY_COMMERCIAL_GROUP_UUID = "WHERE group_workspace_key=? AND (?::uuid IS NULL OR commercial_group_uuid=?) ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CONDITION_COMMERCIAL_GROUP_UUID = "AND (?::uuid IS NULL OR commercial_group_uuid=?) ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CONDITION_TEXT_COMMERCIAL_GROUP_CODE_ILIKE_ESCAPE = "AND (?::text IS NULL OR commercial_group_code ILIKE ? ESCAPE '!' OR ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_COMMERCIAL_GROUP_NAME_ILIKE_ESCAPE = "commercial_group_name ILIKE ? ESCAPE '!') ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_ORDER_BY_COMMERCIAL_GROUP_CODE = "ORDER BY commercial_group_code LIMIT ? OFFSET ?";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_SELECT_HEAD_COMPANY_CODE_NAME = "SELECT id, code || ' ' || name, count(*) OVER() FROM organization.head_company ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_WHERE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_STATUS_ENABLED_ALTERNATE_A = "WHERE workspace_uuid=? AND group_workspace_key=? AND status='ENABLED' AND (?::uuid IS ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_NULL_OR_ID = "NULL OR id=?) ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CONDITION_AND_UUID_IS_NULL_OR_ID = "AND (?::uuid IS NULL OR id=?) ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CONDITION_TEXT_CODE_ILIKE_ESCAPE = "AND (?::text IS NULL OR code ILIKE ? ESCAPE '!' OR name ILIKE ? ESCAPE '!') ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_ORDER_BY_CODE_ALTERNATE_A = "ORDER BY code LIMIT ? OFFSET ?";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CTE_CANDIDATES = "WITH RECURSIVE candidates AS (";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_SELECT_ORGANIZATION_NODE_PARENT_ID_CODE_NAME = "SELECT id, parent_id, code, name FROM organization.organization_node ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_WHERE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_NODE_TYPE_STATUS = "WHERE workspace_uuid=? AND group_workspace_key=? AND node_type=? AND status='ENABLED' ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CONDITION_TEXT_CODE_ILIKE = "AND (?::uuid IS NULL OR id=?) AND (?::uuid IS NULL OR id=?) AND (?::text IS NULL OR code ILIKE ? ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_ESCAPE_NAME_ILIKE = "ESCAPE '!' OR name ILIKE ? ESCAPE '!')";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CLOSE_PAREN_ANCESTRY = "), ancestry AS (";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_SELECT_CANDIDATES_TARGET_ID_PARENT_ID_CODE = "SELECT candidates.id AS target_id, candidates.id, candidates.parent_id, candidates.code, ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CANDIDATES_NAME_DEPTH = "candidates.name, 0 AS depth FROM candidates ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_UNION_ANCESTRY_TARGET_ID_PARENT_PARENT_ID = "UNION ALL SELECT ancestry.target_id, parent.id, parent.parent_id, parent.code, parent.name, ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_ANCESTRY_DEPTH = "ancestry.depth + 1 ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_FROM_CLAUSE_ANCESTRY_PARENT_PARENT_ID = "FROM organization.organization_node parent JOIN ancestry ON ancestry.parent_id=parent.id ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_WHERE_PARENT_WORKSPACE_UUID_GROUP_WORKSPACE_KEY = "WHERE parent.workspace_uuid=? AND parent.group_workspace_key=?";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CLOSE_PAREN_PATHS = "), paths AS (";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_SELECT_TARGET_ID_STRING_AGG_NAME_CODE = "SELECT target_id, string_agg(name || ' ' || code, ' / ' ORDER BY depth DESC) AS display_path FROM ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_ANCESTRY_TARGET_ID = "ancestry GROUP BY target_id";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CLOSE_PAREN_PATHS_DISPLAY_PATH = ") SELECT candidates.id, paths.display_path, count(*) OVER() FROM candidates JOIN paths ON ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_PATHS_TARGET_ID_CANDIDATES = "paths.target_id=candidates.id ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_ORDER_BY_CANDIDATES_CODE = "ORDER BY candidates.code LIMIT ? OFFSET ?";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CTE_CANDIDATES_ALTERNATE_A = "WITH RECURSIVE candidates AS (";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_SELECT_STORE_PROJECT_ID_CODE_NAME = "SELECT store.id, store.project_id, store.code, store.name FROM organization.store store ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_WHERE_STORE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_STATUS = "WHERE store.workspace_uuid=? AND store.group_workspace_key=? AND store.status='ENABLED' ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CONDITION_STORE_TEXT_CODE_ILIKE = "AND (?::uuid IS NULL OR store.id=?) AND (?::text IS NULL OR store.code ILIKE ? ESCAPE '!' OR ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_STORE_NAME_ILIKE_ESCAPE = "store.name ILIKE ? ESCAPE '!') AND (?::uuid IS NULL OR store.id=?)";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CLOSE_PAREN_ANCESTRY_ALTERNATE_A = "), ancestry AS (";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_SELECT_CANDIDATES_TARGET_ID_PROJECT_PARENT_ID = "SELECT candidates.id AS target_id, project.id, project.parent_id, project.code, project.name, 0 AS ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CANDIDATES_DEPTH = "depth FROM candidates ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_JOIN_ORGANIZATION_NODE_PROJECT_CANDIDATES_PROJECT_ID = "JOIN organization.organization_node project ON project.id=candidates.project_id AND ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_PROJECT = "project.workspace_uuid=? AND project.group_workspace_key=? AND project.node_type='PROJECT' AND ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_PROJECT_STATUS_ENABLED = "project.status='ENABLED' ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_UNION_ANCESTRY_TARGET_ID_PARENT_PARENT_ID_ALTERNATE_A = "UNION ALL SELECT ancestry.target_id, parent.id, parent.parent_id, parent.code, parent.name, ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_ANCESTRY_DEPTH_ALTERNATE_A = "ancestry.depth + 1 ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_FROM_CLAUSE_ANCESTRY_PARENT_PARENT_ID_ALTERNATE_A = "FROM organization.organization_node parent JOIN ancestry ON ancestry.parent_id=parent.id ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_WHERE_PARENT_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_ALTERNATE_A = "WHERE parent.workspace_uuid=? AND parent.group_workspace_key=?";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CLOSE_PAREN_PATHS_ALTERNATE_A = "), paths AS (";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_SELECT_TARGET_ID_STRING_AGG_NAME_CODE_ALTERNATE_A = "SELECT target_id, string_agg(name || ' ' || code, ' / ' ORDER BY depth DESC) AS project_path FROM ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_ANCESTRY_TARGET_ID_ALTERNATE_A = "ancestry GROUP BY target_id";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_CLOSE_PAREN_CANDIDATES_PATHS_PROJECT_PATH_NAME = ") SELECT candidates.id, paths.project_path || ' / ' || candidates.name || ' ' || candidates.code, ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_COUNT_OVER = "count(*) OVER() ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_FROM_CLAUSE_PATHS_TARGET_ID_CODE = "FROM candidates JOIN paths ON paths.target_id=candidates.id ORDER BY candidates.code LIMIT ? OFFSET ";
    public static final String ORGANIZATION_ASSIGNMENT_CANDIDATE_SERVICE_PARAMETER_PLACEHOLDER = "?";
}
