package com.catering.v2s.organization.application.persistence;

/** SQL text fragments owned by StoreService; B3 relocates text only and does not change execution. */
public final class StoreServiceSql {
    public static final String STORE_SERVICE_SELECT_OPERATING_RULE_SWITCHES_TEXT = "SELECT operating_rule_switches::text FROM organization.store WHERE id=? AND workspace_uuid=? AND group_workspace_key=?";
    public static final String STORE_SERVICE_SELECT_OPERATING_RULE_SWITCHES_BATCH_PREFIX = "SELECT id, operating_rule_switches::text FROM organization.store WHERE workspace_uuid=? AND group_workspace_key=? AND id IN (";
    public static final String STORE_SERVICE_SELECT_OPERATING_RULE_SWITCHES_BATCH_SUFFIX = ")";
    public static final String STORE_SERVICE_SELECT_STORE_PROJECT_ID_TENANT_ID_BRAND_ID_CODE = "SELECT project_id, tenant_id, brand_id, code FROM organization.store WHERE id=? AND ";
    public static final String STORE_SERVICE_CONTINUATION_WORKSPACE_UUID_GROUP_WORKSPACE_KEY = "workspace_uuid=? AND group_workspace_key=?";
    public static final String STORE_SERVICE_INSERT_INTO_STORE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_PROJECT_ID_TENANT_ID = "INSERT INTO organization.store (id, workspace_uuid, group_workspace_key, project_id, tenant_id, ";
    public static final String STORE_SERVICE_CONTINUATION_BRAND_ID_HEAD_COMPANY_ID_CODE_NAME_NOTES_OPERATING_RULE = "brand_id, head_company_id, code, name, notes, operating_rule_switches, status, version, created_at_epoch_millis, ";
    public static final String STORE_SERVICE_UPDATE_UPDATED_AT_EPOCH_MILLIS_ENABLED = "updated_at_epoch_millis) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CAST(? AS JSONB), 'ENABLED', 1, ?, ?)";
    public static final String STORE_SERVICE_UPDATE_STORE_PROJECT_ID_TENANT_ID_BRAND_ID_HEAD_COMPANY_ID = "UPDATE organization.store SET project_id=?, tenant_id=?, brand_id=?, head_company_id=?, code=?, ";
    public static final String STORE_SERVICE_CONTINUATION_NAME_NOTES_OPERATING_RULE_VERSION_UPDATED_AT_EPOCH_MILLIS = "name=?, notes=?, operating_rule_switches=CAST(? AS JSONB), version=version+1, updated_at_epoch_millis=? WHERE id=? AND ";
    public static final String STORE_SERVICE_CONTINUATION_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_VERSION = "workspace_uuid=? AND group_workspace_key=? AND version=?";
    public static final String STORE_SERVICE_UPDATE_STORE_STATUS_VERSION_UPDATED_AT_EPOCH_MILLIS = "UPDATE organization.store SET status=?, version=version+1, updated_at_epoch_millis=? ";
    public static final String STORE_SERVICE_WHERE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_VERSION = "WHERE id=? AND workspace_uuid=? AND group_workspace_key=? AND version=?";
    public static final String STORE_SERVICE_CTE_REQUESTED_WORKSPACE_UUID_TEXT_GROUP_WORKSPACE_KEY = "WITH requested AS (SELECT ?::uuid AS workspace_uuid, ?::text AS group_workspace_key, ?::uuid AS";
    public static final String STORE_SERVICE_CONTINUATION_TENANT_ID_BRAND_ID_HEAD_COMPANY_ID_STORE = " tenant_id, ?::uuid AS brand_id, ?::uuid AS head_company_id) SELECT store.id,";
    public static final String STORE_SERVICE_CONTINUATION_STORE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_CODE = " store.workspace_uuid, store.group_workspace_key, store.code, store.name, NULL::varchar AS";
    public static final String STORE_SERVICE_CONTINUATION_LEGAL_NAME_VARCHAR_CREDIT_CODE_ALIAS = " legal_name, NULL::varchar AS credit_code, NULL::varchar AS alias, NULL::varchar AS remark,";
    public static final String STORE_SERVICE_CONTINUATION_STORE_NOTES_STATUS_VERSION = " store.notes, store.status, store.version, store.extension_rule_revision,";
    public static final String STORE_SERVICE_CONTINUATION_STORE_CREATED_AT_EPOCH_MILLIS_UPDATED_AT_EPOCH_MILLIS_EXTENSION_VALUES = " store.created_at_epoch_millis, store.updated_at_epoch_millis, store.extension_values::text,";
    public static final String STORE_SERVICE_CONTINUATION_STORE_PROJECT_ID_TENANT_ID_BRAND_ID = " store.project_id, store.tenant_id, store.brand_id, store.head_company_id,";
    public static final String STORE_SERVICE_OPEN_PAREN_TENANT_PROJECT_STATUS_ENABLED_PROJECT_ENABLED = " (project.status='ENABLED') AS project_enabled, EXISTS(SELECT 1 FROM organization.tenant";
    public static final String STORE_SERVICE_CONTINUATION_TENANT_REQUESTED_REQUEST_TENANT_ID = " tenant, requested request WHERE tenant.id=request.tenant_id AND";
    public static final String STORE_SERVICE_CONTINUATION_TENANT_WORKSPACE_UUID_REQUEST_GROUP_WORKSPACE_KEY = " tenant.workspace_uuid=request.workspace_uuid AND tenant.group_workspace_key=request.group_workspace_key";
    public static final String STORE_SERVICE_CONDITION_BRAND_TENANT_STATUS_ENABLED_TENANT_ENABLED = " AND tenant.status='ENABLED') AS tenant_enabled, EXISTS(SELECT 1 FROM organization.brand brand,";
    public static final String STORE_SERVICE_CONTINUATION_REQUESTED_REQUEST_BRAND_BRAND_ID = " requested request WHERE brand.id=request.brand_id AND brand.workspace_uuid=request.workspace_uuid AND";
    public static final String STORE_SERVICE_CONTINUATION_BRAND_GROUP_WORKSPACE_KEY_REQUEST_STATUS = " brand.group_workspace_key=request.group_workspace_key AND brand.status='ENABLED') AS brand_enabled,";
    public static final String STORE_SERVICE_OPEN_PAREN_HEAD_COMPANY_REQUEST_HEAD_COMPANY_ID = " (request.head_company_id IS NULL OR EXISTS(SELECT 1 FROM organization.head_company head_company";
    public static final String STORE_SERVICE_WHERE_HEAD_COMPANY_REQUEST_HEAD_COMPANY_ID_WORKSPACE_UUID = " WHERE head_company.id=request.head_company_id AND head_company.workspace_uuid=request.workspace_uuid AND";
    public static final String STORE_SERVICE_CONTINUATION_HEAD_COMPANY_GROUP_WORKSPACE_KEY_REQUEST_STATUS = " head_company.group_workspace_key=request.group_workspace_key AND head_company.status='ENABLED')) AS";
    public static final String STORE_SERVICE_CONTINUATION_HEAD_COMPANY_ENABLED_REQUEST_HEAD_COMPANY_ID = " head_company_enabled, (request.head_company_id IS NULL OR EXISTS(SELECT 1 FROM";
    public static final String STORE_SERVICE_ALTERNATIVE_HEAD_COMPANY_BRAND_AUTHORIZATION_HBA_HEAD_COMPANY_ID_REQUEST = " organization.head_company_brand_authorization hba WHERE hba.head_company_id=request.head_company_id";
    public static final String STORE_SERVICE_CONDITION_STORE_HBA_BRAND_ID_REQUEST_HEAD_COMPANY_AUTHORIZED = " AND hba.brand_id=request.brand_id)) AS head_company_authorized FROM organization.store store JOIN";
    public static final String STORE_SERVICE_ALTERNATIVE_ORGANIZATION_NODE_PROJECT_STORE_PROJECT_ID = " organization.organization_node project ON project.id=store.project_id AND";
    public static final String STORE_SERVICE_CONTINUATION_PROJECT_WORKSPACE_UUID_STORE_GROUP_WORKSPACE_KEY = " project.workspace_uuid=store.workspace_uuid AND project.group_workspace_key=store.group_workspace_key";
    public static final String STORE_SERVICE_CONDITION_REQUESTED_PROJECT_NODE_TYPE_REQUEST_STORE = " AND project.node_type='PROJECT' CROSS JOIN requested request WHERE store.id=? AND";
    public static final String STORE_SERVICE_CONTINUATION_STORE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY = " store.workspace_uuid=? AND store.group_workspace_key=?";
    public static final String STORE_SERVICE_SELECT_STORE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_CODE = "SELECT store.id, store.workspace_uuid, store.group_workspace_key, store.code, store.name, ";
    public static final String STORE_SERVICE_CONTINUATION_VARCHAR_LEGAL_NAME_CREDIT_CODE_ALIAS = "NULL::varchar AS legal_name, NULL::varchar AS credit_code, NULL::varchar AS alias, ";
    public static final String STORE_SERVICE_CONTINUATION_VARCHAR_REMARK_STORE_NOTES = "NULL::varchar AS remark, store.notes, store.status, store.version, store.extension_rule_revision, ";
    public static final String STORE_SERVICE_CONTINUATION_STORE_CREATED_AT_EPOCH_MILLIS_UPDATED_AT_EPOCH_MILLIS_EXTENSION_VALUES_ALTERNATE_A = "store.created_at_epoch_millis, store.updated_at_epoch_millis, store.extension_values::text, ";
    public static final String STORE_SERVICE_CONTINUATION_ORGANIZATION_NODE_PROJECT_ID_PROJECT = "store.project_id FROM organization.store store JOIN organization.organization_node project ON ";
    public static final String STORE_SERVICE_CONTINUATION_PROJECT_STORE_PROJECT_ID_WORKSPACE_UUID = "project.id=store.project_id AND project.workspace_uuid=store.workspace_uuid AND ";
    public static final String STORE_SERVICE_CONTINUATION_PROJECT_GROUP_WORKSPACE_KEY_STORE_NODE_TYPE = "project.group_workspace_key=store.group_workspace_key AND project.node_type='PROJECT' WHERE ";
    public static final String STORE_SERVICE_CONTINUATION_STORE_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_ALTERNATE_A = "store.id=? AND store.workspace_uuid=? AND store.group_workspace_key=?";
    public static final String STORE_SERVICE_CTE_REQUESTED_WORKSPACE_UUID_TEXT_GROUP_WORKSPACE_KEY_ALTERNATE_A = "WITH requested AS (SELECT ?::uuid AS workspace_uuid, ?::text AS group_workspace_key, ?::uuid AS";
    public static final String STORE_SERVICE_CONTINUATION_PROJECT_ID_TENANT_ID_BRAND_ID_HEAD_COMPANY_ID = " project_id, ?::uuid AS tenant_id, ?::uuid AS brand_id, ?::uuid AS head_company_id) SELECT";
    public static final String STORE_SERVICE_CONTINUATION_ORGANIZATION_NODE_NODE_REQUESTED_REQUEST_PROJECT_ID = " EXISTS(SELECT 1 FROM organization.organization_node node, requested request WHERE node.id=request.project_id";
    public static final String STORE_SERVICE_CONDITION_NODE_WORKSPACE_UUID_REQUEST_GROUP_WORKSPACE_KEY = " AND node.workspace_uuid=request.workspace_uuid AND node.group_workspace_key=request.group_workspace_key";
    public static final String STORE_SERVICE_CONDITION_NODE_NODE_TYPE_PROJECT_STATUS = " AND node.node_type='PROJECT' AND node.status='ENABLED') AS project_enabled, EXISTS(SELECT 1 FROM";
    public static final String STORE_SERVICE_ALTERNATIVE_TENANT_REQUESTED_REQUEST_TENANT_ID = " organization.tenant tenant, requested request WHERE tenant.id=request.tenant_id AND";
    public static final String STORE_SERVICE_CONTINUATION_TENANT_WORKSPACE_UUID_REQUEST_GROUP_WORKSPACE_KEY_ALTERNATE_A = " tenant.workspace_uuid=request.workspace_uuid AND tenant.group_workspace_key=request.group_workspace_key";
    public static final String STORE_SERVICE_CONDITION_BRAND_TENANT_STATUS_ENABLED_TENANT_ENABLED_ALTERNATE_A = " AND tenant.status='ENABLED') AS tenant_enabled, EXISTS(SELECT 1 FROM organization.brand brand,";
    public static final String STORE_SERVICE_CONTINUATION_REQUESTED_REQUEST_BRAND_BRAND_ID_ALTERNATE_A = " requested request WHERE brand.id=request.brand_id AND brand.workspace_uuid=request.workspace_uuid AND";
    public static final String STORE_SERVICE_CONTINUATION_BRAND_GROUP_WORKSPACE_KEY_REQUEST_STATUS_ALTERNATE_A = " brand.group_workspace_key=request.group_workspace_key AND brand.status='ENABLED') AS brand_enabled,";
    public static final String STORE_SERVICE_OPEN_PAREN_HEAD_COMPANY_REQUEST_HEAD_COMPANY_ID_ALTERNATE_A = " (request.head_company_id IS NULL OR EXISTS(SELECT 1 FROM organization.head_company head_company";
    public static final String STORE_SERVICE_WHERE_HEAD_COMPANY_REQUEST_HEAD_COMPANY_ID_WORKSPACE_UUID_ALTERNATE_A = " WHERE head_company.id=request.head_company_id AND head_company.workspace_uuid=request.workspace_uuid AND";
    public static final String STORE_SERVICE_CONTINUATION_HEAD_COMPANY_GROUP_WORKSPACE_KEY_REQUEST_STATUS_ALTERNATE_A = " head_company.group_workspace_key=request.group_workspace_key AND head_company.status='ENABLED')) AS";
    public static final String STORE_SERVICE_CONTINUATION_HEAD_COMPANY_ENABLED_REQUEST_HEAD_COMPANY_ID_ALTERNATE_A = " head_company_enabled, (request.head_company_id IS NULL OR EXISTS(SELECT 1 FROM";
    public static final String STORE_SERVICE_ALTERNATIVE_HEAD_COMPANY_BRAND_AUTHORIZATION_HBA_HEAD_COMPANY_ID_REQUEST_ALTERNATE_A = " organization.head_company_brand_authorization hba WHERE hba.head_company_id=request.head_company_id";
    public static final String STORE_SERVICE_CONDITION_REQUESTED_HBA_BRAND_ID_REQUEST_HEAD_COMPANY_AUTHORIZED = " AND hba.brand_id=request.brand_id)) AS head_company_authorized FROM requested request";
    public static final String STORE_SERVICE_UPDATE_STORE_EXTENSION_VALUES_EXTENSION_RULE_REVISION = "UPDATE organization.store SET extension_values=CAST(? AS JSONB), extension_rule_revision=? WHERE id=?";
    public static final String STORE_SERVICE_UPDATE_STORE_EXTENSION_VALUES_EXTENSION_RULE_REVISION_ALTERNATE_A = "UPDATE organization.store SET extension_values=CAST(? AS JSONB), extension_rule_revision=? WHERE id=?";
    public static final String STORE_SERVICE_UPDATE_STORE_EXTENSION_VALUES_EXTENSION_RULE_REVISION_ALTERNATE_B = "UPDATE organization.store SET extension_values=CAST(? AS JSONB), extension_rule_revision=? WHERE id=?";
    public static final String STORE_SERVICE_INSERT_INTO_AUDIT_EVENT_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_ENTITY_TYPE = "INSERT INTO organization.audit_event (id, workspace_uuid, group_workspace_key, entity_type, ";
    public static final String STORE_SERVICE_CONTINUATION_ENTITY_REF_TEXT_ACTOR_TYPE_ACTOR_ID_ACTOR_DISPLAY_SNAPSHOT = "entity_ref_text, actor_type, actor_id, actor_display_snapshot, action, ";
    public static final String STORE_SERVICE_CONTINUATION_OCCURRED_AT_EPOCH_MILLIS_CHANGES_JSON = "occurred_at_epoch_millis, changes_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CAST(? AS JSONB))";
}
