import {theme, type ThemeConfig} from 'antd';

export const platformAdminThemeProfile = {
  id: 'platform-admin-default',
  consumerFace: 'platform-admin',
  colorScheme: 'light',
  proLayoutNavTheme: 'light',
  theme: {
    algorithm: [theme.defaultAlgorithm, theme.compactAlgorithm],
    cssVar: {key: 'platform-admin', prefix: 'platform-admin'},
    components: {
      Layout: {
        headerBg: 'var(--platform-admin-color-bg-container)',
        bodyBg: 'var(--platform-admin-color-bg-layout)',
        footerBg: 'var(--platform-admin-color-bg-layout)',
        siderBg: 'var(--platform-admin-color-bg-container)',
        lightSiderBg: 'var(--platform-admin-color-bg-container)',
        lightTriggerBg: 'var(--platform-admin-color-bg-container)',
        headerColor: 'var(--platform-admin-color-text)',
        lightTriggerColor: 'var(--platform-admin-color-text)',
      },
    },
    token: {
      colorPrimary: '#5c6c85',
      colorSuccess: '#6a9955',
      colorWarning: '#dcb67a',
      colorError: '#c44e52',
      colorInfo: '#5c6c85',
      colorTextBase: '#333842',
      colorBgBase: '#f5f6f8',
      colorPrimaryBg: '#eaecef',
      colorPrimaryBgHover: '#dfe3ea',
      colorPrimaryBorder: '#c9ced6',
      colorPrimaryBorderHover: '#aeb4bf',
      colorPrimaryHover: '#6f7f99',
      colorPrimaryActive: '#4b586e',
      colorPrimaryText: '#5c6c85',
      colorPrimaryTextHover: '#6f7f99',
      colorPrimaryTextActive: '#4b586e',
      colorSuccessBg: '#f2f6ef',
      colorSuccessText: '#6a9955',
      colorWarningBg: '#fbf6ed',
      colorWarningText: '#dcb67a',
      colorErrorBg: '#f9ecec',
      colorErrorText: '#c44e52',
      colorInfoBg: '#eaecef',
      colorInfoText: '#5c6c85',
      colorText: 'rgba(51, 56, 66, 0.85)',
      colorTextSecondary: 'rgba(51, 56, 66, 0.65)',
      colorTextTertiary: 'rgba(51, 56, 66, 0.45)',
      colorTextQuaternary: 'rgba(51, 56, 66, 0.25)',
      colorTextDisabled: 'rgba(51, 56, 66, 0.25)',
      colorBgContainer: '#ffffff',
      colorBgElevated: '#ffffff',
      colorBgLayout: '#f5f6f8',
      colorBgSpotlight: 'rgba(51, 56, 66, 0.85)',
      colorBgMask: 'rgba(51, 56, 66, 0.35)',
      colorBorder: '#e4e6eb',
      colorBorderSecondary: '#f0f2f5',
      borderRadius: 4,
      borderRadiusXS: 2,
      borderRadiusSM: 3,
      borderRadiusLG: 6,
      padding: 16,
      paddingSM: 12,
      paddingLG: 20,
      margin: 16,
      marginSM: 12,
      marginLG: 20,
      boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.05)',
      boxShadowSecondary: '0 2px 6px 0 rgba(0, 0, 0, 0.08)',
    },
  } satisfies ThemeConfig,
} as const;

export const platformAdminTheme = platformAdminThemeProfile.theme;
export const platformAdminChromeProps = {
  'data-chrome-profile': platformAdminThemeProfile.id,
  'data-consumer-face': platformAdminThemeProfile.consumerFace,
} as const;
