import {theme, type ThemeConfig} from 'antd';

export const platformAdminThemeProfile = {
  id: 'platform-admin-default',
  consumerFace: 'platform-admin',
  colorScheme: 'light',
  proLayoutNavTheme: 'light',
  theme: {
    algorithm: [theme.defaultAlgorithm, theme.compactAlgorithm],
    cssVar: {key: 'platform-admin', prefix: 'platform-admin'},
    components: {
      Layout: {
        headerBg: 'var(--platform-admin-color-bg-container)',
        bodyBg: 'var(--platform-admin-color-bg-layout)',
        footerBg: 'var(--platform-admin-color-bg-layout)',
        siderBg: 'var(--platform-admin-color-bg-container)',
        lightSiderBg: 'var(--platform-admin-color-bg-container)',
        lightTriggerBg: 'var(--platform-admin-color-bg-container)',
        headerColor: 'var(--platform-admin-color-text)',
        lightTriggerColor: 'var(--platform-admin-color-text)',
      },
    },
    token: {
      colorPrimary: '#83b198',
      colorSuccess: '#73a980',
      colorWarning: '#e6b97e',
      colorError: '#d98880',
      colorInfo: '#8ca8b8',
      colorTextBase: '#4a5a52',
      colorBgBase: '#f8f9f7',
      colorPrimaryBg: '#f0f6f3',
      colorPrimaryBgHover: '#dceadc',
      colorPrimaryBorder: '#b8d4c4',
      colorPrimaryBorderHover: '#9ac1a8',
      colorPrimaryHover: '#98c0aa',
      colorPrimaryActive: '#6e997f',
      colorPrimaryText: '#83b198',
      colorPrimaryTextHover: '#98c0aa',
      colorPrimaryTextActive: '#6e997f',
      colorSuccessBg: '#f3f8f4',
      colorSuccessBgHover: '#e0efe3',
      colorSuccessBorder: '#b2d8bc',
      colorSuccessBorderHover: '#8ec09a',
      colorSuccessHover: '#83b991',
      colorSuccessActive: '#5a8c67',
      colorSuccessText: '#73a980',
      colorSuccessTextHover: '#83b991',
      colorSuccessTextActive: '#5a8c67',
      colorWarningBg: '#fef9f0',
      colorWarningBgHover: '#fceecd',
      colorWarningBorder: '#f4d7a2',
      colorWarningBorderHover: '#eec278',
      colorWarningHover: '#ebc68d',
      colorWarningActive: '#c99b4a',
      colorWarningText: '#e6b97e',
      colorWarningTextHover: '#ebc68d',
      colorWarningTextActive: '#c99b4a',
      colorErrorBg: '#fbf2f2',
      colorErrorBgHover: '#f7e0e0',
      colorErrorBorder: '#e8b8b8',
      colorErrorBorderHover: '#df9e9e',
      colorErrorHover: '#e69f9f',
      colorErrorActive: '#c46b6b',
      colorErrorText: '#d98880',
      colorErrorTextHover: '#e69f9f',
      colorErrorTextActive: '#c46b6b',
      colorInfoBg: '#f2f6f8',
      colorInfoBgHover: '#e1e9ef',
      colorInfoBorder: '#b8c9d4',
      colorInfoBorderHover: '#9bb1c2',
      colorInfoHover: '#9eb6c4',
      colorInfoActive: '#6e8b9c',
      colorInfoText: '#8ca8b8',
      colorInfoTextHover: '#9eb6c4',
      colorInfoTextActive: '#6e8b9c',
      colorText: 'rgba(74, 90, 82, 0.85)',
      colorTextSecondary: 'rgba(74, 90, 82, 0.65)',
      colorTextTertiary: 'rgba(74, 90, 82, 0.45)',
      colorTextQuaternary: 'rgba(74, 90, 82, 0.25)',
      colorTextDisabled: 'rgba(74, 90, 82, 0.25)',
      colorBgContainer: '#ffffff',
      colorBgElevated: '#ffffff',
      colorBgLayout: '#f8f9f7',
      colorBgSpotlight: 'rgba(74, 90, 82, 0.85)',
      colorBgMask: 'rgba(74, 90, 82, 0.15)',
      colorBorder: '#e8ebea',
      colorBorderSecondary: '#f0f2f1',
      borderRadius: 8,
      borderRadiusXS: 2,
      borderRadiusSM: 4,
      borderRadiusLG: 12,
      padding: 16,
      paddingSM: 12,
      paddingLG: 24,
      margin: 16,
      marginSM: 12,
      marginLG: 24,
      boxShadow: '0 2px 10px 0 rgba(100, 120, 110, 0.06)',
      boxShadowSecondary: '0 4px 16px 0 rgba(100, 120, 110, 0.08)',
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      fontSize: 14,
    },
  } satisfies ThemeConfig,
} as const;

export const platformAdminTheme = platformAdminThemeProfile.theme;
export const platformAdminChromeProps = {
  'data-chrome-profile': platformAdminThemeProfile.id,
  'data-consumer-face': platformAdminThemeProfile.consumerFace,
} as const;
