export const storeTerminalTestIds = {
  page: 'operations-store-terminal-page',
  list: 'operations-store-terminal-list',
  listItem: (ref: string) => `operations-store-terminal-list-item-${ref}`,
  detail: 'operations-store-terminal-detail',
  create: 'operations-store-terminal-create',
  listRetry: 'operations-store-terminal-list-retry',
  edit: 'operations-store-terminal-edit',
  detailRetry: 'operations-store-terminal-detail-retry',
  actionMenu: 'operations-store-terminal-actions',
  formDrawer: 'operations-store-terminal-form',
  formStep: 'operations-store-terminal-form-step',
  formSections: 'operations-store-terminal-form-sections',
  formSection: (section: string) => `operations-store-terminal-form-section-${section}`,
  name: 'operations-store-terminal-name',
  deviceType: 'operations-store-terminal-device-type',
  deviceTypeOption: (deviceType: string) => `operations-store-terminal-device-type-${deviceType.toLowerCase()}`,
  activationCode: 'operations-store-terminal-activation-code',
  activationCodeClear: 'operations-store-terminal-activation-code-clear',
  formNext: 'operations-store-terminal-form-next',
  formBack: 'operations-store-terminal-form-back',
  formSave: 'operations-store-terminal-form-save',
  formCancel: 'operations-store-terminal-form-cancel',
  formSectionNav: (section: string) => `operations-store-terminal-form-section-nav-${section}`,
  dirtyGuardConfirm: 'operations-store-terminal-dirty-guard-confirm',
  dirtyGuardCancel: 'operations-store-terminal-dirty-guard-cancel',
  statusModal: 'operations-store-terminal-status-modal',
  statusConfirm: 'operations-store-terminal-status-confirm',
  statusCancel: 'operations-store-terminal-status-cancel',
  statusProblem: 'operations-store-terminal-status-problem',
  statusAction: (status: string) => `operations-store-terminal-status-action-${status.toLowerCase()}`,
  printer: (identity: string) => `operations-store-terminal-printer-${identity}`,
  printerAdd: 'operations-store-terminal-printer-add',
  printerRemove: (identity: string) => `operations-store-terminal-printer-remove-${identity}`,
  printerRemoveConfirm: (identity: string) => `operations-store-terminal-printer-remove-confirm-${identity}`,
  printerRemoveCancel: (identity: string) => `operations-store-terminal-printer-remove-cancel-${identity}`,
  printerName: (identity: string) => `operations-store-terminal-printer-name-${identity}`,
  printerBrand: (identity: string) => `operations-store-terminal-printer-brand-${identity}`,
  printerModel: (identity: string) => `operations-store-terminal-printer-model-${identity}`,
  printerPaperSpec: (identity: string) => `operations-store-terminal-printer-paper-${identity}`,
  printerConnection: (identity: string) => `operations-store-terminal-printer-connection-${identity}`,
  printerParameter: (identity: string) => `operations-store-terminal-printer-parameter-${identity}`,
  function: (identity: string) => `operations-store-terminal-function-${identity}`,
  functionList: 'operations-store-terminal-function-list',
  functionNav: (identity: string) => `operations-store-terminal-function-nav-${identity}`,
  functionSelect: (identity: string) => `operations-store-terminal-function-select-${identity}`,
  functionRemove: (identity: string) => `operations-store-terminal-function-remove-${identity}`,
  functionChangeConfirm: (identity: string) => `operations-store-terminal-function-change-confirm-${identity}`,
  functionChangeCancel: (identity: string) => `operations-store-terminal-function-change-cancel-${identity}`,
  functionAdd: 'operations-store-terminal-function-add',
  rangeGroup: (identity: string) => `operations-store-terminal-range-${identity}`,
  rangeOption: (identity: string, rangeKey: string) =>
    `operations-store-terminal-range-${identity}-${rangeKey.toLowerCase()}`,
  areaCandidates: (identity: string) => `operations-store-terminal-area-candidates-${identity}`,
  tagCandidates: (identity: string) => `operations-store-terminal-tag-candidates-${identity}`,
  areaCandidatesRetry: (identity: string) => `operations-store-terminal-area-candidates-retry-${identity}`,
  tagCandidatesRetry: (identity: string) => `operations-store-terminal-tag-candidates-retry-${identity}`,
  scenePicker: (identity: string) => `operations-store-terminal-scene-picker-${identity}`,
  scene: (functionIdentity: string, sceneKey: string) =>
    `operations-store-terminal-scene-${functionIdentity}-${sceneKey.toLowerCase()}`,
  sceneToggle: (functionIdentity: string, sceneKey: string) =>
    `operations-store-terminal-scene-toggle-${functionIdentity}-${sceneKey.toLowerCase()}`,
  sceneOrderTypes: (functionIdentity: string, sceneKey: string) =>
    `operations-store-terminal-scene-order-types-${functionIdentity}-${sceneKey.toLowerCase()}`,
  sceneOrderType: (functionIdentity: string, sceneKey: string, orderType: string) =>
    `operations-store-terminal-scene-order-type-${functionIdentity}-${sceneKey.toLowerCase()}-${orderType.toLowerCase()}`,
  scenePrinters: (functionIdentity: string, sceneKey: string) =>
    `operations-store-terminal-scene-printers-${functionIdentity}-${sceneKey.toLowerCase()}`,
  pagination: 'operations-store-terminal-pagination',
} as const;
