const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9_-]+/g, '-');

export const salesMenuTestIds = {
  page: 'sales-menu-page',
  channelCards: 'sales-menu-channel-cards',
  channelCard: (channelRef: string) => `sales-menu-channel-${slug(channelRef)}`,
  mode: (mode: string) => `sales-menu-mode-${slug(mode)}`,
  menuSelector: 'sales-menu-selector',
  menuManager: 'sales-menu-manager',
  sectionList: 'sales-menu-section-list',
  itemTable: 'sales-menu-item-table',
  operationLog: 'sales-menu-operation-log',
  candidateDrawer: 'sales-menu-candidate-drawer',
  candidateCategoryTree: 'sales-menu-candidate-category-tree',
  itemEditor: 'sales-menu-item-editor',
  itemMediaMode: 'sales-menu-item-media-mode',
  itemDisplayName: 'sales-menu-item-display-name',
  itemListedPrice: 'sales-menu-item-listed-price',
  itemMediaEditor: 'sales-menu-item-media-editor',
  itemMediaUpload: 'sales-menu-item-media-upload',
  itemMediaList: 'sales-menu-item-media-list',
  itemMedia: (identity: string, action: string) => `sales-menu-item-media-${slug(identity)}-${slug(action)}`,
  modes: 'sales-menu-modes',
  itemDetail: 'sales-menu-item-detail',
  publishDrawer: 'sales-menu-publish-drawer',
  scheduleDrawer: 'sales-menu-schedule-drawer',
  pageCursor: 'sales-menu-page-pagination',
  selectorCursor: 'sales-menu-selector-pagination',
  managerCursor: 'sales-menu-manager-pagination',
  candidateCursor: 'sales-menu-candidate-pagination',
  draftCursor: 'sales-menu-draft-pagination',
  publishedCursor: 'sales-menu-published-pagination',
  logCursor: 'sales-menu-log-pagination',
  section: (sectionRef: string) => `sales-menu-section-${slug(sectionRef)}`,
  item: (itemRef: string) => `sales-menu-item-${slug(itemRef)}`,
  itemAction: (itemRef: string, action: string) => `sales-menu-item-${slug(itemRef)}-${slug(action)}`,
} as const;
