const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9_-]+/g, '-');

export const salesMenuTestIds = {
  page: 'sales-menu-page',
  feedback: 'sales-menu-feedback',
  channelCards: 'sales-menu-channel-cards',
  channelCard: (channelRef: string) => `sales-menu-channel-${slug(channelRef)}`,
  mode: (mode: string) => `sales-menu-mode-${slug(mode)}`,
  menuSchedule: 'sales-menu-menu-schedule',
  menuPublish: 'sales-menu-menu-publish',
  menuOption: (menuRef: string) => `sales-menu-option-${slug(menuRef)}`,
  managerOpen: 'sales-menu-manager-open',
  managerAction: (menuRef: string, action: string) => `sales-menu-manager-${slug(menuRef)}-action-${slug(action)}`,
  menuCreate: 'sales-menu-menu-create',
  menuSelector: 'sales-menu-selector',
  menuSelectorInput: 'sales-menu-selector-input',
  managerSearch: 'sales-menu-manager-search',
  candidateSearch: 'sales-menu-candidate-search',
  menuManager: 'sales-menu-manager',
  candidateList: 'sales-menu-candidate-list',
  managerList: 'sales-menu-manager-list',
  draftList: 'sales-menu-draft-list',
  publishedList: 'sales-menu-published-list',
  operationList: 'sales-menu-operation-list',
  sectionList: 'sales-menu-section-list',
  itemTable: 'sales-menu-item-table',
  operationLog: 'sales-menu-operation-log',
  candidateDrawer: 'sales-menu-candidate-drawer',
  candidateCategoryTree: 'sales-menu-candidate-category-tree',
  candidateAdd: 'sales-menu-candidate-add',
  candidateSubmit: 'sales-menu-candidate-submit',
  itemEditor: 'sales-menu-item-editor',
  itemDelete: 'sales-menu-item-delete',
  itemClose: 'sales-menu-item-close',
  itemDiscardConfirm: 'sales-menu-item-discard-confirm',
  itemDiscardCancel: 'sales-menu-item-discard-cancel',
  itemSave: 'sales-menu-item-save',
  itemMediaMode: 'sales-menu-item-media-mode',
  itemDisplayName: 'sales-menu-item-display-name',
  itemListedPrice: 'sales-menu-item-listed-price',
  itemMediaEditor: 'sales-menu-item-media-editor',
  itemMediaUpload: 'sales-menu-item-media-upload',
  itemMediaList: 'sales-menu-item-media-list',
  itemMedia: (identity: string, action: string) => `sales-menu-item-media-${slug(identity)}-${slug(action)}`,
  modes: 'sales-menu-modes',
  itemDetail: 'sales-menu-item-detail',
  publishDrawer: 'sales-menu-publish-drawer',
  scheduleDrawer: 'sales-menu-schedule-drawer',
  scheduleKind: (kind: string) => `sales-menu-schedule-kind-${slug(kind)}`,
  scheduleStart: 'sales-menu-schedule-start',
  scheduleEnd: 'sales-menu-schedule-end',
  scheduleSave: 'sales-menu-schedule-save',
  publishSubmit: 'sales-menu-publish-submit',
  menuCreateDrawer: 'sales-menu-menu-create-drawer',
  menuCreateName: 'sales-menu-menu-create-name',
  menuCreateSubmit: 'sales-menu-menu-create-submit',
  menuRenameDrawer: 'sales-menu-menu-rename-drawer',
  menuRenameName: 'sales-menu-menu-rename-name',
  menuRenameSubmit: 'sales-menu-menu-rename-submit',
  sectionCreate: 'sales-menu-section-create',
  sectionName: 'sales-menu-section-name',
  sectionSave: 'sales-menu-section-save',
  confirmationSubmit: 'sales-menu-confirmation-submit',
  statusAction: (identity: string) => `sales-menu-status-action-${slug(identity)}`,
  statusChoice: (status: string) => `sales-menu-status-choice-${slug(status)}`,
  statusReason: 'sales-menu-status-reason',
  statusSubmit: 'sales-menu-status-submit',
  pageCursor: 'sales-menu-page-pagination',
  selectorCursor: 'sales-menu-selector-pagination',
  managerCursor: 'sales-menu-manager-pagination',
  candidateCursor: 'sales-menu-candidate-pagination',
  draftCursor: 'sales-menu-draft-pagination',
  publishedCursor: 'sales-menu-published-pagination',
  logCursor: 'sales-menu-log-pagination',
  section: (sectionRef: string) => `sales-menu-section-${slug(sectionRef)}`,
  sectionAction: (sectionRef: string) => `sales-menu-section-${slug(sectionRef)}-action`,
  sectionMenuAction: (sectionRef: string, action: string) =>
    `sales-menu-section-${slug(sectionRef)}-menu-${slug(action)}`,
  candidateRow: (candidateRef: string) => `sales-menu-candidate-${slug(candidateRef)}`,
  itemMediaChoice: (mode: string) => `sales-menu-item-media-choice-${slug(mode)}`,
  item: (itemRef: string) => `sales-menu-item-${slug(itemRef)}`,
  itemAction: (itemRef: string, action: string) => `sales-menu-item-${slug(itemRef)}-${slug(action)}`,
  itemMenuAction: (itemRef: string, action: string) => `sales-menu-item-${slug(itemRef)}-menu-${slug(action)}`,
} as const;
