
package com.catering.v2s.platform.asset.application.persistence;

/** SQL fragments used by the typed platform-asset persistence boundary. */
public final class PlatformAssetServiceSql {
    public static final String PARAMETER_PLACEHOLDER = "?";
    public static final String PLACEHOLDER_SEPARATOR = ",";
    public static final String PLATFORM_ASSET_SERVICE_INSERT_INTO_STAGED_ASSET_ASSET_REF_USAGE_WORKSPACE_UUID = "INSERT INTO platform_asset.staged_asset (asset_ref, usage, workspace_uuid, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_GROUP_WORKSPACE_KEY_STORAGE_KEY_BUCKET_NAME_OBJECT_KEY = "group_workspace_key, storage_key, bucket_name, object_key, content_type, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_SIZE_BYTES = "size_bytes, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_SHA256_STATUS_CREATED_AT_EPOCH_MILLIS_VERSION = "sha256, status, created_at_epoch_millis, version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ";
    public static final String PLATFORM_ASSET_SERVICE_PARAMETER_PLACEHOLDER = "?, ?, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_STAGED = "'STAGED', ?, 1)";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_STAGED_ASSET_STATUS_RELEASED_RELEASED_AT_EPOCH_MILLIS = "UPDATE platform_asset.staged_asset SET status='RELEASED', released_at_epoch_millis=?, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_VERSION_ASSET_REF_USAGE_STATUS = "version=version+1 WHERE asset_ref=? AND usage=? AND status='STAGED' AND version=? ";
    public static final String PLATFORM_ASSET_SERVICE_CONDITION_WORKSPACE_UUID_GROUP_WORKSPACE_KEY = "AND workspace_uuid=? AND group_workspace_key=?";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_ASSET_BIND_GRANT_CONSUMED_AT_EPOCH_MILLIS = "UPDATE platform_asset.asset_bind_grant g SET consumed_at_epoch_millis=? FROM ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_PLATFORM_ASSET_STAGED_ASSET_ASSET_REF = "platform_asset.staged_asset a WHERE g.asset_ref=? AND a.asset_ref=g.asset_ref ";
    public static final String PLATFORM_ASSET_SERVICE_CONDITION_STATUS_STAGED_USAGE_WORKSPACE_UUID = "AND a.status='STAGED' AND a.usage=? AND a.workspace_uuid=? AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_GROUP_WORKSPACE_KEY_CONSUMED_AT_EPOCH_MILLIS = "a.group_workspace_key=? AND g.consumed_at_epoch_millis IS NULL ";
    public static final String PLATFORM_ASSET_SERVICE_CONDITION_EXPIRES_AT_EPOCH_MILLIS_GRANT_HASH = "AND g.expires_at_epoch_millis>=? AND g.grant_hash=?";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_ASSET_BIND_GRANT_CONSUMED_AT_EPOCH_MILLIS_ALTERNATE_A = "UPDATE platform_asset.asset_bind_grant g SET consumed_at_epoch_millis=? FROM ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_PLATFORM_ASSET_STAGED_ASSET_ASSET_REF_ALTERNATE_A = "platform_asset.staged_asset a WHERE g.asset_ref=? AND a.asset_ref=g.asset_ref AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_STATUS_STAGED_USAGE_GROUP_WORKSPACE_LOGO = "a.status='STAGED' AND a.usage='GROUP_WORKSPACE_LOGO' AND g.consumed_at_epoch_millis IS NULL ";
    public static final String PLATFORM_ASSET_SERVICE_CONDITION = "AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_EXPIRES_AT_EPOCH_MILLIS_GRANT_HASH = "g.expires_at_epoch_millis>=? AND g.grant_hash=?";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_STAGED_ASSET_WORKSPACE_UUID_GROUP_WORKSPACE_KEY_STATUS_ACTIVE = "UPDATE platform_asset.staged_asset SET workspace_uuid=?, group_workspace_key=?, status='ACTIVE', ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_CLAIMED_BY_TYPE = "claimed_by_type='GROUP_WORKSPACE_LOGO', claimed_by_id=?, activated_at_epoch_millis=?, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_VERSION_ASSET_REF_STATUS_STAGED = "version=version+1 WHERE asset_ref=? AND status='STAGED'";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_ASSET_BIND_GRANT_CONSUMED_AT_EPOCH_MILLIS_ALTERNATE_B = "UPDATE platform_asset.asset_bind_grant g SET consumed_at_epoch_millis=? FROM ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_PLATFORM_ASSET_STAGED_ASSET_ASSET_REF_ALTERNATE_B = "platform_asset.staged_asset a WHERE g.asset_ref=? AND a.asset_ref=g.asset_ref AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_USAGE_CATALOG_ITEM_IMAGE_STATUS_STAGED = "a.usage='CATALOG_ITEM_IMAGE' AND a.status='STAGED' AND a.workspace_uuid=? AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_GROUP_WORKSPACE_KEY_CONSUMED_AT_EPOCH_MILLIS_ALTERNATE_A = "a.group_workspace_key=? AND g.consumed_at_epoch_millis IS NULL AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_EXPIRES_AT_EPOCH_MILLIS = "g.expires_at_epoch_millis>=? ";
    public static final String PLATFORM_ASSET_SERVICE_CONDITION_GRANT_HASH = "AND g.grant_hash=?";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_STAGED_ASSET_STATUS_ACTIVE_CLAIMED_BY_TYPE_CATALOG_ITEM_IMAGE = "UPDATE platform_asset.staged_asset SET status='ACTIVE', claimed_by_type='CATALOG_ITEM_IMAGE', ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_CLAIMED_BY_ID_ACTIVATED_AT_EPOCH_MILLIS_VERSION_ASSET_REF = "claimed_by_id=?, activated_at_epoch_millis=?, version=version+1 WHERE asset_ref=? AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_USAGE_CATALOG_ITEM_IMAGE_STATUS_STAGED_ALTERNATE_A = "usage='CATALOG_ITEM_IMAGE' AND status='STAGED' AND workspace_uuid=? AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_GROUP_WORKSPACE_KEY_ASSET_REF_USAGE_STATUS = "group_workspace_key=? RETURNING asset_ref, usage, status, version, size_bytes";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_STAGED_ASSET_STATUS_RELEASED_RELEASED_AT_EPOCH_MILLIS_ALTERNATE_A = "UPDATE platform_asset.staged_asset SET status='RELEASED', released_at_epoch_millis=?, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_VERSION_ASSET_REF_CLAIMED_BY_ID_STATUS = "version=version+1 WHERE asset_ref=? AND claimed_by_id=? AND status='ACTIVE'";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_STAGED_ASSET_STATUS_RELEASED_RELEASED_AT_EPOCH_MILLIS_ALTERNATE_B = "UPDATE platform_asset.staged_asset a SET status='RELEASED', released_at_epoch_millis=?, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_VERSION_ASSET_REF_STATUS_STAGED_ALTERNATE_A = "version=version+1 WHERE a.asset_ref=? AND a.status='STAGED' AND EXISTS (SELECT 1 FROM ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_PLATFORM_ASSET_ASSET_BIND_GRANT_ASSET_REF = "platform_asset.asset_bind_grant g WHERE g.asset_ref=a.asset_ref AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_CONSUMED_AT_EPOCH_MILLIS = "g.consumed_at_epoch_millis ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_EXPIRES_AT_EPOCH_MILLIS_GRANT_HASH_ALTERNATE_A = "IS NULL AND g.expires_at_epoch_millis>=? AND g.grant_hash=?)";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_ASSET_BIND_GRANT_CONSUMED_AT_EPOCH_MILLIS_ASSET_REF = "UPDATE platform_asset.asset_bind_grant SET consumed_at_epoch_millis=? WHERE asset_ref=? AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_CONSUMED_AT_EPOCH_MILLIS_GRANT_HASH = "consumed_at_epoch_millis IS NULL AND grant_hash=?";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_STAGED_ASSET_STATUS_RELEASED_RELEASED_AT_EPOCH_MILLIS_ALTERNATE_C = "UPDATE platform_asset.staged_asset SET status='RELEASED', released_at_epoch_millis=?, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_VERSION_ASSET_REF_USAGE_CATALOG_ITEM_IMAGE = "version=version+1 WHERE asset_ref=? AND usage='CATALOG_ITEM_IMAGE' AND status='STAGED' AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_VERSION_WORKSPACE_UUID_GROUP_WORKSPACE_KEY = "version=? AND workspace_uuid=? AND group_workspace_key=?";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_STAGED_ASSET_STATUS_RELEASED_RELEASED_AT_EPOCH_MILLIS_ALTERNATE_D = "UPDATE platform_asset.staged_asset SET status='RELEASED', released_at_epoch_millis=?, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_VERSION_ASSET_REF_USAGE_CATALOG_ITEM_IMAGE_ALTERNATE_A = "version=version+1 WHERE asset_ref=? AND usage='CATALOG_ITEM_IMAGE' AND status='ACTIVE' ";
    public static final String PLATFORM_ASSET_SERVICE_CONDITION_ALTERNATE_A = "AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_VERSION_WORKSPACE_UUID = "version=? AND workspace_uuid=?";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_STAGED_ASSET_STATUS_RELEASED_RELEASED_AT_EPOCH_MILLIS_ALTERNATE_E = "UPDATE platform_asset.staged_asset SET status='RELEASED', released_at_epoch_millis=?, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_VERSION_ASSET_REF_USAGE_CATALOG_ITEM_IMAGE_ALTERNATE_B = "version=version+1 WHERE asset_ref=? AND usage='CATALOG_ITEM_IMAGE' AND status='ACTIVE' ";
    public static final String PLATFORM_ASSET_SERVICE_CONDITION_ALTERNATE_B = "AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_VERSION_WORKSPACE_UUID_ALTERNATE_A = "version=? AND workspace_uuid=?";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_PG_ADVISORY_XACT_LOCK = "SELECT pg_advisory_xact_lock(?, ?)";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_STAGED_ASSET_ASSET_REF_USAGE_STATUS_VERSION = "SELECT asset_ref, usage, status, version, size_bytes FROM platform_asset.staged_asset WHERE ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_ASSET_REF = "asset_ref=?";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_ASSET_REF_OBJECT_KEY_CONTENT_TYPE_SHA256 = "SELECT asset_ref, object_key, content_type, sha256, usage, status, version, size_bytes ";
    public static final String PLATFORM_ASSET_SERVICE_FROM_CLAUSE_STAGED_ASSET_USAGE_SALES_MENU_ITEM_IMAGE_STATUS_ACTIVE = "FROM platform_asset.staged_asset WHERE usage='SALES_MENU_ITEM_IMAGE' AND status='ACTIVE' ";
    public static final String PLATFORM_ASSET_SERVICE_CONDITION_ASSET_REF = "AND asset_ref IN (";
    public static final String PLATFORM_ASSET_SERVICE_CLOSE_PAREN = ")";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_STAGED_ASSET_ASSET_REF_USAGE_STATUS_VERSION_ALTERNATE_A = "SELECT asset_ref, usage, status, version, size_bytes FROM platform_asset.staged_asset WHERE ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_ASSET_REF_USAGE_CATALOG_ITEM_IMAGE_WORKSPACE_UUID = "asset_ref=? AND usage='CATALOG_ITEM_IMAGE' AND workspace_uuid=?";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_STAGED_ASSET_OBJECT_KEY_CONTENT_TYPE_SHA256_ASSET_REF = "SELECT object_key, content_type, sha256 FROM platform_asset.staged_asset WHERE asset_ref=? AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_STATUS_ACTIVE = "status='ACTIVE'";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_STAGED_ASSET_ASSET_REF_OBJECT_KEY_CONTENT_TYPE_SHA256 = "SELECT asset_ref, object_key, content_type, sha256 FROM platform_asset.staged_asset WHERE ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_STATUS_ACTIVE_ASSET_REF = "status='ACTIVE' AND asset_ref IN (";
    public static final String PLATFORM_ASSET_SERVICE_CLOSE_PAREN_ALTERNATE_A = ")";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_STAGED_ASSET_BUCKET_NAME_OBJECT_KEY = "SELECT EXISTS(SELECT 1 FROM platform_asset.staged_asset WHERE bucket_name=? AND object_key=?)";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_ASSET_REF_USAGE_STATUS_VERSION = "SELECT asset_ref, usage, status, version, content_type, size_bytes, sha256 ";
    public static final String PLATFORM_ASSET_SERVICE_FROM_CLAUSE_STAGED_ASSET_FROM_PLATFORM_ASSET_STAGED_A = "FROM platform_asset.staged_asset ";
    public static final String PLATFORM_ASSET_SERVICE_WHERE_WORKSPACE_UUID_STORAGE_KEY_USAGE_CATALOG_ITEM_IMAGE = "WHERE workspace_uuid=? AND storage_key=? AND usage='CATALOG_ITEM_IMAGE'";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_STAGED_ASSET_STATUS_STAGED_CLAIMED_BY_TYPE_CLAIMED_BY_ID = "UPDATE platform_asset.staged_asset SET status='STAGED', claimed_by_type=NULL, claimed_by_id=NULL, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_ACTIVATED_AT_EPOCH_MILLIS_RELEASED_AT_EPOCH_MILLIS_VERSION = "activated_at_epoch_millis=NULL, released_at_epoch_millis=NULL, version=version+1 WHERE ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_ASSET_REF_USAGE_CATALOG_ITEM_IMAGE_STATUS = "asset_ref=? AND usage='CATALOG_ITEM_IMAGE' AND status='RELEASED' AND workspace_uuid=? AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_CONTENT_TYPE_SIZE_BYTES_SHA256 = "content_type=? AND size_bytes=? AND sha256=?";
    public static final String PLATFORM_ASSET_SERVICE_INSERT_INTO_ASSET_BIND_GRANT_ASSET_REF_GRANT_HASH_EXPIRES_AT_EPOCH_MILLIS = "INSERT INTO platform_asset.asset_bind_grant (asset_ref, grant_hash, expires_at_epoch_millis, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_SET_CONSUMED_AT_EPOCH_MILLIS_ASSET_REF = "consumed_at_epoch_millis) VALUES (?, ?, ?, NULL) ON CONFLICT (asset_ref) DO UPDATE SET ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_GRANT_HASH_EXPIRES_AT_EPOCH_MILLIS = "grant_hash=EXCLUDED.grant_hash, expires_at_epoch_millis=EXCLUDED.expires_at_epoch_millis, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_CONSUMED_AT_EPOCH_MILLIS_ALTERNATE_A = "consumed_at_epoch_millis=NULL";
    public static final String PLATFORM_ASSET_SERVICE_INSERT_INTO_SALES_MENU_ASSET_TARGET_ASSET_REF_WORKSPACE_UUID = "INSERT INTO platform_asset.sales_menu_asset_target (asset_ref, workspace_uuid, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_GROUP_WORKSPACE_KEY_STORE_REF_SALES_MENU_REF_SALES_ITEM_REF = "group_workspace_key, store_ref, sales_menu_ref, sales_item_ref, usage, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_EXPECTED_DRAFT_VERSION_CREATED_AT_EPOCH_MILLIS = "expected_draft_version, created_at_epoch_millis) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_ASSET_REF_USAGE_ASSET_USAGE_STATUS = "SELECT a.asset_ref AS asset_ref, a.usage AS asset_usage, a.status AS asset_status, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_VERSION_ASSET_VERSION_WORKSPACE_UUID_ASSET_WORKSPACE_UUID = "a.version AS asset_version, a.workspace_uuid AS asset_workspace_uuid, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_GROUP_WORKSPACE_KEY = "a.group_workspace_key AS asset_group_workspace_key, a.size_bytes AS asset_size_bytes, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_RELEASED_AT_EPOCH_MILLIS_ASSET_RELEASED_AT = "a.released_at_epoch_millis AS asset_released_at, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_WORKSPACE_UUID_TARGET_WORKSPACE_UUID = "t.workspace_uuid AS target_workspace_uuid, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_GROUP_WORKSPACE_KEY_ALTERNATE_A = "t.group_workspace_key AS target_group_workspace_key, t.store_ref AS target_store_ref, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_SALES_MENU_REF = "t.sales_menu_ref AS target_sales_menu_ref, t.sales_item_ref AS target_sales_item_ref, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_USAGE = "t.usage AS target_usage, t.expected_draft_version AS target_expected_draft_version ";
    public static final String PLATFORM_ASSET_SERVICE_FROM_CLAUSE_STAGED_ASSET_FROM_PLATFORM_ASSET_STAGED_A_ALTERNATE_A = "FROM platform_asset.staged_asset a ";
    public static final String PLATFORM_ASSET_SERVICE_JOIN_SALES_MENU_ASSET_TARGET_ASSET_REF = "JOIN platform_asset.sales_menu_asset_target t ON t.asset_ref=a.asset_ref ";
    public static final String PLATFORM_ASSET_SERVICE_WHERE_OF_ASSET_REF = "WHERE a.asset_ref=? FOR UPDATE OF a, t";
    public static final String PLATFORM_ASSET_SERVICE_UPDATE_STAGED_ASSET_STATUS_ACTIVE_CLAIMED_BY_TYPE_CLAIMED_BY_ID = "UPDATE platform_asset.staged_asset SET status='ACTIVE', claimed_by_type=?, claimed_by_id=?, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_ACTIVATED_AT_EPOCH_MILLIS_VERSION_ASSET_REF_USAGE = "activated_at_epoch_millis=?, version=version+1 WHERE asset_ref=? AND usage=? ";
    public static final String PLATFORM_ASSET_SERVICE_CONDITION_STATUS_STAGED_VERSION_WORKSPACE_UUID = "AND status='STAGED' AND version=? AND workspace_uuid=? AND group_workspace_key=? ";
    public static final String PLATFORM_ASSET_SERVICE_RETURNING_ASSET_REF_USAGE_STATUS_VERSION = "RETURNING asset_ref, usage, status, version, size_bytes";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_RECEIPT_REQUEST_HASH_ASSET_REF_STATUS = "SELECT receipt.request_hash, asset.asset_ref, asset.status, asset.version, asset.content_type, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_SIZE_BYTES_ALTERNATE_A = "asset.size_bytes, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_ASSET_COMMAND_RECEIPT_SHA256_RECEIPT = "asset.sha256 FROM platform_asset.asset_command_receipt receipt JOIN ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_PLATFORM_ASSET_STAGED_ASSET = "platform_asset.staged_asset ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_ASSET_REF_RECEIPT_IDEMPOTENCY_KEY = "asset ON asset.asset_ref=receipt.asset_ref WHERE receipt.idempotency_key=? AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_RECEIPT_SCOPE_KEY = "receipt.scope_key=? FOR UPDATE";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_PG_ADVISORY_XACT_LOCK_HASHTEXT_TEXT = "SELECT pg_advisory_xact_lock(hashtext(CAST(? AS text)), hashtext(CAST(? AS text)))";
    public static final String PLATFORM_ASSET_SERVICE_SELECT_PG_ADVISORY_XACT_LOCK_HASHTEXT_PLATFORM_OBJECT = "SELECT pg_advisory_xact_lock(hashtext('platform-asset-object'), hashtext(CAST(? AS text)))";
    public static final String PLATFORM_ASSET_SERVICE_INSERT_INTO_ASSET_COMMAND_RECEIPT_SCOPE_KEY_IDEMPOTENCY_KEY_ASSET_REF = "INSERT INTO platform_asset.asset_command_receipt (scope_key, idempotency_key, asset_ref, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_REQUEST_HASH_RESPONSE_JSON_CREATED_AT_EPOCH_MILLIS = "request_hash, response_json, created_at_epoch_millis) VALUES (?, ?, ?, ?, CAST(? AS ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_SET_SCOPE_KEY_IDEMPOTENCY_KEY_ASSET_REF_ASS = "JSONB), ?) ON CONFLICT (scope_key, idempotency_key) DO UPDATE SET asset_ref=EXCLUDED.ass";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_ET_REF = "et_ref, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_REQUEST_HASH_RESPONSE_JSON = "request_hash=EXCLUDED.request_hash, response_json=EXCLUDED.response_json, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_CREATED_AT_EPOCH_MILLIS = "created_at_epoch_millis=EXCLUDED.created_at_epoch_millis WHERE ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_PLATFORM_ASSET_ASSET_COMMAND_RECEIPT_REQUEST_HASH = "platform_asset.asset_command_receipt.request_hash=EXCLUDED.request_hash AND ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_PLATFORM_ASSET_ASSET_COMMAND_RECEIPT_ASSET_REF = "platform_asset.asset_command_receipt.asset_ref=EXCLUDED.asset_ref";
    public static final String PLATFORM_ASSET_SERVICE_INSERT_INTO_ASSET_COMMAND_RECEIPT_SCOPE_KEY_IDEMPOTENCY_KEY_ASSET_REF_ALTERNATE_A = "INSERT INTO platform_asset.asset_command_receipt (scope_key, idempotency_key, asset_ref, ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION_REQUEST_HASH_RESPONSE_JSON_CREATED_AT_EPOCH_MILLIS_ALTERNATE_A = "request_hash, response_json, created_at_epoch_millis) VALUES (?, ?, ?, ?, CAST(? AS ";
    public static final String PLATFORM_ASSET_SERVICE_CONTINUATION = "JSONB), ?)";
}
