package com.catering.v2s.catalog.application.persistence;

/** SQL text fragments owned by CatalogCopyService; B3 relocates text only and does not change execution. */
public final class CatalogCopyServiceSql {
    public static final String PARAMETER_PLACEHOLDER = "?";
    public static final String PLACEHOLDER_SEPARATOR = ",";
    public static final String CATALOG_COPY_SERVICE_INSERT_INTO_CATALOG_CATEGORY_INSERT_INTO_CATALOG_CATALOG_ = "INSERT INTO catalog.catalog_category ";
    public static final String CATALOG_COPY_SERVICE_OPEN_PAREN_CATEGORY_REF_DATA_NODE_REF_BRAND_REF_CODE = "(category_ref,data_node_ref,brand_ref,code,name,parent_code,parent_category_ref,";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_STAT = "stat";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_DISPLAY_ORDER = "us,display_order,version,created_at_epoch_millis,updated_at_epoch_millis) ";
    public static final String CATALOG_COPY_SERVICE_VALUES = "VALUES ";
    public static final String CATALOG_COPY_SERVICE_OPEN_PAREN_DATA_NODE_REF_BRAND_REF_CODE = "(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT (data_node_ref,brand_ref,code) ";
    public static final String CATALOG_COPY_SERVICE_WHERE_STATUS_VOIDED = "WHERE status <> 'VOIDED' DO NOTHING";
    public static final String CATALOG_COPY_SERVICE_INSERT_INTO_DICTIONARY_ENTRY_INSERT_INTO_CATALOG_DICTIONA = "INSERT INTO catalog.dictionary_entry ";
    public static final String CATALOG_COPY_SERVICE_OPEN_PAREN_ENTRY_REF_DATA_NODE_REF_BRAND_REF_DICTIONARY_KIND = "(entry_ref,data_node_ref,brand_ref,dictionary_kind,code,name,status,parent_entry";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_REF = "_ref";
    public static final String CATALOG_COPY_SERVICE_VALUE_SEPARATOR_DISPLAY_ORDER = ",display_order,version,created_at_epoch_millis,updated_at_epoch_millis) VALUES ";
    public static final String CATALOG_COPY_SERVICE_OPEN_PAREN_ON_CONFLICT = "(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT ";
    public static final String CATALOG_COPY_SERVICE_OPEN_PAREN_DATA_NODE_REF_BRAND_REF_DICTIONARY_KIND_CODE = "(data_node_ref,brand_ref,dictionary_kind,code) WHERE status <> 'VOIDED' DO ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION = "NOTHING";
    public static final String CATALOG_COPY_SERVICE_INSERT_INTO_CATALOG_ITEM_ITEM_REF_DATA_NODE_REF_BRAND_REF_CODE = "INSERT INTO catalog.catalog_item (item_ref, data_node_ref, brand_ref, code, name, ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_SHORT_NAME_SHAPE_KEY_STATUS_SECTIONS = "short_name, shape_key, status, sections, source_item_code, ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_SOURCE_SCOPE_REF = "source_scope_ref, version, created_at_epoch_millis, updated_at_epoch_millis) ";
    public static final String CATALOG_COPY_SERVICE_VALUES_ALTERNATE_A = "VALUES ";
    public static final String CATALOG_COPY_SERVICE_OPEN_PAREN_CAST_AS_JSONB_1_ON = "(?, ?, ?, ?, ?, ?, ?, ?, CAST(? AS JSONB), ?, ?, 1, ?, ?) ON ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CONFLICT_DO_NOTHING = "CONFLICT DO NOTHING";
    public static final String CATALOG_COPY_SERVICE_UPDATE_CATALOG_ITEM_NAME_SHORT_NAME_SECTIONS = "UPDATE catalog.catalog_item SET name=?,short_name=?,sections=CAST(? AS JSONB),";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_VERSION_UPDATED_AT_EPOCH_MILLIS_DATA_NODE_REF = "version=version+1,updated_at_epoch_millis=? WHERE data_node_ref=? AND ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_BRAND_REF = "brand_ref=? ";
    public static final String CATALOG_COPY_SERVICE_CONDITION_CODE_VERSION = "AND code=? AND version=?";
    public static final String CATALOG_COPY_SERVICE_WHERE_CODE_ITEM_REF = " WHERE code > ? OR (code = ? AND item_ref > ?)";
    public static final String CATALOG_COPY_SERVICE_CTE_MATCHING_ITEM_REF_CODE_NAME = "WITH matching AS (SELECT item_ref, code, name, short_name, shape_key, status, sections::text, ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_VERSION_UPDATED_AT_EPOCH_MILLIS_SOURCE_SCOPE_REF = "version, updated_at_epoch_millis, source_scope_ref FROM ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_ITEM_DATA_NODE_REF_BRAND_REF_STATUS = "catalog.catalog_item WHERE data_node_ref=? AND brand_ref=? AND status <> 'VOIDED' AND ";
    public static final String CATALOG_COPY_SERVICE_OPEN_PAREN_TEXT_NAME_CHR_SHORT_NAME = "(?::text IS NULL OR (name || chr(1) || COALESCE(short_name, '') || chr(1) || code) ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_MATCHING_ILIKE_AGGREGATE_TOTAL_PAGED = "ILIKE '%' || ? || '%')), aggregate AS (SELECT COUNT(*) AS total FROM matching), paged AS ";
    public static final String CATALOG_COPY_SERVICE_OPEN_PAREN_ITEM_REF_CODE_NAME_SHORT_NAME = "(SELECT item_ref,code,name,short_name,shape_key,status,sections,version,";
    public static final String CATALOG_COPY_SERVICE_UPDATE_MATCHING_UPDATED_AT_EPOCH_MILLIS_SOURCE_SCOPE_REF = "updated_at_epoch_millis,source_scope_ref FROM matching";
    public static final String CATALOG_COPY_SERVICE_ORDER_BY_CODE_ITEM_REF = " ORDER BY code NULLS LAST, item_ref LIMIT ?) SELECT ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_ITEM_REF_CODE_NAME_SHORT_NAME = "p.item_ref,p.code,p.name,p.short_name,p.shape_key,p.status,p.sections,";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_AGGREGATE_VERSION_UPDATED_AT_EPOCH_MILLIS_SOURCE_SCOPE_REF_TOTAL = "p.version,p.updated_at_epoch_millis,p.source_scope_ref,a.total FROM aggregate a LEFT JOIN ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_PAGED = "paged p ON ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CODE_ITEM_REF = "TRUE ORDER BY p.code NULLS LAST,p.item_ref";
    public static final String CATALOG_COPY_SERVICE_UPDATE_CATALOG_ITEM = "UPDATE catalog.catalog_item SET sales_unit_ref=?,sales_unit_code=?,sales_unit_name=?,sales_unit_di";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_MENSION_SALES_UNIT_PRECISION = "mension=?,sales_unit_precision=?,";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_BASE_MEASURE_UNIT_REF = "base_measure_unit_ref=?,base_measure_unit_code=?,base_measure_unit_name=?,base_measure_u";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_NIT_DIMENSION_BASE_MEASURE_UNIT_PRECISION_ITEM_REF = "nit_dimension=?,base_measure_unit_precision=? WHERE item_ref=?";
    public static final String CATALOG_COPY_SERVICE_UPDATE_CATALOG_SKU_UPDATE_CATALOG_CATALOG_SKU_S = "UPDATE catalog.catalog_sku SET";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_SALES_UNIT_REF = " sales_unit_ref=?,sales_unit_code=?,sales_unit_name=?,sales_unit_dimension=?,sales_unit_p";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_RECISION = "recision=?,";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_BASE_MEASURE_UNIT_REF_ALTERNATE_A = "base_measure_unit_ref=?,base_measure_unit_code=?,base_measure_unit_name=?,";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_BASE_MEASURE_UNIT_DIMENSION_BASE_MEASURE_UNIT_PRECISION = "base_measure_unit_dimension=?,base_measure_unit_precision=?";
    public static final String CATALOG_COPY_SERVICE_VALUE_SEPARATOR_UPDATED_AT_EPOCH_MILLIS = ",updated_at_epoch_millis=?";
    public static final String CATALOG_COPY_SERVICE_WHERE_PRODUCT_SKU_REF = " WHERE product_sku_ref=?";
    public static final String CATALOG_COPY_SERVICE_INSERT_INTO_UNIT_DEFINITION_UNIT_REF_DATA_NODE_REF_BRAND_REF_CODE = "INSERT INTO catalog.unit_definition(unit_ref,data_node_ref,brand_ref,code,name,dimension,precision";
    public static final String CATALOG_COPY_SERVICE_VALUE_SEPARATOR_STATUS_VERSION_CREATED_AT_EPOCH_MILLIS_UPDATED_AT_EPOCH_MILLIS = ",status,version,created_at_epoch_millis,updated_at_epoch_millis) ";
    public static final String CATALOG_COPY_SERVICE_VALUES_DATA_NODE_REF_BRAND_REF_CODE = "VALUES(?,?,?,?,?,?,?, ?,1,?,?) ON CONFLICT(data_node_ref,brand_ref,code) ";
    public static final String CATALOG_COPY_SERVICE_WHERE_STATUS_VOIDED_ALTERNATE_A = "WHERE status <> 'VOIDED' DO NOTHING";
    public static final String CATALOG_COPY_SERVICE_SELECT_COMPONENT_PRODUCT_SKU_REF_COMPOSITE_COMPONENT_REF = "SELECT component.product_sku_ref,component.composite_component_ref,";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_OWNER_ITEM_ITEM_REF_CODE_NAME = "owner_item.item_ref,owner_item.code,owner_item.name FROM ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_COMPOSITE_GROUP_CATALOG_COMPOSITE_COMPONENT_COMPONENT = "catalog.catalog_composite_component component JOIN catalog.catalog_composite_group ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_GROUP_ROW = "group_row ON ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_ITEM_GROUP_ROW_COMPOSITE_GROUP_REF_COMPONENT = "group_row.composite_group_ref=component.composite_group_ref JOIN catalog.catalog_item ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_SKU_OWNER_ITEM_ITEM_REF_GROUP_ROW_TARGET_SKU = "owner_item ON owner_item.item_ref=group_row.item_ref JOIN catalog.catalog_sku target_sku ON ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_TARGET_SKU_PRODUCT_SKU_REF_COMPONENT_OWNER_ITEM = "target_sku.product_sku_ref=component.product_sku_ref WHERE owner_item.data_node_ref=? AND ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_OWNER_ITEM_BRAND_REF = "owner_item.brand_ref=? ";
    public static final String CATALOG_COPY_SERVICE_CONDITION = "AND ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_OWNER_ITEM_STATUS_VOIDED_COMPONENT = "owner_item.status <> 'VOIDED' AND component.product_sku_ref = ANY(?::uuid[]) ";
    public static final String CATALOG_COPY_SERVICE_CONDITION_OWNER_ITEM_ITEM_REF_TARGET_SKU = "AND owner_item.item_ref <> target_sku.item_ref ORDER BY ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_COMPONENT_PRODUCT_SKU_REF_OWNER_ITEM_CODE = "component.product_sku_ref,owner_item.code,component.composite_component_ref";
    public static final String CATALOG_COPY_SERVICE_SELECT_CATALOG_CATEGORY_CATEGORY_REF_PARENT_CATEGORY_REF_DATA_NODE_REF = "SELECT category_ref,parent_category_ref FROM catalog.catalog_category WHERE data_node_ref=? ";
    public static final String CATALOG_COPY_SERVICE_CONDITION_BRAND_REF_STATUS_VOIDED = "AND brand_ref=? AND status <> 'VOIDED' FOR UPDATE";
    public static final String CATALOG_COPY_SERVICE_SELECT_CATALOG_ITEM_ITEM_REF_CODE_DATA_NODE_REF_BRAND_REF = "SELECT item_ref,code FROM catalog.catalog_item WHERE data_node_ref=? AND brand_ref=? AND item_ref IN (";
    public static final String CATALOG_COPY_SERVICE_SELECT = "SELECT";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_ITEM_REF_CODE_NAME_SHORT_NAME_ALTERNATE_A = " item_ref,code,name,short_name,shape_key,status,sections::text,version,";
    public static final String CATALOG_COPY_SERVICE_UPDATE_UPDATED_AT_EPOCH_MILLIS_SOURCE_SCOPE_REF = "updated_at_epoch_millis,source_scope_ref";
    public static final String CATALOG_COPY_SERVICE_FROM_CLAUSE_CATALOG_ITEM_DATA_NODE_REF_BRAND_REF_CODE = " FROM catalog.catalog_item WHERE data_node_ref=? AND brand_ref=? AND code IN (";
    public static final String CATALOG_COPY_SERVICE_SELECT_ITEM_REF_CODE_NAME_SHORT_NAME = "SELECT item_ref,code,name,short_name,shape_key,status,sections::text,version,updated_at_epoch_millis,";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_ITEM_SOURCE_SCOPE_REF_DATA_NODE_REF_BRAND_REF = "source_scope_ref FROM catalog.catalog_item WHERE data_node_ref=? AND brand_ref=? AND ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_STATUS_VOIDED_CODE = "status <> 'VOIDED' ORDER BY code";
    public static final String CATALOG_COPY_SERVICE_SELECT_ALTERNATE_A = "SELECT ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_SKU_ITEM_REF = "EXISTS (SELECT 1 FROM catalog.catalog_sku WHERE item_ref IN (";
    public static final String CATALOG_COPY_SERVICE_SELECT_ITEM_REF_SALES_UNIT_REF_SALES_UNIT_CODE_SALES_UNIT_NAME = "SELECT item_ref,sales_unit_ref,sales_unit_code,sales_unit_name,sales_unit_dimension,sales_unit_pre";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CISION = "cision,";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_BASE_MEASURE_UNIT_REF_ALTERNATE_B = "base_measure_unit_ref,base_measure_unit_code,base_measure_unit_name,base_measure_unit_di";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_MENSION_BASE_MEASURE_UNIT_PRECISION = "mension,base_measure_unit_precision ";
    public static final String CATALOG_COPY_SERVICE_FROM_CLAUSE_CATALOG_ITEM_ITEM_REF = "FROM catalog.catalog_item WHERE item_ref IN (";
    public static final String CATALOG_COPY_SERVICE_CTE_CATALOG_CATEGORY_SELECTED_CATEGORY_REF = "WITH RECURSIVE selected(category_ref) AS (SELECT category_ref FROM catalog.catalog_category WHERE ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_DATA_NODE_REF_BRAND_REF_CATEGORY_REF = "data_node_ref=? AND brand_ref=? AND category_ref IN (";
    public static final String CATALOG_COPY_SERVICE_SELECT_UNIT_DEFINITION_UNIT_REF_CODE_NAME_DIMENSION = "SELECT unit_ref,code,name,dimension,precision,status,version FROM catalog.unit_definition ";
    public static final String CATALOG_COPY_SERVICE_WHERE_DATA_NODE_REF_BRAND_REF_UNIT_REF = "WHERE data_node_ref=? AND brand_ref=? AND unit_ref IN (";
    public static final String CATALOG_COPY_SERVICE_CTE_SELECTED = "WITH RECURSIVE selected AS (SELECT ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_ENTRY_REF_DATA_NODE_REF_BRAND_REF_DICTIONARY_KIND = "entry_ref,data_node_ref,brand_ref,dictionary_kind,code,name,status,parent_entry_ref,display_";
    public static final String CATALOG_COPY_SERVICE_ALTERNATIVE_ORDE = "orde";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_DICTIONARY_ENTRY_VERSION_DATA_NODE_REF_BRAND_REF_STATUS = "r,version FROM catalog.dictionary_entry WHERE data_node_ref=? AND brand_ref=? AND status <> ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_VOIDED_ENTRY_REF = "'VOIDED' AND entry_ref IN (";
    public static final String CATALOG_COPY_SERVICE_SELECT_COMMAND_RECEIPT_OPERATION_ID_REQUEST_HASH_RESPONSE_TEXT = "SELECT operation_id,request_hash,response::text FROM catalog.command_receipt WHERE data_node_ref=? ";
    public static final String CATALOG_COPY_SERVICE_CONDITION_IDEMPOTENCY_KEY = "AND idempotency_key=?";
    public static final String CATALOG_COPY_SERVICE_INSERT_INTO = "INSERT INTO ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_COMMAND_RECEIPT_RECEIPT_REF_DATA_NODE_REF_IDEMPOTENCY_KEY = "catalog.command_receipt(receipt_ref,data_node_ref,idempotency_key,operation_id,request_hash,";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_RESP = "resp";
    public static final String CATALOG_COPY_SERVICE_JOIN_CONDITION_ONSE_CREATED_AT_EPOCH_MILLIS = "onse,created_at_epoch_millis) VALUES(?,?,?,?,?,CAST(? AS JSONB),?)";
    public static final String CATALOG_COPY_SERVICE_SELECT_CATALOG_ITEM_VERSION_DATA_NODE_REF_BRAND_REF = "SELECT COALESCE(MAX(version),0) FROM catalog.catalog_item WHERE data_node_ref=? AND brand_ref=?";
    public static final String CATALOG_COPY_SERVICE_SELECT_CATALOG_ITEM_VERSION_DATA_NODE_REF_BRAND_REF_ALTERNATE_A = "SELECT COALESCE(MAX(version),0) FROM catalog.catalog_item WHERE data_node_ref=? AND brand_ref=? ";
    public static final String CATALOG_COPY_SERVICE_CONDITION_CODE_STATUS_VOIDED = "AND code=? AND status <> 'VOIDED'";
    public static final String CATALOG_COPY_SERVICE_SELECT_CATALOG_ITEM_VERSION_DATA_NODE_REF_BRAND_REF_ALTERNATE_B = "SELECT COALESCE(MAX(version),0) FROM catalog.catalog_item WHERE data_node_ref=? AND brand_ref=? AND ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CODE = "code IN (";
    public static final String CATALOG_COPY_SERVICE_SELECT_CATALOG_CATEGORY_CODE_VERSION_DATA_NODE_REF_BRAND_REF = "SELECT code,MAX(version) FROM catalog.catalog_category WHERE data_node_ref=? AND brand_ref=? ";
    public static final String CATALOG_COPY_SERVICE_CONDITION_CODE = "AND code IN (";
    public static final String CATALOG_COPY_SERVICE_SELECT_DICTIONARY_ENTRY_DICTIONARY_KIND_CODE_VERSION_DATA_NODE_REF = "SELECT dictionary_kind,code,MAX(version) FROM catalog.dictionary_entry WHERE data_node_ref=? AND ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_BRAND_REF_ALTERNATE_A = "brand_ref=? AND (";
    public static final String CATALOG_COPY_SERVICE_SELECT_UNIT_DEFINITION_CODE_VERSION_DATA_NODE_REF_BRAND_REF = "SELECT code,MAX(version) FROM catalog.unit_definition WHERE data_node_ref=? AND brand_ref=? ";
    public static final String CATALOG_COPY_SERVICE_CONDITION_CODE_ALTERNATE_A = "AND code IN (";
    public static final String CATALOG_COPY_SERVICE_SELECT_CATALOG_CATEGORY_CODE_CATEGORY_REF_STATUS_VERSION = "SELECT code,category_ref,status,version FROM catalog.catalog_category WHERE data_node_ref=? ";
    public static final String CATALOG_COPY_SERVICE_CONDITION_BRAND_REF_CODE = "AND brand_ref=? AND code IN (";
    public static final String CATALOG_COPY_SERVICE_SELECT_DICTIONARY_ENTRY_DICTIONARY_KIND_CODE_ENTRY_REF_STATUS = "SELECT dictionary_kind,code,entry_ref,status,version FROM catalog.dictionary_entry WHERE ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_DATA_NODE_REF_BRAND_REF = "data_node_ref=? AND brand_ref=? AND (";
    public static final String CATALOG_COPY_SERVICE_SELECT_UNIT_DEFINITION_UNIT_REF_CODE_NAME_DIMENSION_ALTERNATE_A = "SELECT unit_ref,code,name,dimension,precision,status,version FROM catalog.unit_definition ";
    public static final String CATALOG_COPY_SERVICE_WHERE_DATA_NODE_REF_BRAND_REF_CODE = "WHERE data_node_ref=? AND brand_ref=? AND code IN (";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_STATUS_VOIDED_CATEGORY_PARENT_CATEGORY_REF = ") AND status <> 'VOIDED' UNION SELECT category.parent_category_ref FROM ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_SELECTED_CATALOG_CATEGORY_CATEGORY_CHILD = "catalog.catalog_category category JOIN selected child ON ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATEGORY_CATEGORY_REF_CHILD_PARENT_CATEGORY_REF = "category.category_ref=child.category_ref WHERE category.parent_category_ref IS NOT NULL ";
    public static final String CATALOG_COPY_SERVICE_CONDITION_CATEGORY_DATA_NODE_REF_BRAND_REF_STATUS = "AND category.data_node_ref=? AND category.brand_ref=? AND category.status <> 'VOIDED') ";
    public static final String CATALOG_COPY_SERVICE_SELECT_ALTERNATE_B = "SELECT ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATEGORY_CATEGORY_REF_CODE_NAME = "category.category_ref,category.code,category.name,category.parent_code,category.parent_c";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_ATEGORY_REF_CATEGORY_STATUS_VERSION = "ategory_ref,category.status,category.version,category.display_order FROM ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_SELECTED_CATALOG_CATEGORY_CATEGORY = "catalog.catalog_category category JOIN selected ON ";
    public static final String CATALOG_COPY_SERVICE_SELECT_SELECTED_CATEGORY_REF_CATEGORY_PARENT_CATEGORY_REF = "selected.category_ref=category.category_ref ORDER BY category.parent_category_ref NULLS ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATEGORY_DISPLAY_ORDER_CODE = "FIRST,category.display_order,category.code";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_STATUS_VOIDED = ") AND status <> 'VOIDED'";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_STATUS_VOIDED_CODE = ") AND status <> 'VOIDED' ORDER BY code";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_STATUS_VOIDED_ALTERNATE_A = ") AND status <> 'VOIDED'),";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_ITEM_CATEGORY_ITEM_REF = "EXISTS (SELECT 1 FROM catalog.catalog_item_category WHERE item_ref IN (";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN = ")),";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_COMPOSITE_GROUP_ITEM_REF = "EXISTS (SELECT 1 FROM catalog.catalog_composite_group WHERE item_ref IN (";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_ALTERNATE_A = ")),";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_ITEM_ATTRIBUTE_ASSIGNMENT_ITEM_REF = "EXISTS (SELECT 1 FROM catalog.catalog_item_attribute_assignment WHERE item_ref IN (";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_ALTERNATE_B = ")),";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_ITEM_ORDER_OPTION_CONFIG_ITEM_REF = "EXISTS (SELECT 1 FROM catalog.catalog_item_order_option_config WHERE item_ref IN (";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_ALTERNATE_C = ")),";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_SKU_VARIANT_AXIS_ITEM_REF = "EXISTS (SELECT 1 FROM catalog.catalog_sku_variant_axis WHERE item_ref IN (";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_ALTERNATE_D = ")),";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_ITEM_IMAGE_ITEM_REF = "EXISTS (SELECT 1 FROM catalog.catalog_item_image WHERE item_ref IN (";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_ALTERNATE_E = ")),";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_CATALOG_ITEM_REFERENCE_ITEM_REF = "EXISTS (SELECT 1 FROM catalog.catalog_item_reference WHERE item_ref IN (";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_ALTERNATE_F = "))";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_ALTERNATE_G = ")";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_CODE_UNIT_REF = ") ORDER BY code,unit_ref";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_UNION_SELECT = ") UNION SELECT ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_PARENT_ENTRY_REF_DATA_NODE_REF_BRAND_REF = "parent.entry_ref,parent.data_node_ref,parent.brand_ref,parent.dictionary_kind,parent.cod";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_PARENT_NAME_STATUS_PARENT_ENTRY_REF = "e,parent.name,parent.status,parent.parent_entry_ref,parent.display_order,parent.version ";
    public static final String CATALOG_COPY_SERVICE_FROM_CLAUSE_SELECTED_PARENT_CHILD = "FROM catalog.dictionary_entry parent JOIN selected child ON ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_PARENT_ENTRY_REF_CHILD_PARENT_ENTRY_REF = "parent.entry_ref=child.parent_entry_ref AND parent.data_node_ref=child.data_node_ref ";
    public static final String CATALOG_COPY_SERVICE_CONDITION_PARENT_BRAND_REF_CHILD_STATUS = "AND parent.brand_ref=child.brand_ref WHERE parent.status <> 'VOIDED') SELECT ";
    public static final String CATALOG_COPY_SERVICE_CONTINUATION_ENTRY_REF_DICTIONARY_KIND_CODE_NAME = "entry_ref,dictionary_kind,code,name,status,parent_entry_ref,display_order,version FROM ";
    public static final String CATALOG_COPY_SERVICE_SELECT_SELECTED_DICTIONARY_KIND_CODE = "selected ORDER BY dictionary_kind,code";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_STATUS_VOIDED_ALTERNATE_B = ") AND status <> 'VOIDED'";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_CODE = ") GROUP BY code";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_DICTIONARY_KIND_CODE = ") GROUP BY dictionary_kind,code";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_CODE_ALTERNATE_A = ") GROUP BY code";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_CODE_CATEGORY_REF = ") ORDER BY code,category_ref";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_DICTIONARY_KIND_CODE_ENTRY_REF = ") ORDER BY dictionary_kind,code,entry_ref";
    public static final String CATALOG_COPY_SERVICE_CLOSE_PAREN_CODE_UNIT_REF_ALTERNATE_A = ") ORDER BY code,unit_ref";
    public static final String DICTIONARY_KEY_PREDICATE = "(dictionary_kind=? AND code=?)";
    public static final String SQL_OR_JOINER = " OR ";
}
