package com.catering.v2s.catalog.application.persistence;

/** SQL text fragments owned by CatalogCompositeFacts; B3 relocates text only and does not change execution. */
public final class CatalogCompositeFactsSql {
    public static final String PARAMETER_PLACEHOLDER = "?";
    public static final String PLACEHOLDER_SEPARATOR = ",";
    public static final String CATALOG_COMPOSITE_FACTS_SELECT = "SELECT ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_GROUP_ROW_ITEM_REF_COMPOSITE_GROUP_REF_GROUP_CODE = "group_row.item_ref,group_row.composite_group_ref,group_row.group_code,group_row.group_name,g";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_ROUP = "roup";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_ROW_SELECTION_RULE_GROUP_ROW_MIN_SELECTIONS = "_row.selection_rule,group_row.min_selections,group_row.max_selections,group_row.display_orde";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_R_CO = "r,co";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_MPONENT_COMPOSITE_COMPONENT_REF_COMPONENT_COMPONENT_ITEM_REF = "mponent.composite_component_ref,component.component_item_ref,component.product_sku_ref,compo";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_NENT = "nent";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_QUANTITY_COMPONENT_UNIT_IS_DEFAULT = ".quantity,component.unit,component.is_default,component.extra_price,component.status,compone";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_NT_D = "nt.d";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_ISPLAY_ORDER_ITEM_CODE_NAME = "isplay_order,item.code,item.name,sku.sku_code,sku.sku_name ";
    public static final String CATALOG_COMPOSITE_FACTS_FROM_CLAUSE_CATALOG_COMPOSITE_GROUP_GROUP_ROW = "FROM catalog.catalog_composite_group group_row LEFT ";
    public static final String CATALOG_COMPOSITE_FACTS_JOIN = "JOIN ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_CATALOG_COMPOSITE_COMPONENT_COMPONENT = "catalog.catalog_composite_component component ON ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_CATALOG_ITEM_COMPONENT_COMPOSITE_GROUP_REF_GROUP_ROW = "component.composite_group_ref=group_row.composite_group_ref LEFT JOIN catalog.catalog_item ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_ITEM = "item ";
    public static final String CATALOG_COMPOSITE_FACTS_JOIN_CONDITION_CATALOG_SKU_ITEM_ITEM_REF_COMPONENT_COMPONENT_ITEM_REF = "ON item.item_ref=component.component_item_ref LEFT JOIN catalog.catalog_sku sku ON ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_SKU_ITEM_REF_COMPONENT_COMPONENT_ITEM_REF = "sku.item_ref=component.component_item_ref AND sku.product_sku_ref=component.product_sku_ref ";
    public static final String CATALOG_COMPOSITE_FACTS_WHERE_GROUP_ROW_ITEM_REF = "WHERE group_row.item_ref IN (";
    public static final String CATALOG_COMPOSITE_FACTS_UPDATE_CATALOG_COMPOSITE_GROUP_DISPLAY_ORDER_ITEM_REF = "UPDATE catalog.catalog_composite_group SET display_order=display_order+1000000 WHERE item_ref=?";
    public static final String CATALOG_COMPOSITE_FACTS_INSERT_INTO = "INSERT INTO ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_CATALOG_COMPOSITE_GROUP_COMPOSITE_GROUP_REF_ITEM_REF_GROUP_CODE = "catalog.catalog_composite_group(composite_group_ref,item_ref,group_code,group_name,s";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_ELEC = "elec";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_TION_RULE_MIN_SELECTIONS_MAX_SELECTIONS_DISPLAY_ORDER = "tion_rule,min_selections,max_selections,display_order) VALUES(?,?,?,?,?,?,?,?)";
    public static final String CATALOG_COMPOSITE_FACTS_UPDATE_CATALOG_COMPOSITE_GROUP_UPDATE_CATALOG_CATALOG_COMPO = "UPDATE catalog.catalog_composite_group SET ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_GROUP_NAME_SELECTION_RULE_MIN_SELECTIONS_MAX_SELECTIONS = "group_name=?,selection_rule=?,min_selections=?,max_selections=?,display_order=? ";
    public static final String CATALOG_COMPOSITE_FACTS_WHERE = "WHERE ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_COMPOSITE_GROUP_REF = "composite_group_ref=?";
    public static final String CATALOG_COMPOSITE_FACTS_DELETE_CATALOG_COMPOSITE_COMPONENT_COMPOSITE_GROUP_REF = "DELETE FROM catalog.catalog_composite_component WHERE composite_group_ref=?";
    public static final String CATALOG_COMPOSITE_FACTS_DELETE_CATALOG_COMPOSITE_GROUP_COMPOSITE_GROUP_REF = "DELETE FROM catalog.catalog_composite_group WHERE composite_group_ref=?";
    public static final String CATALOG_COMPOSITE_FACTS_INSERT_INTO_ALTERNATE_A = "INSERT INTO ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_CATALOG_COMPOSITE_GROUP_COMPOSITE_GROUP_REF_ITEM_REF_GROUP_CODE_ALTERNATE_A = "catalog.catalog_composite_group(composite_group_ref,item_ref,group_code,group_name,selection";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_RUL = "_rul";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_MIN_SELECTIONS_MAX_SELECTIONS_DISPLAY_ORDER = "e,min_selections,max_selections,display_order) VALUES(?,?,?,?,?,?,?,?)";
    public static final String CATALOG_COMPOSITE_FACTS_INSERT_INTO_ALTERNATE_B = "INSERT INTO ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_CATALOG_COMPOSITE_COMPONENT = "catalog.catalog_composite_component(composite_component_ref,composite_group_ref,componen";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_T_IT = "t_it";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_EM_REF_PRODUCT_SKU_REF_QUANTITY_UNIT = "em_ref,product_sku_ref,quantity,unit,is_default,extra_price,status,display_order) ";
    public static final String CATALOG_COMPOSITE_FACTS_VALUES = "VALUES(?,?,?,?,?,?,?,?,?,?)";
    public static final String CATALOG_COMPOSITE_FACTS_UPDATE_CATALOG_COMPOSITE_COMPONENT_DISPLAY_ORDER = "UPDATE catalog.catalog_composite_component SET display_order=display_order+1000000 WHERE ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_COMPOSITE_GROUP_REF_ALTERNATE_A = "composite_group_ref=?";
    public static final String CATALOG_COMPOSITE_FACTS_INSERT_INTO_ALTERNATE_C = "INSERT INTO ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_CATALOG_COMPOSITE_COMPONENT_ALTERNATE_A = "catalog.catalog_composite_component(composite_component_ref,composite_group_ref,comp";
    public static final String CATALOG_COMPOSITE_FACTS_JOIN_CONDITION_ONEN = "onen";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_T_ITEM_REF_PRODUCT_SKU_REF_QUANTITY_UNIT = "t_item_ref,product_sku_ref,quantity,unit,is_default,extra_price,status,display_order";
    public static final String CATALOG_COMPOSITE_FACTS_CLOSE_PAREN = ") ";
    public static final String CATALOG_COMPOSITE_FACTS_VALUES_ALTERNATE_A = "VALUES(?,?,?,?,?,?,?,?,?,?)";
    public static final String CATALOG_COMPOSITE_FACTS_UPDATE_CATALOG_COMPOSITE_COMPONENT_UPDATE_CATALOG_CATALOG_COMPO = "UPDATE catalog.catalog_composite_component SET ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_COMPONENT_ITEM_REF_PRODUCT_SKU_REF_QUANTITY_UNIT = "component_item_ref=?,product_sku_ref=?,quantity=?,unit=?,is_default=?,extra_price=?,";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_STAT = "stat";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_DISPLAY_ORDER_COMPOSITE_COMPONENT_REF = "us=?,display_order=? WHERE composite_component_ref=?";
    public static final String CATALOG_COMPOSITE_FACTS_DELETE_CATALOG_COMPOSITE_COMPONENT_COMPOSITE_COMPONENT_REF = "DELETE FROM catalog.catalog_composite_component WHERE composite_component_ref=?";
    public static final String CATALOG_COMPOSITE_FACTS_CLOSE_PAREN_ORDER_BY = ") ORDER BY ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_GROUP_ROW_ITEM_REF_DISPLAY_ORDER_GROUP_CODE = "group_row.item_ref,group_row.display_order,group_row.group_code,component.display_order,";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_COMPONENT_COMPOSITE_COMPONENT_REF = "component.composite_component_ref";
    public static final String CATALOG_COMPOSITE_FACTS_SELECT_ALTERNATE_A = "SELECT ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_COMPOSITE_GROUP_REF_GROUP_CODE_GROUP_NAME_SELECTION_RULE = "composite_group_ref,group_code,group_name,selection_rule,min_selections,max_selections,displ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_AY_O = "ay_o";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_CATALOG_COMPOSITE_GROUP_RDER_ITEM_REF = "rder FROM catalog.catalog_composite_group WHERE item_ref=?";
    public static final String CATALOG_COMPOSITE_FACTS_SELECT_ALTERNATE_B = "SELECT ";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_COMPOSITE_COMPONENT_REF = "composite_component_ref,component_item_ref,product_sku_ref,quantity,unit,is_default,extra_pr";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_ICE = "ice,";
    public static final String CATALOG_COMPOSITE_FACTS_CONTINUATION_CATALOG_COMPOSITE_COMPONENT_ALTERNATE_B = "status,display_order FROM catalog.catalog_composite_component WHERE composite_group_ref=?";
}
