package com.catering.v2s.app.edge.operations.contract;

import com.catering.v2s.app.edge.catalog.ContractSortKey;
import com.catering.v2s.app.edge.catalog.SortDirection;
import com.catering.v2s.app.edge.extension.ExtensionDefinitionWireMapper;
import com.catering.v2s.app.edge.generated.wire.ExtensionDefinition;
import com.catering.v2s.app.edge.generated.wire.StoreContract;
import com.catering.v2s.app.edge.generated.wire.StoreContractCandidatePage;
import com.catering.v2s.app.edge.generated.wire.StoreContractCandidatePageMetadata;
import com.catering.v2s.app.edge.generated.wire.StoreContractCandidatePageProject;
import com.catering.v2s.app.edge.generated.wire.StoreContractCreateRequest;
import com.catering.v2s.app.edge.generated.wire.StoreContractInvalidateRequest;
import com.catering.v2s.app.edge.generated.wire.StoreContractItem;
import com.catering.v2s.app.edge.generated.wire.StoreContractPage;
import com.catering.v2s.app.edge.generated.wire.StoreContractStoreCandidate;
import com.catering.v2s.app.edge.generated.wire.StoreContractSelectedTenant;
import com.catering.v2s.app.edge.generated.wire.StoreContractUpdateRequest;
import com.catering.v2s.app.edge.operations.session.OperationsSessionResolver;
import com.catering.v2s.contract.application.ContractCommandService;
import com.catering.v2s.contract.application.ContractTaskReadService;
import com.catering.v2s.extension.application.ExtensionDefinitionService;
import com.catering.v2s.organization.api.OrganizationEntityReadback;
import com.catering.v2s.organization.application.BusinessEntityService;
import com.catering.v2s.workspace.iam.api.WorkspaceSessionReadback;
import com.catering.v2s.workspace.iam.application.WorkspaceAuthenticationService;
import com.catering.v2s.workspace.iam.application.WorkspaceUserService;
import com.catering.v2s.app.edge.session.EdgeRequestContext;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/operations/group-workspaces/{groupWorkspaceKey}/contracts")
public final class OperationsContractController {
    private final OperationsSessionResolver sessions; private final ContractCommandService contracts; private final ContractTaskReadService reads; private final ExtensionDefinitionService definitions; private final WorkspaceUserService user; private final BusinessEntityService entities;
    public OperationsContractController(OperationsSessionResolver sessions, ContractCommandService contracts, ContractTaskReadService reads, ExtensionDefinitionService definitions, WorkspaceUserService user, BusinessEntityService entities) { this.sessions = sessions; this.contracts = contracts; this.reads = reads; this.definitions = definitions; this.user = user; this.entities = entities; }
    @GetMapping StoreContractPage list(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @org.springframework.web.bind.annotation.RequestParam long expectedContextVersion, @org.springframework.web.bind.annotation.RequestParam UUID projectId, @org.springframework.web.bind.annotation.RequestParam(required = false) UUID storeId, @org.springframework.web.bind.annotation.RequestParam(required = false) String contractNo, @org.springframework.web.bind.annotation.RequestParam(required = false) String phaseName, @org.springframework.web.bind.annotation.RequestParam(required = false) String tenantName, @org.springframework.web.bind.annotation.RequestParam(required = false) String itemCode, @org.springframework.web.bind.annotation.RequestParam(required = false) LocalDate dateFrom, @org.springframework.web.bind.annotation.RequestParam(required = false) LocalDate dateTo, @org.springframework.web.bind.annotation.RequestParam(required = false) String status, @org.springframework.web.bind.annotation.RequestParam(defaultValue = ContractSortKey.DEFAULT_WIRE) String sort, @org.springframework.web.bind.annotation.RequestParam(defaultValue = SortDirection.DEFAULT_WIRE) String direction, @org.springframework.web.bind.annotation.RequestParam(defaultValue = "1") int page, @org.springframework.web.bind.annotation.RequestParam(defaultValue = "20") int pageSize) { WorkspaceSessionReadback session = checkedSession(request, groupWorkspaceKey, expectedContextVersion); UUID scopedProjectId = scopedProject(session, projectId); var result = reads.page(session.workspaceUuid(), groupWorkspaceKey, scopedProjectId, storeId, contractNo, phaseName, tenantName, itemCode, dateFrom, dateTo, status, sort, direction, page, pageSize); return new StoreContractPage(ContractWireMapper.metadata(result.metadata()), result.items().stream().map(ContractWireMapper::wire).toList()); }
    @GetMapping("/{contractId}") StoreContract detail(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID contractId, @org.springframework.web.bind.annotation.RequestParam long expectedContextVersion) { WorkspaceSessionReadback session = checkedSession(request, groupWorkspaceKey, expectedContextVersion); return ContractWireMapper.wire(requireScopedView(session, groupWorkspaceKey, contractId)); }
    @PostMapping ResponseEntity<StoreContract> create(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @RequestHeader("Idempotency-Key") String idempotencyKey, @RequestBody StoreContractCreateRequest body) { WorkspaceSessionReadback session = session(request, groupWorkspaceKey); var actor = sessions.actor(session); UUID projectId = scopedProject(session, uuid(body.projectId())); var created = contracts.create(session.workspaceUuid(), groupWorkspaceKey, body.contractNo(), uuid(body.storeId()), projectId, date(body.effectiveFrom()), nullableDate(body.effectiveTo()), body.phaseName(), body.note(), items(body.items()), ContractWireMapper.requestValues(body.extensionValues()), idempotencyKey, actor); return ResponseEntity.status(HttpStatus.CREATED).body(ContractWireMapper.wire(reads.view(session.workspaceUuid(), groupWorkspaceKey, created.id()))); }
    @PatchMapping("/{contractId}") StoreContract update(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID contractId, @RequestHeader("Idempotency-Key") String idempotencyKey, @RequestBody StoreContractUpdateRequest body) { WorkspaceSessionReadback session = session(request, groupWorkspaceKey); requireScopedView(session, groupWorkspaceKey, contractId); var actor = sessions.actor(session); contracts.update(session.workspaceUuid(), groupWorkspaceKey, contractId, date(body.effectiveFrom()), nullableDate(body.effectiveTo()), body.phaseName(), body.note(), items(body.items()), required(body.expectedVersion()), ContractWireMapper.requestValues(body.extensionValues()), idempotencyKey, actor); return ContractWireMapper.wire(reads.view(session.workspaceUuid(), groupWorkspaceKey, contractId)); }
    @PostMapping("/{contractId}/invalidate") StoreContract invalidate(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @PathVariable UUID contractId, @RequestHeader("Idempotency-Key") String idempotencyKey, @RequestBody StoreContractInvalidateRequest body) { WorkspaceSessionReadback session = session(request, groupWorkspaceKey); requireScopedView(session, groupWorkspaceKey, contractId); var actor = sessions.actor(session); contracts.invalidate(session.workspaceUuid(), groupWorkspaceKey, contractId, required(body.expectedVersion()), idempotencyKey, actor); return ContractWireMapper.wire(reads.view(session.workspaceUuid(), groupWorkspaceKey, contractId)); }
    @GetMapping("/extension-definition") ExtensionDefinition extensionDefinition(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @org.springframework.web.bind.annotation.RequestParam long expectedContextVersion, @org.springframework.web.bind.annotation.RequestParam UUID projectId) { WorkspaceSessionReadback session = checkedSession(request, groupWorkspaceKey, expectedContextVersion); scopedProject(session, projectId); return ExtensionDefinitionWireMapper.wire(definitions.requireDefinition(session.workspaceUuid(), groupWorkspaceKey, "CONTRACT")); }
    @GetMapping("/candidates") StoreContractCandidatePage candidates(EdgeRequestContext request, @PathVariable String groupWorkspaceKey, @org.springframework.web.bind.annotation.RequestParam long expectedContextVersion, @org.springframework.web.bind.annotation.RequestParam UUID projectId, @org.springframework.web.bind.annotation.RequestParam(required = false) String storeSearch, @org.springframework.web.bind.annotation.RequestParam(required = false) UUID selectedStoreId, @org.springframework.web.bind.annotation.RequestParam(defaultValue = "1") int page, @org.springframework.web.bind.annotation.RequestParam(defaultValue = "50") int pageSize) { WorkspaceSessionReadback session = checkedSession(request, groupWorkspaceKey, expectedContextVersion); UUID scopedProjectId = scopedProject(session, projectId); var values = reads.candidates(session.workspaceUuid(), groupWorkspaceKey, scopedProjectId, selectedStoreId, storeSearch, page, pageSize); StoreContractSelectedTenant selectedTenant = selectedStoreId == null ? null : selectedStoreTenant(session, groupWorkspaceKey, scopedProjectId, selectedStoreId); return new StoreContractCandidatePage(values.groupWorkspaceKey(), new StoreContractCandidatePageProject(values.project().id().toString(), values.project().code(), values.project().name()), new StoreContractCandidatePageMetadata(values.metadata().storeSearch(), (long) values.metadata().page(), (long) values.metadata().pageSize(), values.metadata().total()), values.stores().stream().map(store -> new StoreContractStoreCandidate(store.id().toString(), store.code(), store.name(), store.storeStatus())).toList(), values.phases(), selectedTenant); }
    private WorkspaceSessionReadback session(EdgeRequestContext request, String key) { return sessions.requireWorkspace(request, key); }
    private WorkspaceSessionReadback checkedSession(EdgeRequestContext request, String key, long expectedContextVersion) { WorkspaceSessionReadback value = sessions.requireWorkspace(request, key); if (value.contextVersion() != expectedContextVersion) throw new WorkspaceAuthenticationService.SessionInvalidException(); return value; }
    private UUID scopedProject(WorkspaceSessionReadback session, UUID projectId) { return user.resolveTaskScope(session, "PROJECT", projectId).targetId(); }
    private ContractTaskReadService.StoreContractView requireScopedView(WorkspaceSessionReadback session, String key, UUID contractId) { ContractTaskReadService.StoreContractView view = reads.view(session.workspaceUuid(), key, contractId); user.resolveTaskScope(session, "PROJECT", view.project().id()); return view; }
    private StoreContractSelectedTenant selectedStoreTenant(WorkspaceSessionReadback session, String key, UUID projectId, UUID storeId) { var context = entities.requireStoreContractContext(session.workspaceUuid(), key, storeId); if (!projectId.equals(context.projectId())) throw new com.catering.v2s.app.edge.problem.InvalidEdgeRequestException("selected store is outside project"); OrganizationEntityReadback tenant = entities.requireEntity("TENANT", session.workspaceUuid(), key, context.tenantId()); return new StoreContractSelectedTenant(tenant.id().toString(), tenant.code(), tenant.name()); }
    private static UUID uuid(String value) { try { return UUID.fromString(value); } catch (RuntimeException exception) { throw new com.catering.v2s.app.edge.problem.InvalidEdgeRequestException("identifier is invalid"); } }
    private static LocalDate date(String value) { try { return LocalDate.parse(value); } catch (RuntimeException exception) { throw new com.catering.v2s.app.edge.problem.InvalidEdgeRequestException("date is invalid"); } }
    private static LocalDate nullableDate(String value) { return value == null ? null : date(value); }
    private static long required(Long value) { if (value == null) throw new com.catering.v2s.app.edge.problem.InvalidEdgeRequestException("expected version is required"); return value; }
    private static List<ContractCommandService.ItemInput> items(List<StoreContractItem> values) { if (values == null) throw new com.catering.v2s.app.edge.problem.InvalidEdgeRequestException("items are required"); return values.stream().map(value -> new ContractCommandService.ItemInput(value.code(), value.name())).toList(); }
}
