/// <reference types="@catering-v2s/assembly-base-android/config/nativewind-env" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
