package com.catering.v2s.workspace.iam.application;

import com.catering.v2s.audit.contract.AuditActor;
import com.catering.v2s.audit.contract.AuditChange;
import com.catering.v2s.audit.contract.AuditChangePolicy;
import com.catering.v2s.platform.foundation.time.TimeProvider;
import com.catering.v2s.organization.api.WorkspaceStatusLookup;
import com.catering.v2s.platform.iam.api.PlatformGovernanceAuthorization;
import com.catering.v2s.workspace.iam.api.WorkspaceAccountReadback;
import com.catering.v2s.workspace.iam.api.WorkspaceAuthorizationCatalog.UserManagementAction;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class WorkspaceAccountService {
    private static final AuditChangePolicy ACCOUNT_STATUS_CHANGED = new AuditChangePolicy("WORKSPACE_ACCOUNT", "WORKSPACE_ACCOUNT_STATUS_CHANGED", Set.of("status"));
    private static final AuditChangePolicy ASSIGNMENT_REVOKED = new AuditChangePolicy("WORKSPACE_ACCOUNT", "WORKSPACE_ACCOUNT_ASSIGNMENT_REVOKED", Set.of("serviceNodeAssignment"));
    private final JdbcTemplate jdbc; private final TimeProvider time; private final WorkspaceCommandAuthorizationService commandAuthorization; private final WorkspaceIamCommandReceiptService receipts; private final WorkspaceStatusLookup workspaces; private final PlatformGovernanceAuthorization platformAuthorization;
    public WorkspaceAccountService(JdbcTemplate jdbc, TimeProvider time) { this(jdbc, time, new WorkspaceCommandAuthorizationService(jdbc), new WorkspaceIamCommandReceiptService(jdbc, time), localWorkspaceStatus(jdbc), null); }
    public WorkspaceAccountService(JdbcTemplate jdbc, TimeProvider time, WorkspaceCommandAuthorizationService commandAuthorization) { this(jdbc, time, commandAuthorization, new WorkspaceIamCommandReceiptService(jdbc, time), localWorkspaceStatus(jdbc), null); }
    @org.springframework.beans.factory.annotation.Autowired
    public WorkspaceAccountService(JdbcTemplate jdbc, TimeProvider time, WorkspaceCommandAuthorizationService commandAuthorization, WorkspaceIamCommandReceiptService receipts, WorkspaceStatusLookup workspaces, PlatformGovernanceAuthorization platformAuthorization) { this.jdbc = jdbc; this.time = time; this.commandAuthorization = commandAuthorization; this.receipts = receipts; this.workspaces = workspaces; this.platformAuthorization = platformAuthorization; }
    @Transactional(readOnly = true) public List<WorkspaceAccountReadback> list(UUID workspaceUuid, String key) { return jdbc.query("SELECT id, workspace_uuid, group_workspace_key, mobile_normalized, login_name_normalized, display_name, status, version FROM workspace_iam.workspace_account WHERE workspace_uuid=? AND group_workspace_key=? ORDER BY login_name_normalized", (row, index) -> readback(row), workspaceUuid, key); }
    @Transactional(readOnly = true) public WorkspaceAccountReadback require(UUID workspaceUuid, String key, UUID accountId) { return jdbc.query("SELECT id, workspace_uuid, group_workspace_key, mobile_normalized, login_name_normalized, display_name, status, version FROM workspace_iam.workspace_account WHERE id=? AND workspace_uuid=? AND group_workspace_key=?", statement -> { statement.setObject(1, accountId); statement.setObject(2, workspaceUuid); statement.setString(3, key); }, result -> { if (!result.next()) throw new AccountNotFoundException(); return readback(result); }); }
    @Transactional public WorkspaceAccountReadback transitionStatus(UUID workspaceUuid, String key, UUID accountId, String status, long expectedVersion) { return transitionStatus(workspaceUuid, key, accountId, status, expectedVersion, AuditActor.system()); }
    @Transactional public WorkspaceAccountReadback transitionStatus(UUID workspaceUuid, String key, UUID accountId, String status, long expectedVersion, AuditActor actor) { requireEnabledWorkspace(workspaceUuid, key); WorkspaceAccountReadback existing = require(workspaceUuid, key, accountId); if (!Set.of("ENABLED", "DISABLED").contains(status) || jdbc.update("UPDATE workspace_iam.workspace_account SET status=?, version=version+1, updated_at_epoch_millis=? WHERE id=? AND workspace_uuid=? AND group_workspace_key=? AND version=?", status, time.currentEpochMillis(), accountId, workspaceUuid, key, expectedVersion) != 1) throw new AccountConflictException(); if ("DISABLED".equals(status)) jdbc.update("UPDATE workspace_iam.workspace_session SET status='REVOKED', revoked_at_epoch_millis=? WHERE account_id=? AND status='ACTIVE'", time.currentEpochMillis(), accountId); WorkspaceAccountReadback updated = require(workspaceUuid, key, accountId); audit(workspaceUuid, key, accountId, "WORKSPACE_ACCOUNT_STATUS_CHANGED", actor, ACCOUNT_STATUS_CHANGED, List.of(new AuditChange("status", existing.status(), updated.status()))); return updated; }
    @Transactional public WorkspaceAccountReadback transitionStatusForPlatform(UUID workspaceUuid, String key, UUID accountId, String status, long expectedVersion, String idempotencyKey, AuditActor actor) { requirePlatformActor(actor); return receipts.execute(workspaceUuid, idempotencyKey, canonical("platform-account-status", key, accountId, status, expectedVersion), WorkspaceAccountReadback.class, () -> transitionStatus(workspaceUuid, key, accountId, status, expectedVersion, actor)); }
    @Transactional public void revokeAssignment(UUID workspaceUuid, String key, UUID accountId, UUID assignmentId, long expectedVersion) { revokeAssignment(workspaceUuid, key, accountId, assignmentId, expectedVersion, AuditActor.system()); }
    @Transactional public void revokeAssignment(UUID workspaceUuid, String key, UUID accountId, UUID assignmentId, long expectedVersion, AuditActor actor) { requireEnabledWorkspace(workspaceUuid, key); String assignment = jdbc.query("SELECT service_node_type FROM workspace_iam.role_assignment WHERE id=? AND account_id=? AND workspace_uuid=? AND group_workspace_key=?", statement -> { statement.setObject(1, assignmentId); statement.setObject(2, accountId); statement.setObject(3, workspaceUuid); statement.setString(4, key); }, result -> result.next() ? result.getString(1) : null); if (assignment == null || jdbc.update("UPDATE workspace_iam.role_assignment SET status='REVOKED', version=version+1, updated_at_epoch_millis=? WHERE id=? AND account_id=? AND workspace_uuid=? AND group_workspace_key=? AND status='ACTIVE' AND version=?", time.currentEpochMillis(), assignmentId, accountId, workspaceUuid, key, expectedVersion) != 1) throw new AccountConflictException(); jdbc.update("UPDATE workspace_iam.workspace_session SET status='REVOKED', revoked_at_epoch_millis=? WHERE account_id=? AND current_assignment_id=? AND status='ACTIVE'", time.currentEpochMillis(), accountId, assignmentId); audit(workspaceUuid, key, accountId, "WORKSPACE_ACCOUNT_ASSIGNMENT_REVOKED", actor, ASSIGNMENT_REVOKED, List.of(new AuditChange("serviceNodeAssignment", assignment, "REVOKED"))); }
    @Transactional public AssignmentRevocation revokeAssignmentForPlatform(UUID workspaceUuid, String key, UUID accountId, UUID assignmentId, long expectedVersion, String idempotencyKey, AuditActor actor) { requirePlatformActor(actor); return receipts.execute(workspaceUuid, idempotencyKey, canonical("platform-assignment-revoke", key, accountId, assignmentId, expectedVersion), AssignmentRevocation.class, () -> { revokeAssignment(workspaceUuid, key, accountId, assignmentId, expectedVersion, actor); return new AssignmentRevocation(assignmentId, "REVOKED", expectedVersion + 1); }); }
    @Transactional public UUID revokeAssignment(UUID workspaceUuid, String key, UUID assignmentId, long expectedVersion) { return revokeAssignment(workspaceUuid, key, assignmentId, expectedVersion, AuditActor.system()); }
    @Transactional public UUID revokeAssignment(UUID workspaceUuid, String key, UUID assignmentId, long expectedVersion, AuditActor actor) { UUID accountId = jdbc.query("SELECT account_id FROM workspace_iam.role_assignment WHERE id=? AND workspace_uuid=? AND group_workspace_key=?", statement -> { statement.setObject(1, assignmentId); statement.setObject(2, workspaceUuid); statement.setString(3, key); }, result -> { if (!result.next()) throw new AccountNotFoundException(); return result.getObject(1, UUID.class); }); revokeAssignment(workspaceUuid, key, accountId, assignmentId, expectedVersion, actor); return accountId; }
    @Transactional public UUID revokeAssignmentForOperations(UUID workspaceUuid, String key, UUID actorAssignmentId, String expectedTargetType, UUID assignmentId, long expectedVersion, AuditActor actor) { AssignmentTarget target = jdbc.query("SELECT account_id, service_node_type, service_node_id FROM workspace_iam.role_assignment WHERE id=? AND workspace_uuid=? AND group_workspace_key=?", statement -> { statement.setObject(1, assignmentId); statement.setObject(2, workspaceUuid); statement.setString(3, key); }, result -> { if (!result.next()) throw new AccountNotFoundException(); return new AssignmentTarget(result.getObject(1, UUID.class), result.getString(2), result.getObject(3, UUID.class)); }); if (expectedTargetType == null || !expectedTargetType.equals(target.serviceNodeType())) throw new WorkspaceCommandAuthorizationService.AuthorizationDeniedException(); commandAuthorization.requireUserManagementAction(workspaceUuid, key, actorAssignmentId, target.serviceNodeType(), target.serviceNodeId(), UserManagementAction.ROLE_REVOKE); revokeAssignment(workspaceUuid, key, target.accountId(), assignmentId, expectedVersion, actor); return target.accountId(); }
    private void audit(UUID workspaceUuid, String key, UUID accountId, String action, AuditActor actor, AuditChangePolicy policy, List<AuditChange> changes) { jdbc.update("INSERT INTO workspace_iam.audit_event (id, workspace_uuid, group_workspace_key, entity_type, entity_ref_text, actor_type, actor_id, actor_display_snapshot, action, occurred_at_epoch_millis, changes_json) VALUES (?, ?, ?, 'WORKSPACE_ACCOUNT', ?, ?, ?, ?, ?, ?, CAST(? AS JSONB))", UUID.randomUUID(), workspaceUuid, key, accountId.toString(), actor.actorType(), actor.actorId(), actor.displaySnapshot(), action, time.currentEpochMillis(), auditJson(policy.allow(changes))); }
    private static WorkspaceAccountReadback readback(ResultSet result) throws SQLException { return new WorkspaceAccountReadback(result.getObject(1, UUID.class), result.getObject(2, UUID.class), result.getString(3), result.getString(4), result.getString(5), result.getString(6), result.getString(7), result.getLong(8)); }
    private static String auditJson(List<AuditChange> changes) { StringBuilder value = new StringBuilder("["); for (int index = 0; index < changes.size(); index++) { if (index > 0) value.append(','); AuditChange change = changes.get(index); value.append("{\"fieldKey\":\"").append(escape(change.fieldKey())).append("\""); if (change.beforeValue() != null) value.append(",\"before\":\"").append(escape(change.beforeValue())).append("\""); if (change.afterValue() != null) value.append(",\"after\":\"").append(escape(change.afterValue())).append("\""); value.append('}'); } return value.append(']').toString(); }
    private static String escape(String value) { return value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r"); }
    private void requireEnabledWorkspace(UUID workspaceUuid, String key) { if (!workspaces.isEnabled(workspaceUuid, key)) throw new WorkspaceDisabledException(); }
    private void requirePlatformActor(AuditActor actor) { if (platformAuthorization == null) throw new IllegalStateException("platform authorization is required"); platformAuthorization.requireEnabledPlatformAdministrator(actor); }
    private static WorkspaceStatusLookup localWorkspaceStatus(JdbcTemplate jdbc) { return (workspaceUuid, key) -> Boolean.TRUE.equals(jdbc.query("SELECT status='ENABLED' FROM platform_workspace.group_workspace WHERE workspace_uuid=? AND group_workspace_key=?", statement -> { statement.setObject(1, workspaceUuid); statement.setString(2, key); }, result -> result.next() && result.getBoolean(1))); }
    private static String canonical(String operation, String key, UUID accountId, Object value, long expectedVersion) { return operation + '|' + key + '|' + accountId + '|' + value + '|' + expectedVersion; }
    public static final class AccountNotFoundException extends RuntimeException { }
    public static final class AccountConflictException extends RuntimeException { }
    public static final class WorkspaceDisabledException extends RuntimeException { }
    private record AssignmentTarget(UUID accountId, String serviceNodeType, UUID serviceNodeId) { }
    public record AssignmentRevocation(UUID assignmentId, String status, long revision) { }
}
