/** Stable locators for project update rules and actual terminal version reports. */
export const terminalUpdateTestIds = {
  page: 'operations-terminal-update-page',
  rulesTab: 'operations-terminal-update-rules-tab',
  rulesTabLabel: 'operations-terminal-update-rules-tab-label',
  reportsTab: 'operations-terminal-update-reports-tab',
  reportsTabLabel: 'operations-terminal-update-reports-tab-label',
  createRule: 'operations-terminal-update-create-rule',
  createRuleSubmit: 'operations-terminal-update-create-rule-submit',
  ruleRow: (ruleRef: string) => `operations-terminal-update-rule-${ruleRef}`,
  ruleOpen: (ruleRef: string) => `operations-terminal-update-rule-open-${ruleRef}`,
  ruleStatusConfirm: 'operations-terminal-update-rule-status-confirm',
  ruleList: 'operations-terminal-update-rule-list',
  ruleApplicationFilter: 'terminal-update-rule-filter-application',
  ruleCreatedRangeFilter: 'terminal-update-rule-filter-created-range',
  ruleDetail: 'operations-terminal-update-rule-detail',
  ruleDetailActions: 'operations-terminal-update-rule-detail-actions',
  ruleHistoryAction: 'operations-terminal-update-rule-history-action',
  enableRuleAction: 'operations-terminal-update-enable-rule-action',
  targetMode: 'operations-terminal-update-target-mode',
  initialStatus: 'operations-terminal-update-initial-status',
  targetModeOption: (mode: 'ALL' | 'STORE_REFS') =>
    `operations-terminal-update-target-mode-option-${mode.toLowerCase()}`,
  storeRefs: 'operations-terminal-update-store-refs',
  storeRefOption: (storeRef: string) => `operations-terminal-update-store-option-${storeRef}`,
  fullArtifact: 'operations-terminal-update-full-artifact',
  fullArtifactOption: (artifactRef: string) => `operations-terminal-update-full-option-${artifactRef}`,
  fullArtifactLoadMore: 'operations-terminal-update-full-artifact-load-more',
  hotArtifact: 'operations-terminal-update-hot-artifact',
  hotArtifactOption: (artifactRef: string) => `operations-terminal-update-hot-option-${artifactRef}`,
  hotArtifactLoadMore: 'operations-terminal-update-hot-artifact-load-more',
  nMinutes: 'operations-terminal-update-n-minutes',
  hotStrategy: 'operations-terminal-update-hot-strategy',
  hotStrategyOption: (strategy: 'IMMEDIATE' | 'IDLE') =>
    `operations-terminal-update-hot-strategy-option-${strategy.toLowerCase()}`,
  mMinutes: 'operations-terminal-update-m-minutes',
  description: 'operations-terminal-update-description',
  reportQuery: 'operations-terminal-update-report-query',
  reportQuerySubmit: 'operations-terminal-update-report-query-submit',
  reportStore: 'operations-terminal-update-report-store',
  reportApk: 'operations-terminal-update-report-apk',
  reportJs: 'operations-terminal-update-report-js',
  reportRuntime: 'operations-terminal-update-report-runtime',
  reportList: 'operations-terminal-update-report-list',
  reportDetail: 'operations-terminal-update-report-detail',
  reportHistory: 'operations-terminal-update-report-history',
  reportRow: (terminalRef: string) => `operations-terminal-update-report-${terminalRef}`,
  reportOpen: (terminalRef: string) => `operations-terminal-update-report-open-${terminalRef}`,
} as const;
