const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9_-]+/g, '-');

export const storeServicePointTestIds = {
  page: 'store-service-point-page',
  feedback: 'store-service-point-feedback',
  operatingRuleGate: 'store-service-point-operating-rule-gate',
  areaCreate: 'store-service-point-area-create',
  areaList: 'store-service-point-area-list',
  areaRow: (ref: string) => `store-service-point-area-row-${slug(ref)}`,
  areaMenu: (ref: string) => `store-service-point-area-menu-${slug(ref)}`,
  areaMenuAction: (ref: string, action: string) => `store-service-point-area-menu-${slug(ref)}-${slug(action)}`,
  pointCreate: 'store-service-point-point-create',
  pointList: 'store-service-point-point-list',
  pointRow: (ref: string) => `store-service-point-point-row-${slug(ref)}`,
  pointMenu: (ref: string) => `store-service-point-point-menu-${slug(ref)}`,
  pointMenuAction: (ref: string, action: string) => `store-service-point-point-menu-${slug(ref)}-${slug(action)}`,
  areaDrawer: 'store-service-point-area-drawer',
  areaName: 'store-service-point-area-name',
  areaCode: 'store-service-point-area-code',
  areaType: 'store-service-point-area-type',
  areaStatus: 'store-service-point-area-status',
  areaSave: 'store-service-point-area-save',
  areaCancel: 'store-service-point-area-cancel',
  pointDrawer: (type: 'table' | 'scan') => `store-service-point-${type}-drawer`,
  pointName: 'store-service-point-name',
  pointCode: 'store-service-point-code',
  pointCapacity: 'store-service-point-capacity',
  pointShape: 'store-service-point-shape',
  pointReservable: 'store-service-point-reservable',
  pointImageUpload: 'store-service-point-image-upload',
  pointExtension: 'store-service-point-extension',
  pointSave: 'store-service-point-save',
  pointCancel: 'store-service-point-cancel',
  detailDrawer: 'store-service-point-detail-drawer',
  detailAction: 'store-service-point-detail-action',
  qrConfig: 'store-service-point-qr-config',
  qrEdit: 'store-service-point-qr-edit',
  qrDrawer: 'store-service-point-qr-drawer',
  qrEnabled: 'store-service-point-qr-enabled',
  qrChannel: 'store-service-point-qr-channel',
  qrChannelOption: (ref: string) => `store-service-point-qr-channel-option-${slug(ref)}`,
  qrSave: 'store-service-point-qr-save',
  qrCancel: 'store-service-point-qr-cancel',
  qrResult: 'store-service-point-qr-result',
  qrResultImage: (ref: string) => `store-service-point-qr-result-image-${slug(ref)}`,
} as const;
