CREATE SCHEMA platform_workspace;
CREATE SCHEMA organization;

CREATE TABLE platform_workspace.group_workspace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_workspace_key VARCHAR(120) NOT NULL,
    name VARCHAR(200) NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('ENABLED', 'DISABLED')),
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_group_workspace_key UNIQUE (group_workspace_key),
    CONSTRAINT uq_group_workspace_composite_ref UNIQUE (group_workspace_key, id)
);

CREATE TABLE organization.commercial_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_workspace_key VARCHAR(120) NOT NULL,
    group_workspace_id BIGINT NOT NULL,
    commercial_group_code VARCHAR(64) NOT NULL,
    commercial_group_name VARCHAR(120) NOT NULL,
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision = 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_platform_subject VARCHAR(255) NOT NULL,
    CONSTRAINT uq_commercial_group_workspace UNIQUE (group_workspace_key, group_workspace_id),
    CONSTRAINT fk_commercial_group_workspace FOREIGN KEY (group_workspace_key, group_workspace_id)
        REFERENCES platform_workspace.group_workspace (group_workspace_key, id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

CREATE TABLE organization.commercial_group_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commercial_group_id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    platform_subject VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_commercial_group_audit_group FOREIGN KEY (commercial_group_id)
        REFERENCES organization.commercial_group (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

CREATE TABLE organization.commercial_group_idempotency (
    idempotency_key VARCHAR(200) PRIMARY KEY,
    group_workspace_key VARCHAR(120) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    commercial_group_id BIGINT,
    commercial_group_code VARCHAR(64),
    commercial_group_name VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_commercial_group_idempotency_group FOREIGN KEY (commercial_group_id)
        REFERENCES organization.commercial_group (id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

ALTER TABLE platform_workspace.group_workspace ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_workspace.group_workspace FORCE ROW LEVEL SECURITY;
CREATE POLICY platform_admin_group_workspace_access ON platform_workspace.group_workspace
    USING (current_setting('app.consumer_face', true) = 'platform-admin'
       AND current_setting('app.platform_subject', true) <> '');

ALTER TABLE organization.commercial_group ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.commercial_group FORCE ROW LEVEL SECURITY;
CREATE POLICY platform_admin_commercial_group_access ON organization.commercial_group
    USING (current_setting('app.consumer_face', true) = 'platform-admin'
       AND current_setting('app.platform_subject', true) <> '');

ALTER TABLE organization.commercial_group_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.commercial_group_audit FORCE ROW LEVEL SECURITY;
CREATE POLICY platform_admin_commercial_group_audit_access ON organization.commercial_group_audit
    USING (current_setting('app.consumer_face', true) = 'platform-admin'
       AND current_setting('app.platform_subject', true) <> '');

ALTER TABLE organization.commercial_group_idempotency ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization.commercial_group_idempotency FORCE ROW LEVEL SECURITY;
CREATE POLICY platform_admin_commercial_group_idempotency_access ON organization.commercial_group_idempotency
    USING (current_setting('app.consumer_face', true) = 'platform-admin'
       AND current_setting('app.platform_subject', true) <> '');
