import {Alert, Button, Card, Form, Input, Space, Steps} from 'antd';
import {testId, useOverlayLock, useSubmissionLifecycle} from '@catering-v2s/admin-ui-foundation';
import {useState} from 'react';
import {useNavigate} from 'react-router';
import {platformClient, platformProblemOf, type PlatformApiProblem} from '../../../app/api/PlatformTransport';

type PasswordValue = {newPassword: string; confirmation: string};
export function PlatformPasswordRecoveryPasswordPage() {
  const [form] = Form.useForm<PasswordValue>(); const [problem, setProblem] = useState<PlatformApiProblem>(); const lifecycle = useSubmissionLifecycle(); const locked = useOverlayLock(); const navigate = useNavigate();
  return <main className="auth-page"><Card className="auth-card" title="设置新密码"><Steps current={1} items={[{title: '验证身份'}, {title: '设置新密码'}, {title: '完成'}]}/>{problem && <Alert type="error" showIcon title={problem.title} description={problem.detail}/>}<Form form={form} layout="vertical" onFinish={async (value) => { lifecycle.markBusinessIntentChanged(); setProblem(undefined); try { await platformClient.completePlatformPasswordRecovery({}, {body: {newPassword: value.newPassword}, headers: {'Idempotency-Key': lifecycle.getIdempotencyKey()}}); form.resetFields(); await navigate('/platform/password-recovery/complete'); } catch (error) { form.resetFields(['newPassword', 'confirmation']); setProblem(platformProblemOf(error)); } }}><Form.Item name="newPassword" label="新密码" rules={[{required: true, min: 8}]}><Input.Password autoComplete="new-password" {...testId('platform-recovery-new-password')}/></Form.Item><Form.Item name="confirmation" label="确认新密码" dependencies={['newPassword']} rules={[{required: true}, ({getFieldValue}) => ({validator: (_, value) => value === getFieldValue('newPassword') ? Promise.resolve() : Promise.reject(new Error('两次输入的密码不一致'))})]}><Input.Password autoComplete="new-password" {...testId('platform-recovery-confirmation')}/></Form.Item><Space><Button onClick={() => void navigate('/platform/password-recovery/verify')} {...testId('platform-recovery-previous')}>上一步</Button><Button type="primary" htmlType="submit" disabled={locked} {...testId('platform-recovery-complete')}>提交</Button></Space></Form></Card></main>;
}
