import {Alert, Button, Card, Form, Input, Space, Steps} from 'antd';
import {testId, useOverlayLock, useSubmissionLifecycle} from '@catering-v2s/admin-ui-foundation';
import {useState} from 'react';
import {useNavigate} from 'react-router';
import {platformClient, platformProblemOf, type PlatformApiProblem} from '../../../app/api/PlatformTransport';
import {adminCatalog, platformShellCopyKeys} from '../../../app/catalog/generatedAdminCatalog';

type RecoveryVerifyValue = {loginName: string; mobile: string; code: string};

/** Public recovery verification keeps the opaque recovery flow in its secure owner cookie. */
export function PlatformPasswordRecoveryVerifyPage() {
  const [form] = Form.useForm<RecoveryVerifyValue>(); const [sent, setSent] = useState(false); const [debugCode, setDebugCode] = useState<string>(); const [problem, setProblem] = useState<PlatformApiProblem>(); const [sendingOtp, setSendingOtp] = useState(false); const [submitting, setSubmitting] = useState(false);
  const lifecycle = useSubmissionLifecycle(); const locked = useOverlayLock(); const navigate = useNavigate();
  const invalidateOtp = () => { setSent(false); setDebugCode(undefined); form.setFieldValue('code', undefined); };
  const sendOtp = async () => { let value: Pick<RecoveryVerifyValue, 'loginName' | 'mobile'>; try { value = await form.validateFields(['loginName', 'mobile']); } catch { return; } setSendingOtp(true); lifecycle.markBusinessIntentChanged(); setProblem(undefined); try { await platformClient.startPlatformPasswordRecovery({}, {body: value, headers: {'Idempotency-Key': lifecycle.getIdempotencyKey()}}); lifecycle.markBusinessIntentChanged(); const response = await platformClient.sendPlatformPasswordRecoveryOtp({}, {body: {}, headers: {'Idempotency-Key': lifecycle.getIdempotencyKey()}}); const debugCode = response.debugVerificationCode ?? undefined; setSent(true); setDebugCode(debugCode); form.setFieldValue('code', debugCode); } catch (error) { invalidateOtp(); setProblem(platformProblemOf(error)); } finally { setSendingOtp(false); } };
  return <main className="auth-page"><Card className="auth-card" title={`找回${adminCatalog.platformShellCopy[platformShellCopyKeys.PlatformShellBrand]}密码`}><Steps current={0} items={[{title: '验证身份'}, {title: '设置新密码'}, {title: '完成'}]}/>{problem && <Alert type="error" showIcon title={problem.title} description={problem.detail}/>}<p>如果信息匹配，验证码将发送到该手机号。</p><Form form={form} layout="vertical" onFinish={async (value) => { setSubmitting(true); lifecycle.markBusinessIntentChanged(); setProblem(undefined); try { await platformClient.verifyPlatformPasswordRecoveryOtp({}, {body: {code: value.code}, headers: {'Idempotency-Key': lifecycle.getIdempotencyKey()}}); await navigate('/platform/password-recovery/password'); } catch (error) { form.setFieldValue('code', undefined); setProblem(platformProblemOf(error)); } finally { setSubmitting(false); } }}><Form.Item name="loginName" label="登录名" rules={[{required: true, whitespace: true}]}><Input disabled={submitting || sendingOtp} onChange={invalidateOtp} {...testId('platform-recovery-login-name')}/></Form.Item><Form.Item name="mobile" label="手机号" rules={[{required: true, pattern: /^1\d{10}$/, message: '请输入正确的手机号'}]}><Input disabled={submitting || sendingOtp} onChange={invalidateOtp} {...testId('platform-recovery-mobile')}/></Form.Item><Form.Item label="验证码" required><Space.Compact block><Form.Item name="code" noStyle rules={[{required: true, pattern: /^\d{6}$/, message: '请输入6位验证码'}]}><Input disabled={!sent || submitting} {...testId('platform-recovery-otp')}/></Form.Item><Button htmlType="button" onClick={() => void sendOtp()} loading={sendingOtp} disabled={locked || submitting || sendingOtp} {...testId('platform-recovery-send-otp')}>获取验证码</Button></Space.Compact></Form.Item>{debugCode && <Alert type="info" showIcon title={`当前为测试环境，验证码：${debugCode}`}/>}<Space><Button type="primary" htmlType="submit" disabled={!sent || locked || submitting || sendingOtp} {...testId('platform-recovery-verify')}>下一步</Button><Button disabled={submitting || sendingOtp} onClick={() => void navigate('/platform/login')} {...testId('platform-recovery-return-login')}>返回登录</Button></Space></Form></Card></main>;
}
